Repository finos/legend-engine, pull requests merged in 2022-06, with the labels that each got.

#697 Stricter enforce rule on execution and generation collection modules
  legend-engine-executionPlan-dependencies/pom.xml
  legend-engine-executionPlan-execution-api/pom.xml
  legend-engine-executionPlan-execution-store-inMemory/pom.xml
  legend-engine-executionPlan-execution/pom.xml
  legend-engine-extensions-collection-execution/pom.xml
  legend-engine-extensions-collection-generation/pom.xml
  legend-engine-external-shared-format-runtime/pom.xml
  legend-engine-xt-flatdata-runtime/pom.xml
  legend-engine-xt-xml-runtime/pom.xml
  pom.xml
Labels: cla-present

#693 SQLQueryToString: Quote window keyword for MemSQL
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/tests/testMemSQLCompatibility.pure
Labels: cla-present

#707 Remove service store deprecated code
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/plugin/ServiceExecutionNodeExecutor.java
  legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/deprecatedGrammar/features/batching/TestServiceStoreBatching.java
  legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/deprecatedGrammar/features/flags/TestServiceStoreParameterFlags.java
  legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/deprecatedGrammar/features/pathOffset/TestServiceStorePathOffset.java
  legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/deprecatedGrammar/features/union/TestServiceStoreUnion.java
  legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/deprecatedGrammar/showcase/flatdataApis/ServiceStoreFlatdataShowcaseTest.java
  legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/deprecatedGrammar/showcase/jsonApis/ServiceStoreJsonShowcaseTest.java
  legend-engine-xt-serviceStore-grammar/pom.xml
  legend-engine-xt-serviceStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceStoreMappingCompilationFromGrammar.java
  legend-engine-xt-serviceStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceStoreMappingGrammarRoundtrip.java
Labels: cla-present

#714 Add missing copyrights
  legend-engine-xt-relationalStore-pure/src/test/java/org/finos/legend/pure/code/core/relational/dbSpecific/Test_Pure_Relational_DbSpecific_H2.java
  legend-engine-xt-relationalStore-pure/src/test/java/org/finos/legend/pure/code/core/relational/dbSpecific/Test_Pure_Relational_DbSpecific_Redshift.java
  legend-engine-xt-relationalStore-pure/src/test/java/org/finos/legend/pure/code/core/relational/dbSpecific/Test_Pure_Relational_DbSpecific_Snowflake.java
  legend-engine-xt-relationalStore-pure/src/test/java/org/finos/legend/pure/code/core/relational/dbSpecific/Test_Pure_Relational_DbSpecific_SqlServer.java
Labels: cla-present

#713 Upgrade to Pure 2.2.1 and Engine 0.22.0
  pom.xml
Labels: cla-present

#716 Ensure the relational DB specific tests are not executed
  legend-engine-server/src/test/java/org/finos/legend/engine/server/test/pureClient/stores/dbSpecific/Relational_DbSpecific_UsingPureClientTestSuite.java
  legend-engine-server/src/test/java/org/finos/legend/engine/server/test/pureClient/stores/dbSpecific/Test_Relational_DbSpecific_H2_UsingPureClientTestSuite.java
  legend-engine-server/src/test/java/org/finos/legend/engine/server/test/pureClient/stores/dbSpecific/Test_Relational_DbSpecific_Redshift_UsingPureClientTestSuite.java
  legend-engine-server/src/test/java/org/finos/legend/engine/server/test/pureClient/stores/dbSpecific/Test_Relational_DbSpecific_Snowflake_UsingPureClientTestSuite.java
  legend-engine-server/src/test/java/org/finos/legend/engine/server/test/pureClient/stores/dbSpecific/Test_Relational_DbSpecific_SqlServer_UsingPureClientTestSuite.java
Labels: cla-present

#717 Fix flow provider configuration
  .github/workflows/database-snowflake-sql-generation-integration-test.yml
  legend-engine-xt-relationalStore-executionPlan-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProvider_Redshift.java
Labels: cla-present

#711 refactor dyna fn sqlQueryToString
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/dbSpecificProcessor.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/processInOperation.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/trimColumnNamePostProcessor.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/postProcessor.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalTypeTranslations.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
Labels: cla-present

#706 Assorted protobuf improvements and fixes
  legend-engine-pure-ide-light/src/main/java/org/finos/legend/engine/ide/PureIDELight.java
  legend-engine-xt-protobuf-grammar/src/main/java/org/finos/legend/engine/language/protobuf3/grammar/from/Protobuf3GrammarParser.java
  legend-engine-xt-protobuf-grammar/src/main/java/org/finos/legend/engine/language/protobuf3/grammar/to/Protobuf3GrammarComposer.java
  legend-engine-xt-protobuf-grammar/src/test/java/org/finos/legend/engine/language/protobuf3/grammar/test/TestProtobuf3.java
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/metamodel/metamodel.pure
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/metamodel/metamodel_serialization.pure
Labels: cla-present

#722 Update README.md
  README.md
Labels: cla-present

#655 Support current user id in engine.
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/store/platform/PredefinedExpressions.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/PlanExecutor.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/helpers/platform/ExecutionNodeJavaPlatformHelper.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/state/ExecutionState.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
  legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
  legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/simpleRelationalService.pure
Labels: cla-present, requires PURE

#712 Avoid index out of bound exception if result has no activities
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/object/StreamingObjectResultJSONSerializer.java
Labels: bug, cla-present

#723 Limit max size returned by buildUniqueName in pureToSqlQuery
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
Labels: cla-present

#686 Opensource postgres connector support
  .github/workflows/database-postgresql-integration-test.yml
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/src/main/java/org/finos/legend/engine/authentication/LegendDefaultDatabaseAuthenticationFlowProvider.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/src/main/java/org/finos/legend/engine/authentication/flows/PostgresStaticWithUserPasswordFlow.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/src/test/java/org/finos/legend/engine/authentication/TestDefaultSupportedFlows.java
  legend-engine-xt-relationalStore-executionPlan-connection-tests/pom.xml
  legend-engine-xt-relationalStore-executionPlan-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProvider_Postgres.java
  legend-engine-xt-relationalStore-executionPlan-connection/pom.xml
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/DatabaseManager.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/commands/RelationalDatabaseCommandsVisitor.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/postgres/PostgresCommands.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/postgres/PostgresDriver.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/postgres/PostgresManager.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/StreamResultToTempTableVisitor.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalConnectionGrammarRoundtrip.java
  pom.xml
Labels: cla-present

#735 Clean up Protobuf generation configs
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/deprecated.pure
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/protocol/protocol_v1_23_0.pure
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/protocol/protocol_vX_X_X.pure
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/transformation/transformation.pure
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/transformation/transformation_tests.pure
  legend-engine-xt-protobuf/pom.xml
  legend-engine-xt-protobuf/src/main/java/org/finos/legend/engine/external/format/protobuf/ProtobufFormatExtension.java
  legend-engine-xt-protobuf/src/main/java/org/finos/legend/engine/external/format/protobuf/deprecated/generation/configuration/Options.java
  legend-engine-xt-protobuf/src/main/java/org/finos/legend/engine/external/format/protobuf/deprecated/generation/configuration/ProtobufGenerationConfig.java
  legend-engine-xt-protobuf/src/main/java/org/finos/legend/engine/external/format/protobuf/fromModel/ModelToProtobufConfiguration.java
Labels: cla-present

#729 Speed up java generation by avoiding duplicate interface and enum generation
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/graphFetchCommon.pure
Labels: cla-present

#730 create one file per relational db
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/relationalGraphFetch.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/helperFunctions/databaseHelperFunctions.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/helperFunctions/toDDL.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/metamodel/diagram/relationalOperationDiagram.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/metamodel/metamodel.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/milestoning.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/processInOperation.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/processObjectReferenceIn.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/reAliasQuery.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/trimColumnNamePostProcessor.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/postProcessor.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/metamodel.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/router/router_extension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/bigQueryExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/compositeExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/databricksExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/db2Extension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/defaultExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/h2Extension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/hiveExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/memSqlExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/postgresExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/prestoExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/redshiftExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/snowflakeExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/sqlServerExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/sybaseASEExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/sybaseIQExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/testDataGeneration/testDataGeneration.pure
Labels: cla-present

#718 handle circular constraints
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/inMemory/graphFetchInMemory.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/shared/constraints.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/shared/mappingAdaptor.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetch_routing.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_routing.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/javaRuntime/executionPlanNodes/graphFetch/graphFetchRelational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/testSimpleRelationalGraphFetch.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/modelWithConstraints.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/relationalSetUp.pure
Labels: cla-present

#739 Remove deprecated protocol models
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/ServiceParametersResolutionExecutionNode.java
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/service/mapping/ParameterIndexedParameterMapping.java
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/service/mapping/PropertyIndexedParameterMapping.java
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/service/mapping/ServiceMapping.java
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/service/mapping/ServiceParameterMapping.java
Labels: cla-present

#741 Set userId result before executing auth dependent plans
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/PlanExecutor.java
Labels: cla-present

#743 remove unnecessary instructions as core repos have been moved to legend-engine
  legend-engine-pure-ide-light/README.md
Labels: cla-present

#744 Service store supports take
  legend-engine-pure-code-compiled-core-external-shared/src/main/resources/core_external_shared/executionPlan/executionPlan.pure
  legend-engine-pure-code-compiled-core-external-shared/src/main/resources/core_external_shared/executionPlan/model.pure
  legend-engine-pure-code-compiled-core-external-shared/src/main/resources/core_external_shared/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/extensions/extension.pure
  legend-engine-xt-flatdata-pure/src/main/resources/core_external_format_flatdata/protocol_vX_X_X.pure
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/ServiceStoreExecutionExtension.java
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/plugin/ServiceExecutionNodeExecutor.java
  legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/showcase/jsonApis/ServiceStoreJsonShowcaseTest.java
  legend-engine-xt-serviceStore-executionPlan/src/test/resources/showcase/json/mappings/stub.json
  legend-engine-xt-serviceStore-executionPlan/src/test/resources/showcase/json/testGrammar.pure
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/ServiceStoreProtocolExtension.java
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/LimitExecutionNode.java
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan_generation.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan_print.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/javaRuntime/executionPlanNodes/limit/limit.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/vX_X_X/extension/extension_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/vX_X_X/models/executionPlan_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/pureToServiceStoreQuery/pureToServiceStoreQuery.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/router/router_extension.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/router/tests/testRouting.pure
  legend-engine-xt-xml-pure/src/main/resources/core_external_format_xml/protocol_vX_X_X.pure
Labels: cla-present

#746 Use daemon thread to avoid holding VM on service execution jars
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/state/ConnectionStateManager.java
Labels: cla-present

#745 Remove deepfetch references
  legend-engine-pure-code-compiled-core/src/main/resources/core/java/generation/conventions.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/deepfetch/deepFetch_builder.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/deepfetch/deepFetch_execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/XStore.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/mappingExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_entry.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_main.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_routing.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_20_0/invocations/execution_relational_execute.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_21_0/invocations/execution_relational_execute.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_22_0/invocations/execution_relational_execute.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_23_0/invocations/execution_relational_execute.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/invocations/execution_relational_execute.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/transform/fromPure/toSQLString.pure
Labels: cla-present

#747 Adjusting heap size for release action
  .github/workflows/build.yml
  .github/workflows/database-bigquery-integration-test.yml
  .github/workflows/database-databricks-integration-test.yml
  .github/workflows/database-databricks-sql-generation-integration-test.yml
  .github/workflows/database-mssqlserver-integration-test.yml
  .github/workflows/database-mssqlserver-sql-generation-integration-test.yml
  .github/workflows/database-postgresql-integration-test.yml
  .github/workflows/database-redshift-integration-test.yml
  .github/workflows/database-redshift-sql-generation-integration-test.yml
  .github/workflows/database-snowflake-integration-test.yml
  .github/workflows/database-snowflake-sql-generation-integration-test.yml
  .github/workflows/release.yml
Labels: cla-present

#749 Fix defaulting optional param for null params
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/helpers/platform/DefaultExecutionNodeContext.java
  legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
Labels: cla-present

#751 Updating release action commands
  .github/workflows/release.yml
Labels: cla-present

#754 Added TDS stats helper functions (Interquartile range classification, Z-score)
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/mathExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/math/mathExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tds/tdsExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tds/tests/testTdsExtension.pure
Labels: cla-present

#752 Fix JSON to Grammar transformation when Applied functions are passed as parameters.
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperValueSpecificationGrammarComposer.java
  legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java
  legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestLambdaRoundtrip.java
Labels: cla-present

#758 Fix the csv package issue cause by merge conflict
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tds/tests/testTdsExtension.pure
Labels: cla-present

#762 Running DB integration tests once a day
  .github/workflows/database-bigquery-integration-test.yml
  .github/workflows/database-databricks-integration-test.yml
  .github/workflows/database-databricks-sql-generation-integration-test.yml
  .github/workflows/database-mssqlserver-integration-test.yml
  .github/workflows/database-mssqlserver-sql-generation-integration-test.yml
  .github/workflows/database-postgresql-integration-test.yml
  .github/workflows/database-redshift-integration-test.yml
  .github/workflows/database-redshift-sql-generation-integration-test.yml
  .github/workflows/database-snowflake-integration-test.yml
  .github/workflows/database-snowflake-sql-generation-integration-test.yml
Labels: cla-present

#761 Specifying maven profiles correctly
  .github/workflows/release.yml
Labels: cla-present

#760 minor testable api fixes
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/CorePureProtocolExtension.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/assertion/status/AssertionStatus.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/result/TestResult.java
  legend-engine-server/pom.xml
  legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
  legend-engine-testable/pom.xml
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/TestableRunner.java
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/api/Testable.java
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/model/RunTestsInput.java
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/model/RunTestsResult.java
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/model/RunTestsTestableInput.java
Labels: cla-present

#764 make dataspace and diagram API more robust and backward-compatible
  legend-engine-external-shared/src/main/java/org/finos/legend/engine/external/shared/format/imports/PureModelContextDataGenerator.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/metamodel_diagram.pure
  legend-engine-xt-data-space-api/pom.xml
  legend-engine-xt-data-space-api/src/main/java/org/finos/legend/engine/api/analytics/DataSpaceAnalytics.java
  legend-engine-xt-data-space-api/src/main/java/org/finos/legend/engine/api/analytics/DataSpaceAnalyticsHelper.java
  legend-engine-xt-data-space-api/src/main/java/org/finos/legend/engine/api/analytics/model/DataSpaceAnalysisResult.java
  legend-engine-xt-data-space-api/src/test/java/org/finos/legend/engine/api/analytics/test/TestDataSpaceAnalyticsApi.java
  legend-engine-xt-data-space-api/src/test/resources/dataSpaceAnalyticsTestData.json
  legend-engine-xt-data-space-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/DataSpaceLexerGrammar.g4
  legend-engine-xt-data-space-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/DataSpaceParserGrammar.g4
  legend-engine-xt-data-space-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/DataSpaceParseTreeWalker.java
  legend-engine-xt-data-space-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestDataSpaceGrammarRoundtrip.java
  legend-engine-xt-data-space-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/dataSpace/DataSpace.java
  legend-engine-xt-data-space-protocol/src/test/java/org/finos/legend/engine/protocol/pure/v1/test/TestDataSpaceProtocol.java
  legend-engine-xt-data-space-protocol/src/test/resources/dataSpace_DeprecatedModel.json
  legend-engine-xt-diagram-api/pom.xml
  legend-engine-xt-diagram-api/src/main/java/org/finos/legend/engine/api/analytics/DiagramAnalytics.java
  legend-engine-xt-diagram-api/src/main/java/org/finos/legend/engine/api/analytics/model/DiagramModelCoverageAnalysisResult.java
  legend-engine-xt-diagram-api/src/test/java/org/finos/legend/engine/api/analytics/test/TestDiagramAnalyticsApi.java
  legend-engine-xt-diagram-api/src/test/resources/diagramAnalyticsTestData.json
  legend-engine-xt-diagram-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/DiagramParseTreeWalker.java
  legend-engine-xt-diagram-pure/src/main/resources/core_diagram/analytics/analytics.pure
  legend-engine-xt-diagram-pure/src/main/resources/core_diagram/metamodel_diagram.pure
  legend-engine-xt-text-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/TextParseTreeWalker.java
Labels: cla-present

#766 Cleanup StoreContract definition file names
  legend-engine-configuration/src/main/java/org/finos/legend/engine/plan/generation/extension/LegendPlanGeneratorExtension.java
  legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
  legend-engine-server/src/test/java/org/finos/legend/engine/server/test/shared/TestMetaDataServer.java
  legend-engine-test-runner-mapping/src/test/java/org/finos/legend/engine/test/runner/mapping/TestMappingTestRunner.java
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestRunner.java
  legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/test/runner/service/TestServiceTestRunner.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/debug/GraphQLDebug.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecute.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/AlloyTestServer.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/graphFetch/cache/TestPlanExecutionWithGraphFetchCrossKeyCache.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/AbstractTestSemiStructured.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/contract/storeContract.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/extensions/extension.pure
  legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/utils/ServiceStoreTestUtils.java
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/contract/storeContract.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/extensions/extension.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/router/router_extension.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/serviceStoreApi.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/tests/testRouting.pure
Labels: cla-present

#753 Do not handle views when building relation tree from SQL query
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/lineage/scanRelations/scanRelations.pure
Labels: cla-present

#768 Add base64 SQL function translations
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/LegendH2Extensions.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/DefaultH2AuthenticationStrategy.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/h2Extension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/memSqlExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/sqlFunction/testSqlFunctionsInMapping.pure
Labels: cla-present

#767 attempt to fix Build CI workflow in master
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: cla-present

#773 Upgrade Pure to 3.1.0
  pom.xml
Labels: cla-present

#757 refactor testable mechanism
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/extension/CompilerExtension.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/extension/CompilerExtensions.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/test/TestFirstPassBuilder.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/ServiceCompilerExtensionImpl.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/test/diagram.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/test/testable.pure
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestableRunnerExtension.java
  legend-engine-testable/pom.xml
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/TestableRunner.java
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/extension/TestableRunnerExtension.java
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/extension/TestableRunnerExtensionLoader.java
Labels: cla-present, requires PURE

#769 Add missing dependencies
  legend-engine-extensions-collection-generation/pom.xml
  legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
Labels: cla-present

#771 Expose relational builder utility methods to avoid duplication on extensions
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
Labels: cla-present

#775 Fix an issue with GraphFetch plan generation when types are mapped to…
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/testUnion.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/modelToModel.pure
Labels: cla-present
