Repository finos/legend-engine, pull requests merged in 2022-11, with the labels that each got.

#1091 Mastery id refactor
  legend-engine-xt-mastery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/MasteryLexerGrammar.g4
  legend-engine-xt-mastery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/MasteryParserGrammar.g4
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/MasteryParseTreeWalker.java
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/to/HelperMasteryGrammarComposer.java
  legend-engine-xt-mastery-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/test/TestMasteryCompilationFromGrammar.java
  legend-engine-xt-mastery-pure/src/main/resources/core_mastery/mastery/metamodel_diagram.pure
Labels: cla-present

#1071 Fix few partial union SQL gen issues
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/helperFunctions/helperFunctions.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery_union.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/extends/union/testExtendsForPropertyMappingWithUnion.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/union/testUnion.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/union/testUnionPartial.pure
Labels: bug, cla-present, not backwards compatible

#1097 Revert "Mastery id refactor"
  legend-engine-xt-mastery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/MasteryLexerGrammar.g4
  legend-engine-xt-mastery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/MasteryParserGrammar.g4
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/MasteryParseTreeWalker.java
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/to/HelperMasteryGrammarComposer.java
  legend-engine-xt-mastery-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/test/TestMasteryCompilationFromGrammar.java
  legend-engine-xt-mastery-pure/src/main/resources/core_mastery/mastery/metamodel_diagram.pure
Labels: cla-present

#1095 Add tests for enum param in testables
  legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java
  legend-engine-test-runner-service/src/test/resources/testable/relational/legend-testable-relational-model.pure
  legend-engine-test-runner-service/src/test/resources/testable/relational/legend-testable-relational-service-enum-parameters.pure
Labels: cla-present

#1094 M2M - Match Return Multiplicity & Null
  legend-engine-pure-code-compiled-core/src/main/resources/core/external/language/java/generation/conventions.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/external/language/java/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/langLibrary.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/qualifiedProperties.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/shared.pure
Labels: cla-present

#1098 Upgrade legend-pure version to 3.7.2
  pom.xml
Labels: cla-present

#1030 Implement the first version of Change Tokens
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/changetoken/changetoken.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/changetoken/changetoken_diagram.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/changetoken/changetoken_test.pure
Labels: cla-present

#1100 Fix service store mapping processing bug
  legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/showcase/jsonApis/ServiceStoreJsonShowcaseTest.java
  legend-engine-xt-serviceStore-executionPlan/src/test/resources/showcase/json/testGrammar.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan_generation.pure
Labels: bug, cla-present

#1079 relay to appropriate extension instead of h2 for ddl commands
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/dbTestRunner/shared.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/helperFunctions/helperFunctions.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/helperFunctions/toDDL.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/defaultExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/aggregateFunctions/groupBy.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/dynaFunctions/date.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/shared.pure
  legend-engine-xt-relationalStore-test-server/src/main/java/org/finos/legend/engine/server/test/shared/ExecuteInRelationalDb.java
Labels: cla-present

#1109 Support user defined functions in service store parameter gen logic
  legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/showcase/jsonApis/ServiceStoreJsonShowcaseTest.java
  legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/utils/ServiceStoreTestUtils.java
  legend-engine-xt-serviceStore-executionPlan/src/test/resources/showcase/json/testGrammar.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/javaRuntime/executionPlanNodes/serviceParametersResolution/serviceParametersResolution.pure
Labels: enhancement, cla-present

#1107 Disable non-mapped service parameters to be populated while processing the url
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/ServiceExecutor.java
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/plugin/ServiceExecutionNodeExecutor.java
  legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/showcase/jsonApis/ServiceStoreJsonShowcaseTest.java
  legend-engine-xt-serviceStore-executionPlan/src/test/resources/showcase/json/mappings/stub.json
  legend-engine-xt-serviceStore-executionPlan/src/test/resources/showcase/json/testGrammar.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan_generation.pure
Labels: bug, cla-present

#1111 Support testing of semi structured mappings with parseJson
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/LegendH2Extensions.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/DefaultH2AuthenticationStrategy.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredParseJsonMapping.java
  legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/semiStructuredParseJsonMapping.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/h2Extension.pure
Labels: bug, cla-present

#1114 update java Docker image to `eclipse-temurin:11.0.17_8-jdk-jammy`
  legend-engine-server/Dockerfile
Labels: cla-present

#1072 Daml
  legend-engine-pure-ide-light/src/main/java/org/finos/legend/engine/ide/PureIDELight.java
  legend-engine-server/pom.xml
  legend-engine-xt-daml-grammar/pom.xml
  legend-engine-xt-daml-grammar/src/main/java/org/finos/legend/engine/language/daml/grammar/from/DamlGrammarParser.java
  legend-engine-xt-daml-grammar/src/main/java/org/finos/legend/engine/language/daml/grammar/to/DamlGrammarComposer.java
  legend-engine-xt-daml-grammar/src/test/java/org/finos/legend/engine/language/haskell/grammar/test/TestGrammar.java
  legend-engine-xt-daml-model/pom.xml
  legend-engine-xt-daml-model/src/main/java/org/finos/legend/engine/external/format/daml/DamlFormatExtension.java
  legend-engine-xt-daml-model/src/main/java/org/finos/legend/engine/external/format/daml/fromModel/ModelToDamlConfiguration.java
  legend-engine-xt-daml-model/src/main/java/org/finos/legend/engine/external/format/daml/toModel/DamlToModelConfiguration.java
  legend-engine-xt-daml-model/src/main/resources/META-INF/services/org.finos.legend.engine.external.shared.format.model.ExternalFormatExtension
  legend-engine-xt-daml-model/src/test/java/org/finos/legend/engine/external/format/daml/fromModel/TestModelToDamlSchemaGeneration.java
  legend-engine-xt-daml-pure/pom.xml
  legend-engine-xt-daml-pure/src/main/java/org/finos/legend/engine/code/core/CoreExternalLanguageDamlCodeRepositoryProvider.java
  legend-engine-xt-daml-pure/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.filesystem.repository.CodeRepositoryProvider
  legend-engine-xt-daml-pure/src/main/resources/core_external_language_daml.definition.json
  legend-engine-xt-daml-pure/src/main/resources/core_external_language_daml/externalFormatContract.pure
  legend-engine-xt-daml-pure/src/main/resources/core_external_language_daml/pureToDaml.pure
  legend-engine-xt-daml-pure/src/main/resources/core_external_language_daml/serialization.pure
  legend-engine-xt-daml-pure/src/main/resources/core_external_language_daml/tests/testPureToDaml.pure
  legend-engine-xt-daml-pure/src/main/resources/core_external_language_daml/tests/testTransformation.pure
  legend-engine-xt-daml-pure/src/main/resources/core_external_language_daml/transformation.pure
  legend-engine-xt-haskell-grammar/pom.xml
  legend-engine-xt-haskell-grammar/src/main/antlr4/org/finos/legend/engine/language/haskell/grammar/from/antlr4/HaskellLexer.g4
  legend-engine-xt-haskell-grammar/src/main/antlr4/org/finos/legend/engine/language/haskell/grammar/from/antlr4/HaskellParser.g4
  legend-engine-xt-haskell-grammar/src/main/java/org/finos/legend/engine/language/haskell/grammar/from/HaskellGrammarParser.java
  legend-engine-xt-haskell-grammar/src/main/java/org/finos/legend/engine/language/haskell/grammar/from/HaskellParserException.java
  legend-engine-xt-haskell-grammar/src/main/java/org/finos/legend/engine/language/haskell/grammar/from/antlr4/HaskellBaseLexer.java
  legend-engine-xt-haskell-grammar/src/main/java/org/finos/legend/engine/language/haskell/grammar/to/HaskellGrammarComposer.java
  legend-engine-xt-haskell-grammar/src/test/java/org/finos/legend/engine/language/haskell/grammar/test/TestGrammar.java
  legend-engine-xt-haskell-protocol/pom.xml
  legend-engine-xt-haskell-pure/pom.xml
  legend-engine-xt-haskell-pure/src/main/java/org/finos/legend/engine/code/core/CoreExternalLanguageHaskellCodeRepositoryProvider.java
  legend-engine-xt-haskell-pure/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.filesystem.repository.CodeRepositoryProvider
  legend-engine-xt-haskell-pure/src/main/resources/core_external_language_haskell.definition.json
  legend-engine-xt-haskell-pure/src/main/resources/core_external_language_haskell/externalFormatContract.pure
  legend-engine-xt-haskell-pure/src/main/resources/core_external_language_haskell/metamodel.pure
  legend-engine-xt-haskell-pure/src/main/resources/core_external_language_haskell/pureToHaskell.pure
  legend-engine-xt-haskell-pure/src/main/resources/core_external_language_haskell/serialization.pure
  legend-engine-xt-haskell-pure/src/main/resources/core_external_language_haskell/tests/testPureToHaskell.pure
  legend-engine-xt-haskell-pure/src/main/resources/core_external_language_haskell/tests/testSerialization.pure
  legend-engine-xt-haskell-pure/src/main/resources/core_external_language_haskell/transformation.pure
  pom.xml
Labels: cla-present

#1081 Support for memsql create statement with shards and column store specification
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-core/src/main/java/org/finos/legend/engine/persistence/components/relational/sqldom/schemaops/statements/CreateTable.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/MemSqlSink.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sql/visitor/SQLCreateVisitor.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sql/visitor/SchemaDefinitionVisitor.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sqldom/common/Clause.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sqldom/constraints/table/ClusteredColumnStoreIndexConstraint.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sqldom/constraints/table/ShardKeyConstraint.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sqldom/constraints/table/UnenforcedUniqueIndexConstraint.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/IngestModeTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/MemsqlTestArtifacts.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalDeltaTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/logicalplan/operations/BaseTestUtils.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/logicalplan/operations/CreateTest.java
Labels: cla-present

#1082 Delete Indicator Support for Nontemporal Delta
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/NontemporalDeltaPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/Planner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/UnitemporalDeltaPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/nontemporal/NontemporalDeltaTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/main/java/org/finos/legend/engine/persistence/components/relational/h2/H2Sink.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/java/org/finos/legend/engine/persistence/components/TestUtils.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/nontemporal/AppendOnlyTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/nontemporal/NontemporalDeltaMergeTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/nontemporal/NontemporalDeltaTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/nontemporal/NontemporalSnapshotTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/incremental-delta-milestoning/expected/with_delete_indicator/expected_pass1.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/incremental-delta-milestoning/expected/with_delete_indicator/expected_pass2.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/incremental-delta-milestoning/input/with_delete_indicator/data_pass1.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/incremental-delta-milestoning/input/with_delete_indicator/data_pass2.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/NontemporalDeltaTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/NontemporalDeltaMergeTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/BaseTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/scenarios/NonTemporalDeltaScenarios.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/scenarios/TestScenario.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/testcases/ingestmode/nontemporal/NontemporalDeltaTestCases.java
Labels: cla-present

#1119 Fix Haskell grammar pom
  legend-engine-xt-haskell-grammar/pom.xml
Labels: cla-present

#1117 update Pure IDE port to 9200 to avoid port conflicts
  README.md
  legend-engine-pure-ide-light/src/main/resources/ideLightConfig.json
Labels: cla-present

#1120 Fix GraphQL ExternalFormat configuration
  legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/external/shared/format/model/api/GenerateModelInput.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/format/GraphQLFormatExtension.java
Labels: bug, cla-present

#1121 Fix sql generation for AllVersions query
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/milestoning.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/tests/testBusinessDateMilestoning.pure
Labels: bug, cla-present

#1103 refactor all sqlQueryToString code in a common location
  legend-engine-xt-relationalStore-bigquery-pure/src/main/resources/core_relational_bigquery/relational/tests/dbSpecificTests/bigQueryTestSuiteInvoker.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/helperFunctions/databaseHelperFunctions.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/helperFunctions/helperFunctions.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/helperFunctions/toDDL.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/DDL/testDDL.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/DDL/toDDL.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/composite/compositeExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/databricks/customDatabricksTests.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/databricks/databricksExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/databricks/databricksTestSuiteInvoker.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/db2/db2Extension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/h2/h2Extension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/h2/h2TestSuiteInvoker.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/hive/hiveExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/customMemSQLTests.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/memSqlExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/postgres/postgresExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/postgres/postgresTestSuiteInvoker.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/presto/prestoExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/redshift/customRedshiftTests.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/redshift/redshiftExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/redshift/redshiftTestSuiteInvoker.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/snowflake/snowflakeExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/snowflake/snowflakeTestSuiteInvoker.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/sybaseASE/sybaseASEExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/sybaseIQ/sybaseIQExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbTestRunner/dynaFunctionTestRunner.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbTestRunner/executionPlanTestRunner.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/extensionDefaults.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/dynaFunctions/boolean.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/dynaFunctions/date.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/dynaFunctions/misc.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/dynaFunctions/numeric.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/dynaFunctions/string.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/naming/naming.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/selectSubClauses/filters.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/selectSubClauses/groupBy.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/selectSubClauses/join.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/selectSubClauses/mixtureOfClauses.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/selectSubClauses/orderBy.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/selectSubClauses/range.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/selectSubClauses/setup.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/selectSubClauses/union.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/selectSubClauses/view.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/selectSubClauses/windowColumn.pure
  legend-engine-xt-relationalStore-spanner-pure/src/main/resources/core_relational_spanner/relational/tests/dbSpecificTests/spannerTestSuiteInvoker.pure
  legend-engine-xt-relationalStore-sqlserver-pure/src/main/resources/core_relational_sqlserver/relational/tests/dbSpecificTests/sqlServerTestSuiteInvoker.pure
Labels: cla-present

#1125 Adding build action with the large runner
  .github/workflows/build-large-runner.yml
Labels: enhancement, cla-present

#1133 Configure Xmx - 3g to main proc, 2g to forked
  .github/workflows/build.yml
  .github/workflows/release.yml
  pom.xml
Labels: cla-present

#1123 Support for deriving mainDataset, stagingDataset is added in testRunner
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/logicalplan/datasets/DataType.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/NontemporalDeltaPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/util/LogicalPlanUtils.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/main/java/org/finos/legend/engine/persistence/components/relational/ansi/sql/visitors/ArrayVisitor.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/nontemporal/NontemporalDeltaTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-core/src/main/java/org/finos/legend/engine/persistence/components/relational/sqldom/schemaops/expresssions/select/ArrayExpression.java
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/toPureGraph/HelperPersistenceBuilder.java
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/grammar/to/HelperPersistenceComposer.java
  legend-engine-xt-persistence-test-runner/src/main/java/org/finos/legend/engine/testable/persistence/extension/PersistenceTestRunner.java
  legend-engine-xt-persistence-test-runner/src/main/java/org/finos/legend/engine/testable/persistence/mapper/AppendOnlyMapper.java
  legend-engine-xt-persistence-test-runner/src/main/java/org/finos/legend/engine/testable/persistence/mapper/BitemporalDeltaMapper.java
  legend-engine-xt-persistence-test-runner/src/main/java/org/finos/legend/engine/testable/persistence/mapper/BitemporalSnapshotMapper.java
  legend-engine-xt-persistence-test-runner/src/main/java/org/finos/legend/engine/testable/persistence/mapper/DatasetMapper.java
  legend-engine-xt-persistence-test-runner/src/main/java/org/finos/legend/engine/testable/persistence/mapper/DeriveDatasets.java
  legend-engine-xt-persistence-test-runner/src/main/java/org/finos/legend/engine/testable/persistence/mapper/IngestModeMapper.java
  legend-engine-xt-persistence-test-runner/src/main/java/org/finos/legend/engine/testable/persistence/mapper/MappingVisitors.java
  legend-engine-xt-persistence-test-runner/src/main/java/org/finos/legend/engine/testable/persistence/mapper/NontemporalDeltaMapper.java
  legend-engine-xt-persistence-test-runner/src/main/java/org/finos/legend/engine/testable/persistence/mapper/UnitemporalDeltaMapper.java
  legend-engine-xt-persistence-test-runner/src/main/java/org/finos/legend/engine/testable/persistence/mapper/UnitemporalSnapshotMapper.java
  legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/mapper/IngestModeMapperTest.java
  legend-engine-xt-persistence-test-runner/src/test/resources/append-only/allow_duplicates/persistence_date_time_auditing.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/append-only/allow_duplicates/persistence_no_audit_error.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/append-only/allow_duplicates/persistence_no_audit_fail.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/append-only/allow_duplicates/persistence_no_audit_success.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/append-only/filter_duplicates/persistence_date_time_auditing.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/append-only/filter_duplicates/persistence_no_audit.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/bitemporal-delta/batch_id_and_date_time_based/persistence_no_del_ind_user_specifies_from.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/bitemporal-delta/batch_id_and_date_time_based/persistence_no_del_ind_user_specifies_from_and_thru.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/bitemporal-delta/batch_id_based/persistence_no_del_ind_user_specifies_from_and_thru.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/bitemporal-delta/batch_id_based/persistence_with_del_ind_user_specifies_from.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/bitemporal-delta/date_time_based/persistence_no_del_ind_user_specifies_from.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/bitemporal-delta/date_time_based/persistence_no_del_ind_user_specifies_from_and_thru.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/non-temporal-delta/persistence_audit.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/non-temporal-delta/persistence_date_time_audit.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/non-temporal-delta/persistence_date_time_audit_delete_indicator.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/non-temporal-delta/persistence_no_audit.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/non-temporal-snapshot/persistence_date_time_audit.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/non-temporal-snapshot/persistence_no_audit.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/unitemporal-delta/batch_id_and_date_time_based/persistence_no_delete_indicator.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/unitemporal-delta/batch_id_based/persistence_no_delete_indicator.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/unitemporal-delta/date_time_based/persistence_with_delete_indicator.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/unitemporal-snapshot/batch_id_and_date_time_based/persistence.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/unitemporal-snapshot/batch_id_based/persistence.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/unitemporal-snapshot/date_time_based/persistence.txt
Labels: cla-present

#1148 Setting arguments for release:perform
  .github/workflows/release-large-runner.yml
Labels: bug, cla-present

#1145 Add parser and compiler tests for qualifiers in graph fetch tree
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
  legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java
Labels: cla-present

#1147 Make workflow logs readable
  legend-engine-pure-code-compiled-core/src/test/java/org/finos/legend/engine/pure/code/core/Test_Pure_Core.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/DbSpecificTests.java
  legend-engine-xt-relationalStore-pure/src/test/java/org/finos/legend/pure/code/core/relational/Test_Pure_Relational.java
  pom.xml
Labels: cla-present

#1149 Fix a bug with diagram property view referencing association
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/CompileContext.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperModelBuilder.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
  legend-engine-xt-diagram-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperDiagramBuilder.java
  legend-engine-xt-diagram-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestDiagramGrammarRoundtrip.java
Labels: bug, cla-present

#1150 Add Xml Test to showcase parsing of default value
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/simpleObjectXml.pure
Labels: cla-present

#1152 Support for services with only query lambda
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ValueSpecificationBuilderForFuncExpr.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/builder/MultiHandlerFunctionExpressionBuilder.java
  legend-engine-language-pure-dsl-service-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/service/generation/ServicePlanGenerator.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/HelperServiceBuilder.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/from/ServiceParseTreeWalker.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/HelperServiceGrammarComposer.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceCompilationFromGrammar.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarParser.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarRoundtrip.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/legend/service/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/legend/service/serviceValidationHelper.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/runtime/runtimeExtension.pure
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestRunner.java
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/TestRuntimeBuilder.java
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/TestValueSpecificationBuilder.java
  legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java
  legend-engine-test-runner-service/src/test/resources/testable/relational/legend-testable-relational-service-inline-simple-fail.pure
  legend-engine-xt-persistence-pure/src/main/resources/core_persistence/persistence/validations_rules.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanExecutionTest.pure
Labels: cla-present

#1155 New protocol v1_28_0
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/PureClientVersions.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_28_0/extension/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_28_0/models/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_28_0/models/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_28_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_28_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/extension/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/invocations/execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/invocations/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/invocations/testLoadModels.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/models/diagram.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/models/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/models/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/models/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/models/results.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/scan/buildBasePureModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/scan/buildPureModelAsText.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/scan/testBuildPureModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/transfers/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/transfers/mapping.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/transfers/store.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/transfers/valueSpecification.pure
  legend-engine-xt-avro-pure/src/main/resources/core_external_format_avro/protocol/protocol_v1_28_0.pure
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/protocol/protocol_v1_28_0.pure
  legend-engine-xt-relationalStore-bigquery-pure/src/main/resources/core_relational_bigquery/relational/protocols/pure/v1_27_0/extension/extension_bigQuery.pure
  legend-engine-xt-relationalStore-bigquery-pure/src/main/resources/core_relational_bigquery/relational/protocols/pure/v1_27_0/models/metamodel_bigQuery.pure
  legend-engine-xt-relationalStore-bigquery-pure/src/main/resources/core_relational_bigquery/relational/protocols/pure/v1_28_0/extension/extension_bigQuery.pure
  legend-engine-xt-relationalStore-bigquery-pure/src/main/resources/core_relational_bigquery/relational/protocols/pure/v1_28_0/models/metamodel_bigQuery.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_28_0/extension/extension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_28_0/extension/extension_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_28_0/invocations/execution_relation_executeInRelationalDb.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_28_0/invocations/execution_relational_execute.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_28_0/invocations/execution_relational_testConnection.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_28_0/invocations/execution_relational_testData.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_28_0/models/executionPlan_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_28_0/models/metamodel_connection.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_28_0/models/metamodel_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_28_0/models/results_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_28_0/models/testData_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_28_0/transfers/connection_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_28_0/transfers/metamodel_relational.pure
  legend-engine-xt-relationalStore-spanner-pure/src/main/resources/core_relational_spanner/relational/protocols/pure/v1_28_0/extension/extension_Spanner.pure
  legend-engine-xt-relationalStore-spanner-pure/src/main/resources/core_relational_spanner/relational/protocols/pure/v1_28_0/models/metamodel_Spanner.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_28_0/extension/extension.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_28_0/extension/extension_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_28_0/models/executionPlan_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_28_0/models/metamodel_connection.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_28_0/models/metamodel_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_28_0/transfers/connection_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_28_0/transfers/metamodel_serviceStore.pure
Labels: cla-present

#1102 Refactor IDs to use identifiers 2 (Revert 1091)
  legend-engine-xt-mastery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/MasteryLexerGrammar.g4
  legend-engine-xt-mastery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/MasteryParserGrammar.g4
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/MasteryParseTreeWalker.java
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/to/HelperMasteryGrammarComposer.java
  legend-engine-xt-mastery-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/test/TestMasteryCompilationFromGrammar.java
Labels: cla-present

#1157 Adding a manual action to close an OSSRH staging repo
  .github/workflows/ossrh-close-staging-repo.yml
Labels: enhancement, cla-present

#1137 Ability to consume java Json representation of results
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/helpers/ExecutionNodeSerializerHelper.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/json/JsonStreamingResult.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/serialization/ExecutionResultObjectMapperFactory.java
  legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/result/test/json/TestJsonStreamingResult.java
  legend-engine-protocol-pure/pom.xml
  legend-engine-protocol-pure/src/test/java/org/finos/legend/engine/protocol/test/TestCompatibilityAndMigration.java
  legend-engine-testable/src/test/java/org/finos/legend/engine/testable/assertion/TestTestAssertionEvaluator.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/RelationalResult.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/execution/TestExecutionPlan.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/graphFetch/dataTypes/TestRelationalGraphFetchExecutionDataTypes.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/javaRuntime/executionPlanNodes/graphFetch/graphFetchRelational.pure
Labels: cla-present

#1136 Optional & Collection Enum Parameter
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/validation/ParameterValidationContextExecutor.java
  legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
  legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/enumServiceParameter.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure
  legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestQueryExecutionWithParameters.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbExtension.pure
Labels: cla-present

#1166 Close and release staging repo action
  .github/workflows/ossrh-close-staging-repo.yml
Labels: enhancement, cla-present

#1156 Add Service Store docs
  docs/store/ServiceStore/resources/service-store-mapping-diagram.PNG
  docs/store/ServiceStore/resources/service-store-metamodel-diagram.PNG
  docs/store/ServiceStore/resources/service-store-test-data-diagram.PNG
  docs/store/ServiceStore/service-store-examples-templates.md
  docs/store/ServiceStore/service-store-tutorial.md
  docs/store/ServiceStore/service-store.md
Labels: cla-present

#1168 Remove deprecated graph fetch plan models
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetchExecutionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_18_0/transfers/executionPlan.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/relationalGraphFetch.pure
Labels: cla-present

#1167 Fixing quotes for maven release command
  .github/workflows/build-large-runner.yml
  .github/workflows/build.yml
  .github/workflows/release-large-runner.yml
  .github/workflows/release.yml
  pom.xml
Labels: cla-present

#1174 Move relational docs and fix service store docs
  docs/spanner/spanner-connector.md
  docs/store/Relational/Databases/bigquery/bigquery-connector.md
  docs/store/Relational/Databases/bigquery/bigquery-example-model.md
  docs/store/Relational/Databases/databricks/README.md
  docs/store/Relational/Databases/databricks/databricks.pure
  docs/store/Relational/Databases/databricks/images/db-cluster-jdbc.png
  docs/store/Relational/Databases/databricks/images/db-cluster.png
  docs/store/Relational/Databases/databricks/images/db-lakehouse-logo.png
  docs/store/Relational/Databases/databricks/images/db-token-create.png
  docs/store/Relational/Databases/databricks/images/lg-store-create.png
  docs/store/Relational/Databases/databricks/images/lg-store-query.png
  docs/store/Relational/Databases/spanner/spanner-connector.md
  docs/store/Relational/Databases/spanner/spanner-example-model.md
  docs/store/Relational/database-connection-management/ConnectionManagement.md
  docs/store/Relational/database-integration-tests/README.md
  docs/store/ServiceStore/service-store-tutorial.md
  docs/store/ServiceStore/service-store.md
Labels: cla-present

#1158 Fix repository loading in PureIDELight
  legend-engine-pure-ide-light/src/main/java/org/finos/legend/engine/ide/PureIDELight.java
Labels: bug, cla-present

#1171 Creating Keys for MultiExec Test Blocks 11-17-22
  legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceLexerGrammar.g4
  legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceParserGrammar.g4
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/ServiceCompilerExtensionImpl.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/from/ServiceParseTreeWalker.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/HelperServiceGrammarComposer.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/ServiceTest.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarParser.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarRoundtrip.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/legend/service/metamodel.pure
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestRunner.java
  legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java
  legend-engine-test-runner-service/src/test/resources/testable/service/serviceGrammarForFailedTestModel.pure
  legend-engine-test-runner-service/src/test/resources/testable/service/serviceGrammarModel.pure
  legend-engine-test-runner-service/src/test/resources/testable/service/serviceGrammarWithFailedServiceTestKeys.pure
  legend-engine-test-runner-service/src/test/resources/testable/service/serviceGrammarWithServiceTestKeys2.pure
  legend-engine-test-runner-service/src/test/resources/testable/service/serviceGrammarWithTestKeys1.pure
Labels: cla-present

#1182 Update large runner release flags
  .github/workflows/build.yml
  .github/workflows/release-large-runner.yml
  .github/workflows/release.yml
Labels: bug, cla-present

#1180 Persistence: Bitemporal Milestoning Prefixing Table/Column Aliases
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/BitemporalDeltaPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/bitemporal/BitemporalDeltaWithBatchIdTest.java
Labels: cla-present

#1142 Persistence: Test Code Restructuring for Unitemporal Delta
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/AppendOnlyPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/BitemporalDeltaPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/AnsiTestArtifacts.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/nontemporal/AppendOnlyTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/unitemporal/UnitemporalDeltaBatchIdBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/unitemporal/UnitemporalDeltaBatchIdDateTimeBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/unitemporal/UnitemporalDeltaDateTimeBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/unitemporal/UnitemporalDeltaTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/unitemporal/UnitemporalDeltaWithBatchIdTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/unitemporal/UnitemporalDeltaWithBatchTimeTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/AppendOnlyTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/MemsqlTestArtifacts.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalDeltaBatchIdBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalDeltaBatchIdDateTimeBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalDeltaDateTimeBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalDeltaTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalDeltaWithBatchIdTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalDeltaWithBatchTimeTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/SnowflakeTestArtifacts.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalDeltaBatchIdBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalDeltaBatchIdDateTimeBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalDeltaDateTimeBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalDeltaTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/BaseTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/scenarios/AppendOnlyScenarios.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/scenarios/UnitemporalDeltaBatchIdBasedScenarios.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/scenarios/UnitemporalDeltaBatchIdDateTimeBasedScenarios.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/scenarios/UnitemporalDeltaDateTimeBasedScenarios.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/testcases/ingestmode/nontemporal/AppendOnlyTestCases.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/testcases/ingestmode/unitemporal/UnitmemporalDeltaBatchIdBasedTestCases.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/testcases/ingestmode/unitemporal/UnitmemporalDeltaBatchIdDateTimeBasedTestCases.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/testcases/ingestmode/unitemporal/UnitmemporalDeltaDateTimeBasedTestCases.java
Labels: cla-present

#1184 Fixing StackOverFlow Issue For Alloy M2M Recursive Functions
  legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
  legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/simpleM2MService.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/dataQuality.pure
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/conventions.pure
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/expressionGeneration.pure
Labels: cla-present

#1162 [Router Clean Up] Delete Platform Store
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/test/executionPlan_execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/extensions/functions.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetch_routing.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/platform/executionPlan/executionPlan_generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/metamodel/clustering.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/metamodel/platformStore.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/storeContract.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/platform/executionPlanNodes/platform/objectReference.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/platform/executionPlanNodes/platform/platform.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/platform/executionPlanNodes/platform/serialize.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/platform/executionPlanNodes/platformMerge/platformMerge.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/platform/executionPlanNodes/platformUnion/platformUnion.pure
Labels: cla-present

#1165 Introduce service validation
  docs/service-post-validations/service-post-validations.md
  legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceLexerGrammar.g4
  legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceParserGrammar.g4
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/ServiceCompilerExtensionImpl.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/from/ServiceParseTreeWalker.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/HelperServiceGrammarComposer.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/ServiceGrammarComposerExtension.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/PostValidation.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/PostValidationAssertion.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/Service.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceCompilationFromGrammar.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarParser.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/legend/service/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/legend/service/validation.pure
  legend-engine-service-post-validation-runner/pom.xml
  legend-engine-service-post-validation-runner/src/main/java/org/finos/legend/engine/service/post/validation/runner/LegendServicePostValidationRunner.java
  legend-engine-service-post-validation-runner/src/main/java/org/finos/legend/engine/service/post/validation/runner/PostValidationAssertionResult.java
  legend-engine-service-post-validation-runner/src/main/java/org/finos/legend/engine/service/post/validation/runner/PostValidationAssertionStreamingOutput.java
  legend-engine-service-post-validation-runner/src/main/java/org/finos/legend/engine/service/post/validation/runner/ServicePostValidationRunner.java
  legend-engine-service-post-validation-runner/src/test/java/org/finos/legend/engine/service/post/validation/runner/TestLegendServicePostValidationRunner.java
  legend-engine-service-post-validation-runner/src/test/resources/legend-test-object-services-with-validation.json
  legend-engine-service-post-validation-runner/src/test/resources/legend-test-services-with-validation-and-parameters.json
  legend-engine-service-post-validation-runner/src/test/resources/legend-test-services-with-validation-multi-execution.json
  legend-engine-service-post-validation-runner/src/test/resources/legend-test-tds-services-with-validation.json
  legend-engine-services-model-api/pom.xml
  legend-engine-services-model-api/src/main/java/org/finos/legend/engine/plan/execution/service/api/ServiceModelingApi.java
  legend-engine-services-model/pom.xml
  legend-engine-services-model/src/main/java/org/finos/legend/engine/plan/execution/service/ServiceModeling.java
  pom.xml
Labels: cla-present

#1189 Add ability to instantiate GraphQL APIs with extensions
  legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
  legend-engine-xt-graphQL-query/pom.xml
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/debug/GraphQLDebug.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecute.java
  legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLAPI.java
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Project1_Workspace1.pure
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Project2_Workspace1.pure
Labels: bug, enhancement, cla-present

#1190 Adding documentation for external formats
  docs/bindings/bindings.md
  docs/externalFormat/README.md
  docs/externalFormat/bindings/README.md
  docs/externalFormat/bindings/resources/bindingMetamodel.png
  docs/externalFormat/bindings/resources/bindings.png
  docs/externalFormat/extensions/FlatData/README.md
  docs/externalFormat/extensions/JSONSchema/README.md
  docs/externalFormat/extensions/XSD/README.md
  docs/externalFormat/resources/schemaSetMetamodel.png
  docs/externalFormat/steps-to-add-new-external-format.md
  docs/store/extensions/Relational/Databases/bigquery/bigquery-connector.md
  docs/store/extensions/Relational/Databases/bigquery/bigquery-example-model.md
  docs/store/extensions/Relational/Databases/databricks/README.md
  docs/store/extensions/Relational/Databases/databricks/databricks.pure
  docs/store/extensions/Relational/Databases/databricks/images/db-cluster-jdbc.png
  docs/store/extensions/Relational/Databases/databricks/images/db-cluster.png
  docs/store/extensions/Relational/Databases/databricks/images/db-lakehouse-logo.png
  docs/store/extensions/Relational/Databases/databricks/images/db-token-create.png
  docs/store/extensions/Relational/Databases/databricks/images/lg-store-create.png
  docs/store/extensions/Relational/Databases/databricks/images/lg-store-query.png
  docs/store/extensions/Relational/Databases/spanner/spanner-connector.md
  docs/store/extensions/Relational/Databases/spanner/spanner-example-model.md
  docs/store/extensions/Relational/database-connection-management/ConnectionManagement.md
  docs/store/extensions/Relational/database-integration-tests/README.md
  docs/store/extensions/ServiceStore/README.md
  docs/store/extensions/ServiceStore/resources/service-store-mapping-diagram.PNG
  docs/store/extensions/ServiceStore/resources/service-store-metamodel-diagram.PNG
  docs/store/extensions/ServiceStore/resources/service-store-test-data-diagram.PNG
  docs/store/extensions/ServiceStore/resources/service-store.PNG
  docs/store/extensions/ServiceStore/service-store-examples-templates.md
  docs/store/extensions/ServiceStore/service-store-tutorial.md
Labels: cla-present

#1194 print test summary post db integration test workflow run
  .github/workflows/database-bigquery-sql-generation-integration-test.yml
  .github/workflows/database-databricks-sql-generation-integration-test.yml
  .github/workflows/database-mssqlserver-sql-generation-integration-test.yml
  .github/workflows/database-postgresql-sql-generation-integration-test.yml
  .github/workflows/database-redshift-sql-generation-integration-test.yml
  .github/workflows/database-snowflake-sql-generation-integration-test.yml
  .github/workflows/database-spanner-sql-generation-integration-test.yml
  legend-engine-xt-relationalStore-bigquery-pure/src/main/resources/core_relational_bigquery.definition.json
  legend-engine-xt-relationalStore-bigquery-pure/src/main/resources/core_relational_bigquery/relational/sqlQueryToString/customBigQueryTests.pure
  legend-engine-xt-relationalStore-bigquery-pure/src/test/java/org/finos/legend/pure/code/core/Test_Pure_Relational_Custom_BigQuery.java
  legend-engine-xt-relationalStore-sqlserver-pure/src/main/resources/core_relational_sqlserver.definition.json
  legend-engine-xt-relationalStore-sqlserver-pure/src/main/resources/core_relational_sqlserver/relational/sqlQueryToString/customSqlServerTests.pure
  legend-engine-xt-relationalStore-sqlserver-pure/src/test/java/org/finos/legend/pure/code/core/Test_Pure_Relational_Custom_SqlServer.java
  legend-engine-xt-relationalStore-test-server/src/main/java/org/finos/legend/engine/server/test/shared/Relational_DbSpecific_UsingPureClientTestSuite.java
Labels: cla-present

#1118 make GraphQL API endpoints support fetching models from depot/metadata server
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/GraphQL.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/debug/GraphQLDebug.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecute.java
Labels: cla-present

#1178 add warnings to relational compiler
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/Warning.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/extension/CompilerExtension.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/extension/CompilerExtensions.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/validator/MappingValidator.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/validator/MappingValidatorContext.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestCompilationFromGrammar.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/IRelationalCompilerExtension.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/RelationalCompilerExtension.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/validation/RelationalValidator.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
Labels: cla-present

#1198 Upgrade to Legend Pure 3.8.0 (M3 Function taxonomy clean up)
  legend-engine-external-shared/src/main/java/org/finos/legend/engine/external/shared/format/imports/PureModelContextDataGenerator.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRoundTripWithPureTransformation.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/external/format/json/fromJSONSchema.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/external/format/json/jsonSchema.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/external/format/json/tests/testFromJSONSchema.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/metaExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/milestoningExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/testExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/test/testIsTestElement.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/lineage/scanExecute.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/metamodel_diagram.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_18_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_18_0/transfers/valueSpecification.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_19_0/scan/buildPureModelAsText.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_19_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_19_0/transfers/valueSpecification.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_20_0/scan/buildPureModelAsText.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_20_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_20_0/transfers/valueSpecification.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/scan/buildPureModelAsText.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/transfers/valueSpecification.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_22_0/scan/buildPureModelAsText.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_22_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_22_0/transfers/valueSpecification.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_23_0/scan/buildPureModelAsText.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_23_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_23_0/transfers/valueSpecification.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/scan/buildPureModelAsText.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/transfers/valueSpecification.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/scan/buildPureModelAsText.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/transfers/valueSpecification.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/scan/buildPureModelAsText.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/transfers/valueSpecification.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/scan/buildPureModelAsText.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/transfers/valueSpecification.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/scan/buildPureModelAsText.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/transfers/valueSpecification.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/scan/buildPureModelAsText.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/valueSpecification.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/printer/printer.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/test/testCollection.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/tools/testProfiles.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/aggregationAware/aggregationAware.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/aggregationAware/storeContract.pure
  legend-engine-pure-ide-light/src/main/resources/pure_ide/concepts.pure
  legend-engine-pure-ide-light/src/main/resources/pure_ide/findUsage.pure
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/expressionGeneration.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/testUtils.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbTestRunner/executionPlanTestRunner.pure
  pom.xml
Labels: cla-present

#1143 Throw warnings for incompatible types in relational property mappings
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/testRelationalExtension.pure
Labels: cla-present

#1201 Revert "Throw warnings for incompatible types in relational property mappings (#1143)"
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/testRelationalExtension.pure
Labels: cla-present

#1196 Fix parsing of enum mapping with special characters
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/EnumerationMappingParseTreeWalker.java
  legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestMappingGrammarRoundtrip.java
Labels: cla-present

#1185 support latestdate in graphfetchtree
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/compilation/GeneratePureConfig.java
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/date/AbstractPureDate.java
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/date/LatestDate.java
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/date/PureDate.java
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/store/platform/ISerializationWriter.java
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/util/Library.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/helpers/ExecutionNodeSerializerHelper.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/helpers/platform/DefaultExecutionNodeContext.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/GraphFetchTreeParseTreeWalker.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/date/testDateElementFunctions.pure
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/conventions.pure
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/metamodel_factories.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/enginePlatformDependencies.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/pureDateLibrary.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/pureDateLibraryTests.pure
  legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/graphFetchRelational.pure
  legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/executionPlanTest.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/testGraphFetchMilestoning.pure
Labels: cla-present

#1200 Revert "Fix sql generation for AllVersions query (#1121)"
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/milestoning.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/tests/testBusinessDateMilestoning.pure
Labels: cla-present

#1204 Rename external format Java platform binding packages
  legend-engine-pure-code-compiled-core-configuration/src/main/resources/core_configuration/coreExtensions.pure
  legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding.definition.json
  legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/descriptor.pure
  legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/engineDependencies.pure
  legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/executionPlanTest.pure
  legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/externalize.pure
  legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/internalize.pure
  legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/shared.pure
  legend-engine-xt-flatdata-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/Test_Pure_FlatDataJavaPlatformBinding.java
  legend-engine-xt-flatdata-runtime/src/main/java/org/finos/legend/engine/external/format/flatdata/FlatDataJavaCompilerExtension.java
  legend-engine-xt-flatdata-runtime/src/test/java/org/finos/legend/engine/external/format/flatdata/read/test/TestFlatDataQueries.java
  legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding.definition.json
  legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/descriptor.pure
  legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/engineDependencies.pure
  legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/executionPlanTest.pure
  legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/externalize.pure
  legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/internalize.pure
  legend-engine-xt-json-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/Test_Pure_JsonJavaPlatformBinding.java
  legend-engine-xt-json-runtime/src/main/java/org/finos/legend/engine/external/format/json/JsonJavaCompilerExtension.java
  legend-engine-xt-json-runtime/src/test/java/org/finos/legend/engine/external/format/json/read/test/TestJsonSchemaQueries.java
  legend-engine-xt-json-runtime/src/test/java/org/finos/legend/engine/external/format/json/read/test/TestJsonSchemaQueriesDeprecated.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/AbstractTestSemiStructured.java
  legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/utils/ServiceStoreTestUtils.java
  legend-engine-xt-xml-javaPlatformBinding-pure/src/main/resources/core_external_format_xml_java_platform_binding.definition.json
  legend-engine-xt-xml-javaPlatformBinding-pure/src/main/resources/core_external_format_xml_java_platform_binding/legendJavaPlatformBinding/descriptor.pure
  legend-engine-xt-xml-javaPlatformBinding-pure/src/main/resources/core_external_format_xml_java_platform_binding/legendJavaPlatformBinding/engineDependencies.pure
  legend-engine-xt-xml-javaPlatformBinding-pure/src/main/resources/core_external_format_xml_java_platform_binding/legendJavaPlatformBinding/internalize.pure
  legend-engine-xt-xml-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/Test_Pure_XmlJavaPlatformBinding.java
  legend-engine-xt-xml-runtime/src/main/java/org/finos/legend/engine/external/format/xml/XmlJavaCompilerExtension.java
  legend-engine-xt-xml-runtime/src/test/java/org/finos/legend/engine/external/format/xml/test/TestXmlQueries.java
Labels: enhancement, cla-present

#1163 Implementing statistics collection for Bitemporal Delta milestoning
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/AppendOnlyPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/BitemporalDeltaPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/NontemporalDeltaPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/Planner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/UnitemporalDeltaPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/UnitemporalPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-physical-plan/src/main/java/org/finos/legend/engine/persistence/components/schemaevolution/SchemaEvolution.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/bitemporal/BitemporalDeltaWithBatchIdTest.java
Labels: cla-present

#1175 Bitemp vanila case source from/thru columns refactor
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/BitemporalDeltaPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/BitemporalPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/util/LogicalPlanUtils.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/IngestModeTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/bitemporal/BitemporalDeltaWithBatchIdTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/java/org/finos/legend/engine/persistence/components/TestUtils.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/bitemporal/BitemporalDeltaWithBatchIdTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from_and_through/less_columns_in_staging/expected_pass1.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from_and_through/less_columns_in_staging/expected_pass2.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from_and_through/less_columns_in_staging/expected_pass3.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from_and_through/with_delete_ind/expected_pass1.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from_and_through/with_delete_ind/expected_pass2.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from_and_through/with_delete_ind/expected_pass3.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from_and_through/without_delete_ind/expected_pass1.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from_and_through/without_delete_ind/expected_pass2.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from_and_through/without_delete_ind/expected_pass3.csv
  legend-engine-xt-persistence-test-runner/src/main/java/org/finos/legend/engine/testable/persistence/mapper/MappingVisitors.java
  legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/delta/bitemporal/TestPersistenceBitemporalDelta.java
  legend-engine-xt-persistence-test-runner/src/test/resources/bitemporal-delta/batch_id_and_date_time_based/persistence_no_del_ind_user_specifies_from_and_thru.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/bitemporal-delta/batch_id_based/persistence_no_del_ind_user_specifies_from_and_thru.txt
  legend-engine-xt-persistence-test-runner/src/test/resources/bitemporal-delta/date_time_based/persistence_no_del_ind_user_specifies_from_and_thru.txt
Labels: cla-present

#1195 fix spanner credentials
  .github/workflows/database-spanner-integration-test.yml
  .github/workflows/database-spanner-sql-generation-integration-test.yml
Labels: cla-present

#1203 Specify metadata for LegendCompileVS
  legend-engine-pure-runtime-compiler/src/main/java/org/finos/legend/engine/pure/runtime/compiler/compiled/natives/LegendCompileVS.java
  legend-engine-xt-graphQL-grammar-integration/src/test/java/org/finos/legend/engine/language/graphQL/grammar/integration/test/TestGraphQLEmbedded.java
Labels: cla-present

#1199 add MauricioUyaguari as codeOwner
  CODEOWNERS
Labels: cla-present
