Repository finos/legend-engine, pull requests merged in 2022-01, with the labels that each got.

#478 Pool Housekeeping bug fix and enhacements
  legend-engine-executionPlan-execution-store-relational-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/TestConnectionState.java
  legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/AuthenticationStatistics.java
  legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/AuthenticationStrategy.java
  legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/DriverWrapper.java
  legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/DataSourceSpecification.java
  legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/DataSourceStatistics.java
  legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/DataSourceWithStatistics.java
  legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/state/ConnectionStateManager.java
  legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/state/ConnectionStateManagerPOJO.java
  legend-engine-executionPlan-execution-store-relational-connection/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/state/InstrumentedConnectionStateManager.java
  legend-engine-executionPlan-execution-store-relational-connection/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/state/TestConnectionStateManager.java
  legend-engine-executionPlan-execution-store-relational-connection/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/state/TestConnectionStateManagerRace.java
  legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/api/RelationalExecutorInformation.java
  legend-engine-executionPlan-execution-store-relational/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/TestRelationalExecutionStatistics.java
Labels: cla-present

#482 Cache common imports instead of resolving them each time
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/CompileContext.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/TestCompilerContext.java
Labels: cla-present

#483 Metrics Handler Refactor first phase
  legend-engine-executionPlan-execution-store-relational-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/DataSourceSpecification.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/serialization/TemporaryFile.java
  legend-engine-language-pure-compiler-api/src/main/java/org/finos/legend/engine/language/pure/compiler/api/Compile.java
  legend-engine-language-pure-compiler-api/src/test/java/org/finos/legend/engine/language/pure/compiler/api/test/TestCompileApi.java
  legend-engine-query-pure/src/main/java/org/finos/legend/engine/query/pure/api/Execute.java
  legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestM2MGrammarCompileAndExecute.java
  legend-engine-services-model-api/src/main/java/org/finos/legend/engine/plan/execution/service/api/ServiceModelingApi.java
  legend-engine-services-model/src/main/java/org/finos/legend/engine/plan/execution/service/ServiceModeling.java
  legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/prometheus/MetricsHandler.java
  legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/EngineJavaCompiler.java
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ServiceTestRunner.java
Labels: cla-present

#484 Enable sqlServer connection test with docker
  legend-engine-executionPlan-execution-store-relational-connection-tests/pom.xml
  legend-engine-executionPlan-execution-store-relational-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/TestConnectionAcquisitionWithFlowProvider_Server.java
  legend-engine-executionPlan-execution-store-relational-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/TestSqlServerConnectionAcquisitionWithFlowProvider.java
Labels: cla-present

#486 Removed hard coded Windows temp path
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/serialization/TemporaryFile.java
  legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/result/test/serialization/TestTemporaryFile.java
Labels: cla-present

#488 Fix generate plan api to include params while compilation
  legend-engine-query-pure/src/main/java/org/finos/legend/engine/query/pure/api/Execute.java
Labels: cla-present

#489 Allow build on Mac OSX
  legend-engine-executionPlan-execution-store-relational/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/AlloyTestServer.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/serialization/TemporaryFile.java
  legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/result/test/serialization/TestTemporaryFile.java
Labels: bug, cla-present

#490 Fix extended handler resolution when qualified
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/CompileContext.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
Labels: cla-present

#492 Improve tracing of graph fetch execution
  legend-engine-executionPlan-execution-store-inMemory/pom.xml
  legend-engine-executionPlan-execution-store-inMemory/src/main/java/org/finos/legend/engine/plan/execution/stores/inMemory/plugin/InMemoryExecutionNodeExecutor.java
  legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/RelationalExecutor.java
  legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/StreamResultToTempTableVisitor.java
  legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalExecutionNodeExecutor.java
  legend-engine-executionPlan-execution-store-relational/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/serialization/RealizedRelationalResultCSVSerializer.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/ExecutionNodeExecutor.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/graphFetch/GraphFetchResult.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/graphFetch/GraphObjectsBatch.java
Labels: cla-present

#493 Allow case insensitive column names in delimited flatdata
  legend-engine-external-format-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/shared/driver/core/DelimitedWithHeadingsDriverDescription.java
  legend-engine-external-format-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/shared/driver/core/DelimitedWithHeadingsReadDriver.java
  legend-engine-external-format-flatdata-shared/src/test/java/org/finos/legend/engine/external/format/flatdata/shared/driver/TestDelimitedCaseInsensitiveColumnNames.java
Labels: cla-present

#499 Use long for PureDate microsecond computations
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/date/PureDate.java
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/util/Library.java
Labels: cla-present

#496 Allow multiple prioritized date/datetime formats in flat data
  legend-engine-external-format-flatdata-model/src/main/java/org/finos/legend/engine/external/format/flatdata/FlatDataExternalFormatExtension.java
  legend-engine-external-format-flatdata-model/src/main/java/org/finos/legend/engine/external/format/flatdata/compile/FlatDataSchemaCompiler.java
  legend-engine-external-format-flatdata-shared/src/main/antlr4/org/finos/legend/engine/external/format/flatdata/shared/antlr4/FlatDataLexerGrammar.g4
  legend-engine-external-format-flatdata-shared/src/main/antlr4/org/finos/legend/engine/external/format/flatdata/shared/antlr4/FlatDataParserGrammar.g4
  legend-engine-external-format-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/shared/driver/core/DelimitedDriverHelper.java
  legend-engine-external-format-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/shared/driver/core/StreamingDriverHelper.java
  legend-engine-external-format-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/shared/driver/core/util/FlatDataUtils.java
  legend-engine-external-format-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/shared/driver/core/valueParser/DateParser.java
  legend-engine-external-format-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/shared/driver/core/valueParser/DateTimeParser.java
  legend-engine-external-format-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/shared/driver/core/variables/ProcessingVariables.java
  legend-engine-external-format-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/shared/driver/core/variables/StringListVariable.java
  legend-engine-external-format-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/shared/driver/spi/VariableType.java
  legend-engine-external-format-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/shared/grammar/FlatDataGrammarHelper.java
  legend-engine-external-format-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/shared/grammar/FlatDataSchemaParser.java
  legend-engine-external-format-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/shared/model/FlatDataProperty.java
  legend-engine-external-format-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/shared/model/FlatDataTemporal.java
  legend-engine-external-format-flatdata-shared/src/main/java/org/finos/legend/engine/external/format/flatdata/shared/validation/FlatDataValidation.java
  legend-engine-external-format-flatdata-shared/src/test/java/org/finos/legend/engine/external/format/flatdata/shared/TestValidation.java
  legend-engine-external-format-flatdata-shared/src/test/java/org/finos/legend/engine/external/format/flatdata/shared/driver/TestDelimitedDate.java
  legend-engine-external-format-flatdata-shared/src/test/java/org/finos/legend/engine/external/format/flatdata/shared/driver/TestDelimitedDateTime.java
  legend-engine-external-format-flatdata-shared/src/test/java/org/finos/legend/engine/external/format/flatdata/shared/driver/TestNullAndEmptyValues.java
Labels: enhancement, cla-present

#487 Add support for reading subsection of service response
  legend-engine-executionPlan-execution-external-store-service/src/test/java/org/finos/legend/engine/plan/execution/stores/service/fragment/TestServiceStoreFragment.java
  legend-engine-executionPlan-execution-external-store-service/src/test/resources/fragment/mapping.pure
  legend-engine-executionPlan-execution-external-store-service/src/test/resources/fragment/model.pure
  legend-engine-executionPlan-execution-external-store-service/src/test/resources/fragment/pathContent.json
  legend-engine-executionPlan-execution-external-store-service/src/test/resources/fragment/serviceStore.pure
  legend-engine-language-external-store-service/pom.xml
  legend-engine-language-external-store-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceStoreLexerGrammar.g4
  legend-engine-language-external-store-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceStoreParserGrammar.g4
  legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperServiceStoreClassMappingBuilder.java
  legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/grammar/from/ServiceStoreParseTreeWalker.java
  legend-engine-protocol-external-format-flatdata/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/external/format/flatdata/FlatDataDeserializeExecutionNode.java
  legend-engine-protocol-external-format-json/src/main/java/org/finos/legend/engine/external/format/json/JsonProtocolExtension.java
  legend-engine-protocol-external-format-json/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/external/format/json/JsonDeserializeExecutionNode.java
  legend-engine-protocol-external-format-json/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/external/format/json/JsonPathReference.java
  legend-engine-protocol-external-format-xml/pom.xml
  legend-engine-protocol-external-format-xml/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/external/format/xml/XmlDeserializeExecutionNode.java
  legend-engine-protocol-external-shared-format/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/external/shared/ExternalFormatDeserializeExecutionNode.java
  legend-engine-protocol-external-shared-format/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/external/shared/PathReference.java
  legend-engine-protocol-external-store-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/service/mapping/ServiceMapping.java
Labels: cla-present

#504 Upgrade Pure and add support for GraphQL query
  legend-engine-executionPlan-generation/src/main/java/org/finos/legend/engine/plan/generation/PlanGenerator.java
  legend-engine-language-graphQL-compiler/src/test/java/org/finos/legend/engine/protocol/graphQL/GenerateTestQueryBuilder.java
  legend-engine-query-graphQL/pom.xml
  legend-engine-query-graphQL/src/main/java/org/finos/legend/engine/query/graphQL/api/Execute.java
  legend-engine-query-graphQL/src/main/resources/exampleModel.json
  legend-engine-query-graphQL/src/main/resources/exampleRuntime.json
  legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
  pom.xml
Labels: cla-present

#515 Revert "Cache common imports instead of resolving them each time"
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/CompileContext.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/TestCompilerContext.java
Labels: cla-present

#520 Prevent jackson from closing the output stream when generating JSON
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/json/JsonSerializer.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/serialization/ExecutionResultObjectMapperFactory.java
  legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/result/test/serialization/TestExecutionResultObjectMapperFactory.java
  legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/ObjectMapperFactory.java
  legend-engine-shared-core/src/test/java/org/finos/legend/engine/shared/core/test/TestObjectMapperFactory.java
Labels: cla-present

#519 Add composer changes for service store mapping path offset feature
  legend-engine-language-external-store-service/pom.xml
  legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/grammar/from/ServiceStoreParseTreeWalker.java
  legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperServiceStoreGrammarComposer.java
  legend-engine-language-external-store-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceStoreCompilationUtils.java
  legend-engine-language-external-store-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceStoreMappingCompilationFromGrammar.java
  legend-engine-language-external-store-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceStoreMappingGrammarParser.java
  legend-engine-language-external-store-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceStoreMappingGrammarRoundtrip.java
Labels: cla-present

#509 Allow special characters in parameter names for service store
  legend-engine-executionPlan-execution-external-store-service/src/main/java/org/finos/legend/engine/plan/execution/stores/service/ServiceExecutor.java
  legend-engine-executionPlan-execution-external-store-service/src/test/java/org/finos/legend/engine/plan/execution/stores/service/showcase/ServiceStoreJsonShowcaseTest.java
  legend-engine-executionPlan-execution-external-store-service/src/test/resources/showcase/json/mapping.pure
  legend-engine-executionPlan-execution-external-store-service/src/test/resources/showcase/json/pathContent.json
  legend-engine-executionPlan-execution-external-store-service/src/test/resources/showcase/json/serviceStore.pure
  legend-engine-language-external-store-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceStoreLexerGrammar.g4
  legend-engine-language-external-store-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceStoreParserGrammar.g4
  legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/grammar/from/ServiceStoreParseTreeWalker.java
  legend-engine-language-external-store-service/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperServiceStoreGrammarComposer.java
  legend-engine-language-external-store-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceStoreCompilationFromGrammar.java
  legend-engine-language-external-store-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceStoreMappingCompilationFromGrammar.java
  legend-engine-language-external-store-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceStoreGrammarRoundtrip.java
  legend-engine-language-external-store-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceStoreMappingGrammarRoundtrip.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/PureGrammarComposerUtility.java
Labels: cla-present

#507 Fix local mapping property parsing
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/PureInstanceClassMappingParseTreeWalker.java
  legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalParseTreeWalker.java
  legend-engine-language-pure-store-relational/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalMappingGrammarParser.java
Labels: cla-present

#523 Upgrade Pure to 1.48.0
  pom.xml
Labels: cla-present

#491 Add support for CrossStore union & refactor platform store plan generation
  legend-engine-executionPlan-execution-external-store-service/src/test/java/org/finos/legend/engine/plan/execution/stores/service/union/TestServiceStoreUnion.java
  legend-engine-executionPlan-execution-external-store-service/src/test/resources/union/mapping.pure
  legend-engine-executionPlan-execution-external-store-service/src/test/resources/union/model.pure
  legend-engine-executionPlan-execution-external-store-service/src/test/resources/union/pathContent.json
  legend-engine-executionPlan-execution-external-store-service/src/test/resources/union/serviceStore.pure
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
Labels: cla-present
