Repository finos/legend-engine, pull requests merged in 2022-12, with the labels that each got.

#1181 Add support for registration of services with binding queries
  legend-engine-language-pure-dsl-service/pom.xml
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/HelperServiceBuilder.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceCompilationFromGrammar.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarRoundtrip.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/metaExtension.pure
Labels: enhancement, cla-present

#1209 fix bug in filterOnView
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/tests/businessDateMilestoningSetUp.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/tests/testBusinessDateMilestoning.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
Labels: cla-present

#1208 Persistence: Fix the failing test in Bitemporal Delta
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/BitemporalDeltaPlanner.java
Labels: cla-present

#1207 Updating M2M Error Message To Include Context On What Failed
  legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
  legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/simpleM2MService.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchInMemory.pure
Labels: cla-present

#1205 Throw warnings for incompatible types in relational property mappings
  legend-engine-xt-relationalStore-grammar/pom.xml
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/testRelationalExtension.pure
Labels: cla-present

#1214 Change LogInfo APIs
  legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/logs/LogInfo.java
Labels: cla-present

#1215 Revert "Throw warnings for incompatible types in relational property mappings"
  legend-engine-xt-relationalStore-grammar/pom.xml
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/testRelationalExtension.pure
Labels: cla-present

#1217 prevent overriding of generated milestoning date properties
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/Milestoning.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PackageableElementSecondPassBuilder.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
Labels: cla-present

#1222 Revert "Support LatestDate in relational graphFetch (#1185)"
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/compilation/GeneratePureConfig.java
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/date/AbstractPureDate.java
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/date/LatestDate.java
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/date/PureDate.java
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/store/platform/ISerializationWriter.java
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/util/Library.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/helpers/ExecutionNodeSerializerHelper.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/helpers/platform/DefaultExecutionNodeContext.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/GraphFetchTreeParseTreeWalker.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/date/testDateElementFunctions.pure
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/conventions.pure
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/metamodel_factories.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/enginePlatformDependencies.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/pureDateLibrary.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/pureDateLibraryTests.pure
  legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/graphFetchRelational.pure
  legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/executionPlanTest.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/testGraphFetchMilestoning.pure
Labels: cla-present

#1197 Post Process Table/Schema Mapping by Traversing the Query
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/runtime/connection/postprocessor.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/runtime/connection/tests/testMapperPostProcessor.pure
Labels: cla-present

#1226 Pure IDE: Expose source information for getDiagramInfo service
  legend-engine-pure-ide-light/src/main/resources/pure_ide/diagram.pure
Labels: enhancement, cla-present

#1212 Remove Url support with internalize and stage for cleanup
  legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ExternalFormatCompilerExtension.java
  legend-engine-external-shared-format-runtime/src/test/java/org/finos/legend/engine/external/shared/runtime/test/TestExternalFormatQueries.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceCompilationFromGrammar.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarRoundtrip.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/deprecated.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/executionPlan_diagram.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/executionPlan_generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/executionPlan_print.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/model.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/tests/executionPlanTests.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/functions/functions.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/schemaSet/metamodel_diagram.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/data/data.pure
  legend-engine-xt-flatdata-pure/src/main/resources/core_external_format_flatdata/executionPlan/tests/executionPlanTest.pure
  legend-engine-xt-flatdata-runtime/src/test/java/org/finos/legend/engine/external/format/flatdata/read/test/TestFlatDataQueries.java
  legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/executionPlanTest.pure
  legend-engine-xt-json-pure/src/main/resources/core_external_format_json/executionPlan/tests/executionPlanTest.pure
  legend-engine-xt-json-runtime/src/test/java/org/finos/legend/engine/external/format/json/read/test/TestJsonSchemaQueries.java
  legend-engine-xt-json-runtime/src/test/java/org/finos/legend/engine/external/format/json/read/test/TestJsonSchemaQueriesDeprecated.java
  legend-engine-xt-xml-pure/src/main/resources/core_external_format_xml/executionPlan/tests/executionPlanTest.pure
  legend-engine-xt-xml-runtime/src/test/java/org/finos/legend/engine/external/format/xml/test/TestXmlQueries.java
Labels: cla-present

#1227 use github action which downloads artifacts across workflows
  .github/workflows/database-bigquery-sql-generation-integration-test.yml
  .github/workflows/database-databricks-sql-generation-integration-test.yml
  .github/workflows/database-mssqlserver-sql-generation-integration-test.yml
  .github/workflows/database-postgresql-sql-generation-integration-test.yml
  .github/workflows/database-redshift-sql-generation-integration-test.yml
  .github/workflows/database-snowflake-sql-generation-integration-test.yml
  .github/workflows/database-spanner-sql-generation-integration-test.yml
  .github/workflows/summarize-sql-generation-integration-tests.yml
Labels: cla-present

#1218 GraphQL file generation in studio pipelines
  legend-engine-extensions-collection-generation/pom.xml
  legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
  legend-engine-language-pure-dsl-generation/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/fileGeneration/FileGenerationType.java
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/deprecated/generation.pure
  legend-engine-xt-graphQL-query/pom.xml
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/format/GraphQLGenerationConfigFromFileGenerationSpecificationBuilder.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/format/GraphQLGenerationExtension.java
  legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLFileGeneration.java
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/schema.graphql
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/simpleFileGeneration.json
Labels: enhancement, cla-present

#1229 download summary of failed actions too
  .github/workflows/summarize-sql-generation-integration-tests.yml
Labels: cla-present

#1221 Revert parseDate implementation of sybase IQ
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/sybaseIQ/sybaseIQExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/sqlFunction/testSqlFunctionsInMapping.pure
Labels: cla-present

#1223 Support nested sequence node on java binding
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/bindPlanToLegendJavaPlatform.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/graphFetchCommon.pure
  legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/executionPlanTest.pure
Labels: bug, cla-present

#1228 Remove deprecated GraphQL API constructors
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/debug/GraphQLDebug.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecute.java
  legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLAPI.java
Labels: cla-present

#1232 Rename shared external format Java binding packages
  legend-engine-external-shared-format-runtime/src/main/java/org/finos/legend/engine/external/shared/ExternalFormatJavaCompilerExtension.java
  legend-engine-external-shared-format-runtime/src/test/java/org/finos/legend/engine/external/shared/format/test/GeneratePlanDataClasses.java
  legend-engine-external-shared-format-runtime/src/test/java/org/finos/legend/engine/external/shared/runtime/test/TestExternalFormatQueries.java
  legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/descriptor.pure
  legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/externalize.pure
  legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/internalize.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding.definition.json
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/binding/bindingLegendJavaPlatformBindingExtension.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/binding/descriptor.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/binding/engineDependencies.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/binding/executionPlanTest.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/binding/shared.pure
  legend-engine-xt-javaPlatformBinding-pure/src/test/java/org/finos/legend/engine/pure/code/core/Test_Pure_JavaPlatformBinding.java
  legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/descriptor.pure
  legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/externalize.pure
  legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/internalize.pure
  legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/relationalLegendJavaPlatformBindingExtension.pure
  legend-engine-xt-serviceStore-javaPlatformBinding-pure/src/main/resources/core_servicestore_java_platform_binding/legendJavaPlatformBinding/serviceStoreLegendJavaPlatformBindingExtension.pure
  legend-engine-xt-xml-javaPlatformBinding-pure/src/main/resources/core_external_format_xml_java_platform_binding/legendJavaPlatformBinding/descriptor.pure
  legend-engine-xt-xml-javaPlatformBinding-pure/src/main/resources/core_external_format_xml_java_platform_binding/legendJavaPlatformBinding/internalize.pure
Labels: enhancement, cla-present

#1139 Enable DAML generation in Studio
  legend-engine-extensions-collection-generation/pom.xml
  legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
  legend-engine-language-pure-dsl-generation/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/fileGeneration/FileGenerationType.java
  legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/logs/LoggingEventType.java
  legend-engine-xt-daml-model/pom.xml
  legend-engine-xt-daml-model/src/main/java/org/finos/legend/engine/external/format/daml/generation/DAMLGenerationConfig.java
  legend-engine-xt-daml-model/src/main/java/org/finos/legend/engine/external/format/daml/generation/DAMLGenerationConfigFromFileGenerationSpecificationBuilder.java
  legend-engine-xt-daml-model/src/main/java/org/finos/legend/engine/external/format/daml/generation/DAMLGenerationExtension.java
  legend-engine-xt-daml-model/src/main/java/org/finos/legend/engine/external/format/daml/generation/DAMLGenerationInput.java
  legend-engine-xt-daml-model/src/main/java/org/finos/legend/engine/external/format/daml/generation/DAMLGenerationService.java
  legend-engine-xt-daml-model/src/main/resources/META-INF/services/org.finos.legend.engine.external.shared.format.extension.GenerationExtension
  legend-engine-xt-daml-pure/src/main/resources/core_external_language_daml/deprecated/generation.pure
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/deprecated/generation.pure
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/format/generation/GraphQLGenerationConfig.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/format/generation/GraphQLGenerationConfigFromFileGenerationSpecificationBuilder.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/format/generation/GraphQLGenerationExtension.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/format/generation/GraphQLGenerationInput.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/format/generation/GraphQLGenerationService.java
  legend-engine-xt-graphQL-query/src/main/resources/META-INF/services/org.finos.legend.engine.external.shared.format.extension.GenerationExtension
  legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLFileGeneration.java
Labels: cla-present

#1233 documentation for adding new relational connectors
  docs/store/extensions/Relational/README.md
  docs/store/extensions/Relational/database-integration-tests/README.md
  docs/store/extensions/Relational/new-connector-tutorial.md
Labels: cla-present

#1235 Rename platform Java binding packages
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/bindPlanToLegendJavaPlatform.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/graphFetchCommon.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchInMemory.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchStoreStreamReading.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/engineConventions.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/metaLibrary.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/platform/executionPlanNodes/platform/objectReference.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/platform/executionPlanNodes/platform/platform.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/platform/executionPlanNodes/platform/serialize.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/platform/executionPlanNodes/platformMerge/platformMerge.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/platform/executionPlanNodes/platformUnion/platformUnion.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/shared/common.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/shared/units.pure
  legend-engine-xt-json-javaPlatformBinding-pure/src/main/resources/core_external_format_json_java_platform_binding/legendJavaPlatformBinding/externalize.pure
  legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/graphFetchRelational.pure
  legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/platform/platform.pure
  legend-engine-xt-serviceStore-javaPlatformBinding-pure/src/main/resources/core_servicestore_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/limit/limit.pure
Labels: enhancement, cla-present

#1237 Upgrade legend pure version
  pom.xml
Labels: cla-present

#1236 support for allVersionInRange with businessSnapshotMilestoning
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/milestoning.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/tests/testBusinessSnapshotMilestoning.pure
Labels: cla-present

#1213 Provide a configurable way to set up Infinite batch_id value and ANSI tests for bitemporal delta statistics
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/logicalplan/values/InfiniteBatchIdValueAbstract.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/util/LogicalPlanUtils.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-physical-plan/src/main/java/org/finos/legend/engine/persistence/components/transformer/AbstractTransformer.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-physical-plan/src/main/java/org/finos/legend/engine/persistence/components/transformer/LogicalPlanVisitor.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-physical-plan/src/main/java/org/finos/legend/engine/persistence/components/transformer/Transformer.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/main/java/org/finos/legend/engine/persistence/components/relational/ansi/AnsiSqlSink.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/main/java/org/finos/legend/engine/persistence/components/relational/ansi/sql/visitors/InfiniteBatchIdValueVisitor.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/bitemporal/BitemporalDeltaWithBatchIdTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-core/src/main/java/org/finos/legend/engine/persistence/components/relational/api/RelationalGeneratorAbstract.java
Labels: cla-present

#1240 Always lowercase reservedKeyword check
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/h2/h2Extension.pure
Labels: cla-present

#1246 add tutorial section on adding new data source or auth strategy specs
  docs/store/extensions/Relational/new-connector-tutorial.md
Labels: cla-present

#1248 Pure IDE: minor fixes for concept tree display
  legend-engine-pure-ide-light/src/main/resources/pure_ide/concepts.pure
Labels: bug, cla-present

#1254 Add support for matches in dynaFunction for memSQL
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/databricks/databricksExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/memSqlExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/dynaFunctions/string.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuiteCompletenessTests.pure
Labels: cla-present

#1252 Memsql boolean literal processor fix
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/customMemSQLTests.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/memSqlExtension.pure
Labels: cla-present

#1220 Add testing support for services with binding
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ValueSpecificationBuilder.java
  legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceParserGrammar.g4
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceCompilationFromGrammar.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarRoundtrip.java
  legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/core/M3LexerGrammar.g4
  legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/core/M3ParserGrammar.g4
  legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/domain/DomainParserGrammar.g4
  legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/mapping/MappingParserGrammar.g4
  legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/mapping/aggregationAware/AggregationAwareParserGrammar.g4
  legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/mapping/operationClassMapping/OperationClassMappingParserGrammar.g4
  legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/mapping/pureInstanceClassMapping/PureInstanceClassMappingParserGrammar.g4
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/DomainParseTreeWalker.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/DEPRECATED_PureGrammarComposerCore.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/data/ModelStoreDataGrammarComposer.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/ValueSpecification.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/ValueSpecificationVisitor.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/CByteStream.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/legend/service/serviceValidationHelper.pure
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ValueSpecificationToResultVisitor.java
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/TestValueSpecificationBuilder.java
  legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/helper/PrimitiveValueSpecificationToObjectVisitor.java
  legend-engine-xt-persistence-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/PersistenceParserGrammar.g4
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/grammar/to/PrimitiveValueSpecificationToObjectVisitor.java
  legend-engine-xt-relationalStore-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/data/RelationalEmbeddedDataParserGrammar.g4
  legend-engine-xt-serviceStore-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceStoreParserGrammar.g4
Labels: cla-present, not backwards compatible

#1135 Enable spanner
  legend-engine-extensions-collection-generation/pom.xml
  legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
  legend-engine-server/pom.xml
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/pom.xml
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/main/java/org/finos/legend/engine/authentication/LegendDefaultDatabaseAuthenticationFlowProvider.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/test/java/org/finos/legend/engine/authentication/TestDefaultSupportedFlows.java
  legend-engine-xt-relationalStore-spanner-execution-tests/pom.xml
  legend-engine-xt-relationalStore-spanner-execution/pom.xml
  legend-engine-xt-relationalStore-spanner-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/spanner/driver/SpannerDriver.java
  legend-engine-xt-relationalStore-spanner-jdbc-shaded/pom.xml
  pom.xml
Labels: cla-present, not backwards compatible

#1255 Revert "Enable spanner (#1135)"
  legend-engine-extensions-collection-generation/pom.xml
  legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
  legend-engine-server/pom.xml
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/pom.xml
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/main/java/org/finos/legend/engine/authentication/LegendDefaultDatabaseAuthenticationFlowProvider.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/test/java/org/finos/legend/engine/authentication/TestDefaultSupportedFlows.java
  legend-engine-xt-relationalStore-spanner-execution-tests/pom.xml
  legend-engine-xt-relationalStore-spanner-execution/pom.xml
  legend-engine-xt-relationalStore-spanner-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/spanner/driver/SpannerDriver.java
  legend-engine-xt-relationalStore-spanner-jdbc-shaded/pom.xml
  pom.xml
Labels: cla-present

#1259 improve handling of platform functions in M2M
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/chain.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
Labels: bug, cla-present

#1260 Throw better error message for mis-configured runtime
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/runtime/runtimeExtension.pure
Labels: cla-present

#1257 Rename library Java binding packages
  legend-engine-server/src/test/java/org/finos/legend/engine/server/test/pureClient/executionPlan/Test_ExecutionPlan_JavaPlatform_UsingPureClient.java
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchJson.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchXml.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/assertLibrary.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/booleanLibrary.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/collectionsLibrary.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/engineConventions.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/jacksonSupport.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/langLibrary.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/mathLibrary.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/metaLibrary.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/multiplicityLibrary.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/pureDateLibrary.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/runtimeLibrary.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/stringLibrary.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/booleanLibraryTests.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/collectionsLibraryTests.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/langLibraryTests.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/mathLibraryTests.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/metaLibraryTests.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/multiplicityLibraryTests.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/pureDateLibraryTests.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/runtimeLibraryTests.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/stringLibraryTests.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/testUtils.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/unitLibraryTests.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/unitLibrary.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/shared/common.pure
Labels: enhancement, cla-present

#1258 Add deserialize and execute plan tests for relational crossStore graphFetch
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/graphFetch/crossStore/TestDeserializeAndExecuteRelationalCrossStoreGraphFetchExecutionPlan.java
  legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/full/graphFetch/crossStore/withByteCode/plan1.json
  legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/full/graphFetch/crossStore/withSourceCode/plan1.json
Labels: cla-present

#1058 Add support for SQL query protocol
  legend-engine-pure-ide-light/pom.xml
  legend-engine-pure-ide-light/src/main/java/org/finos/legend/engine/ide/PureIDELight.java
  legend-engine-server/pom.xml
  legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
  legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig.json
  legend-engine-xt-sql-compiler/pom.xml
  legend-engine-xt-sql-compiler/src/test/java/org/finos/legend/engine/protocol/sql/GenerateTestQueryBuilder.java
  legend-engine-xt-sql-grammar-integration/pom.xml
  legend-engine-xt-sql-grammar-integration/src/main/java/org/finos/legend/engine/language/sql/grammar/integration/SQLCompilerExtension.java
  legend-engine-xt-sql-grammar-integration/src/main/java/org/finos/legend/engine/language/sql/grammar/integration/SQLEmbeddedPureParser.java
  legend-engine-xt-sql-grammar-integration/src/main/java/org/finos/legend/engine/language/sql/grammar/integration/SQLGrammarParserExtension.java
  legend-engine-xt-sql-grammar-integration/src/main/java/org/finos/legend/engine/language/sql/grammar/integration/SQLPureGrammarComposerExtension.java
  legend-engine-xt-sql-grammar-integration/src/main/java/org/finos/legend/engine/language/sql/grammar/integration/SQLPureProtocolExtension.java
  legend-engine-xt-sql-grammar-integration/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.compiler.toPureGraph.extension.CompilerExtension
  legend-engine-xt-sql-grammar-integration/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.grammar.from.extension.PureGrammarParserExtension
  legend-engine-xt-sql-grammar-integration/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.grammar.to.extension.PureGrammarComposerExtension
  legend-engine-xt-sql-grammar-integration/src/main/resources/META-INF/services/org.finos.legend.engine.protocol.pure.v1.extension.PureProtocolExtension
  legend-engine-xt-sql-grammar-integration/src/test/java/org/finos/legend/engine/language/sql/grammar/integration/compiled/natives/test/TestSQLEmbeddedCompiled.java
  legend-engine-xt-sql-grammar-integration/src/test/java/org/finos/legend/engine/language/sql/grammar/integration/interpreted/natives/test/TestSQLEmbeddedInterpreted.java
  legend-engine-xt-sql-grammar-integration/src/test/java/org/finos/legend/engine/language/sql/grammar/integration/test/TestSQLEmbedded.java
  legend-engine-xt-sql-grammar/pom.xml
  legend-engine-xt-sql-grammar/src/main/antlr4/org/finos/legend/engine/language/sql/grammar/from/antlr4/SqlBase.g4
  legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/from/SQLGrammarParser.java
  legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/from/SQLParserException.java
  legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/from/SqlVisitor.java
  legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/to/SQLGrammarComposer.java
  legend-engine-xt-sql-grammar/src/test/java/org/finos/legend/engine/language/sql/grammar/test/roundtrip/TestSQLRoundTrip.java
  legend-engine-xt-sql-protocol/pom.xml
  legend-engine-xt-sql-pure-metamodel/pom.xml
  legend-engine-xt-sql-pure-metamodel/src/main/java/org/finos/legend/engine/code/core/CoreExternalQuerySQLMetamodelCodeRepositoryProvider.java
  legend-engine-xt-sql-pure-metamodel/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.filesystem.repository.CodeRepositoryProvider
  legend-engine-xt-sql-pure-metamodel/src/main/resources/core_external_query_sql_metamodel.definition.json
  legend-engine-xt-sql-pure-metamodel/src/main/resources/core_external_query_sql_metamodel/metamodel.pure
  legend-engine-xt-sql-pure/pom.xml
  legend-engine-xt-sql-pure/src/main/java/org/finos/legend/engine/code/core/CoreExternalQuerySQLCodeRepositoryProvider.java
  legend-engine-xt-sql-pure/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.filesystem.repository.CodeRepositoryProvider
  legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql.definition.json
  legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
  legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/shared.pure
  legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
  legend-engine-xt-sql-pure/src/test/java/org/finos/legend/engine/code/core/Test_SQL_Pure.java
  legend-engine-xt-sql-query/pom.xml
  legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/execute/MyCookie.java
  legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/execute/SqlExecute.java
  legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/grammar/SqlGrammar.java
  pom.xml
Labels: cla-present

#1265 M2M - Update equals on property returning null
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/qualifiedProperties.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/shared.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/booleanLibrary.pure
Labels: cla-present

#1261 update shade plugin version
  legend-engine-server/pom.xml
  pom.xml
Labels: cla-present

#1272 Add optional field support for protobuf
  legend-engine-xt-protobuf-grammar/src/main/antlr4/org/finos/legend/engine/language/protobuf3/grammar/from/antlr4/Protobuf3.g4
  legend-engine-xt-protobuf-grammar/src/main/java/org/finos/legend/engine/language/protobuf3/grammar/from/Protobuf3GrammarParser.java
  legend-engine-xt-protobuf-grammar/src/main/java/org/finos/legend/engine/language/protobuf3/grammar/to/Protobuf3GrammarComposer.java
  legend-engine-xt-protobuf-grammar/src/test/java/org/finos/legend/engine/language/protobuf3/grammar/test/TestProtobuf3.java
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/metamodel/metamodel.pure
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/metamodel/metamodel_serialization.pure
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/transformation/fromPure/pureToProtobuf.pure
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/transformation/fromPure/tests/pureToProtobufTests.pure
  legend-engine-xt-protobuf/src/test/java/org/finos/legend/engine/external/format/protobuf/tests/TestProtobufFileGeneration.java
Labels: cla-present

#1266 Add connector for Athena
  .github/workflows/database-athena-integration-test.yml
  .github/workflows/database-athena-sql-generation-integration-test.yml
  .github/workflows/summarize-sql-generation-integration-tests.yml
  docs/store/extensions/Relational/database-integration-tests/README.md
  legend-engine-pure-ide-light/src/main/java/org/finos/legend/engine/ide/PureIDELight.java
  legend-engine-xt-relationalStore-athena-execution-tests/pom.xml
  legend-engine-xt-relationalStore-athena-execution-tests/src/main/java/org/finos/legend/engine/authentication/AthenaTestDatabaseAuthenticationFlowProvider.java
  legend-engine-xt-relationalStore-athena-execution-tests/src/main/java/org/finos/legend/engine/authentication/AthenaTestDatabaseAuthenticationFlowProviderConfiguration.java
  legend-engine-xt-relationalStore-athena-execution-tests/src/main/resources/META-INF/services/org.finos.legend.engine.authentication.provider.DatabaseAuthenticationFlowProvider
  legend-engine-xt-relationalStore-athena-execution-tests/src/test/java/org/finos/legend/engine/AthenaRelationalTestServerInvoker.java
  legend-engine-xt-relationalStore-athena-execution-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProvider_Athena.java
  legend-engine-xt-relationalStore-athena-execution-tests/src/test/java/org/finos/legend/engine/server/test/pureClient/stores/dbSpecific/Test_Relational_DbSpecific_Athena_UsingPureClientTestSuite.java
  legend-engine-xt-relationalStore-athena-execution-tests/src/test/resources/org/finos/legend/engine/server/test/athenaRelationalDatabaseConnections.json
  legend-engine-xt-relationalStore-athena-execution-tests/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withAthenaTestConnection.json
  legend-engine-xt-relationalStore-athena-execution/pom.xml
  legend-engine-xt-relationalStore-athena-execution/src/main/java/org/finos/legend/engine/authentication/flows/AthenaWithUserNamePasswordFlow.java
  legend-engine-xt-relationalStore-athena-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/AthenaConnectionExtension.java
  legend-engine-xt-relationalStore-athena-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/athena/AthenaCommands.java
  legend-engine-xt-relationalStore-athena-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/athena/AthenaDriver.java
  legend-engine-xt-relationalStore-athena-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/athena/AthenaManager.java
  legend-engine-xt-relationalStore-athena-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/AthenaDatasourceSpecificationRuntime.java
  legend-engine-xt-relationalStore-athena-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/keys/AthenaDatasourceSpecificationKey.java
  legend-engine-xt-relationalStore-athena-execution/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.RelationalConnectionExtension
  legend-engine-xt-relationalStore-athena-execution/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.connection.ConnectionExtension
  legend-engine-xt-relationalStore-athena-execution/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.connection.manager.strategic.StrategicConnectionExtension
  legend-engine-xt-relationalStore-athena-grammar/pom.xml
  legend-engine-xt-relationalStore-athena-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/AthenaLexerGrammar.g4
  legend-engine-xt-relationalStore-athena-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/AthenaParserGrammar.g4
  legend-engine-xt-relationalStore-athena-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/AthenaCompilerExtension.java
  legend-engine-xt-relationalStore-athena-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/AthenaGrammarParserExtension.java
  legend-engine-xt-relationalStore-athena-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/AthenaGrammarComposerExtension.java
  legend-engine-xt-relationalStore-athena-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.compiler.toPureGraph.extension.CompilerExtension
  legend-engine-xt-relationalStore-athena-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.grammar.from.IRelationalGrammarParserExtension
  legend-engine-xt-relationalStore-athena-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.grammar.to.extension.PureGrammarComposerExtension
  legend-engine-xt-relationalStore-athena-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestAthenaConnectionGrammarRoundtrip.java
  legend-engine-xt-relationalStore-athena-protocol/pom.xml
  legend-engine-xt-relationalStore-athena-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/AthenaProtocolExtension.java
  legend-engine-xt-relationalStore-athena-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/specification/AthenaDatasourceSpecification.java
  legend-engine-xt-relationalStore-athena-protocol/src/main/resources/META-INF/services/org.finos.legend.engine.protocol.pure.v1.extension.PureProtocolExtension
  legend-engine-xt-relationalStore-athena-pure/pom.xml
  legend-engine-xt-relationalStore-athena-pure/src/main/java/org/finos/legend/pure/code/core/CoreRelationalAthenaCodeRepositoryProvider.java
  legend-engine-xt-relationalStore-athena-pure/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.filesystem.repository.CodeRepositoryProvider
  legend-engine-xt-relationalStore-athena-pure/src/main/resources/core_relational_athena.definition.json
  legend-engine-xt-relationalStore-athena-pure/src/main/resources/core_relational_athena/relational/connection/metamodel.pure
  legend-engine-xt-relationalStore-athena-pure/src/main/resources/core_relational_athena/relational/protocols/pure/vX_X_X/extension/extension_athena.pure
  legend-engine-xt-relationalStore-athena-pure/src/main/resources/core_relational_athena/relational/protocols/pure/vX_X_X/model/metamodel_connection.pure
  legend-engine-xt-relationalStore-athena-pure/src/main/resources/core_relational_athena/relational/sqlQueryToString/athenaExtension.pure
  legend-engine-xt-relationalStore-athena-pure/src/main/resources/core_relational_athena/relational/sqlQueryToString/athenaTestSuiteInvoker.pure
  legend-engine-xt-relationalStore-athena-pure/src/test/java/org/finos/legend/pure/code/core/Test_Pure_Relational_DbSpecific_Athena.java
  legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/DatabaseType.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/selectSubClauses/view.pure
  legend-engine-xt-relationalStore-test-server/src/main/java/org/finos/legend/engine/server/test/shared/ExecuteInRelationalDb.java
  pom.xml
Labels: cla-present, requires PURE

#1273 Throw warning if both legacy and strategic tests are used
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/ServiceCompilerExtensionImpl.java
Labels: cla-present

#1274 improve db integration tests docs
  docs/store/extensions/Relational/README.md
  docs/store/extensions/Relational/database-integration-tests/README.md
Labels: cla-present
