Repository finos/legend-engine, pull requests merged in 2022-10, with the labels that each got.

#1001 Fix service store mapping compiler
  legend-engine-xt-serviceStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperServiceStoreClassMappingBuilder.java
  legend-engine-xt-serviceStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceStoreMappingCompilationFromGrammar.java
Labels: cla-present

#996 throw error instead of warning from pure when engine is enabled but test conn not found
  legend-engine-extensions-collection-generation/pom.xml
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/dbTestRunner/shared.pure
Labels: cla-present

#1005 Increase nexus plugin staging timeout
  pom.xml
Labels: cla-present

#1010 Updating GCP build config
  .gcp/cloud-build/build.sh
  .gcp/cloud-build/cloudbuild.yaml
Labels: enhancement, cla-present

#1003 fix dataSpace Analytics with Association
  legend-engine-external-shared/src/main/java/org/finos/legend/engine/external/shared/format/imports/PureModelContextDataGenerator.java
  legend-engine-xt-data-space-api/src/test/java/org/finos/legend/engine/api/analytics/test/TestDataSpaceAnalyticsApi.java
  legend-engine-xt-data-space-api/src/test/resources/dataSpaceAnalyticsWithAssociation.json
Labels: bug, cla-present, approved

#1012 Specifying GCP region
  .gcp/cloud-build/build.sh
  .github/workflows/trigger-gcp-build.yml
Labels: bug, cla-present

#1013 Fixing quotes in GitHub actions
  .gcp/cloud-build/build.sh
  .github/workflows/trigger-gcp-build.yml
Labels: bug, cla-present

#1014 Updating GCP build script
  .gcp/cloud-build/build.sh
Labels: cla-present

#1004 properly process connections for LegacyRuntime
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRuntimeBuilder.java
Labels: bug, cla-present

#994 Apply fix for false realizeInMemory calls during plan execution (edited)
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/ExecutionNodeExecutor.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/state/ExecutionState.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/AllocationExecutionNode.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/ExecutionNode.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/models/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/executionPlan.pure
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/RelationalExecutor.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalExecutionNodeExecutor.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/RealizedRelationalResult.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/AlloyTestServer.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/tdsJoin/TestTDSJoinRealizedResults.java
  legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/full/tdsJoin/TestTDSJoin.json
  legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/full/tdsJoin/TestTDSJoinExpectedFail.json
Labels: cla-present

#984 Upgrade legend-pure version to 3.7.0
  pom.xml
Labels: cla-present, dependencies

#986 fix issue with printing of database names in join chains
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalParseTreeWalker.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalMappingGrammarRoundtrip.java
Labels: cla-present

#992 Improve error messages for failing to fetch metadata
  legend-engine-language-pure-modelManager-sdlc/src/main/java/org/finos/legend/engine/language/pure/modelManager/sdlc/SDLCLoader.java
  legend-engine-language-pure-modelManager-sdlc/src/main/java/org/finos/legend/engine/language/pure/modelManager/sdlc/alloy/AlloySDLCLoader.java
  legend-engine-shared-core/src/main/resources/ExceptionData.json
Labels: cla-present

#1017 standardize engine port to `60xx` range
  README.md
  legend-engine-pure-ide-light/src/main/resources/ideLightConfig.json
  legend-engine-server-integration-tests/config/config.json
  legend-engine-server/config/config.json
  legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig.json
  legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withFlowProvider.json
  legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withMetadataFromIDELight.json
  legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withVault.json
  legend-engine-xt-relationalStore-sqlserver-execution-tests/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withSqlServerTestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withDatabricksTestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withH2TestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withPostgresTestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withRedshiftTestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withSnowflakeTestConnection.json
  pom.xml
Labels: cla-present

#1019 standardize Engine port to 6300
  README.md
  legend-engine-server-integration-tests/config/config.json
  legend-engine-server/config/config.json
  legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig.json
  legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withFlowProvider.json
  legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withMetadataFromIDELight.json
  legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withVault.json
  legend-engine-xt-relationalStore-sqlserver-execution-tests/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withSqlServerTestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withDatabricksTestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withH2TestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withPostgresTestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withRedshiftTestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withSnowflakeTestConnection.json
Labels: cla-present

#1020 allow specifying session cookie name
  README.md
  legend-engine-pure-ide-light/src/main/resources/ideLightConfig.json
  legend-engine-server-integration-tests/config/config.json
  legend-engine-server/config/config.json
  legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
  legend-engine-server/src/main/java/org/finos/legend/engine/server/ServerConfiguration.java
  legend-engine-server/src/main/resources/docker/config/config.json
  legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig.json
  legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withFlowProvider.json
  legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withMetadataFromIDELight.json
  legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withVault.json
  legend-engine-xt-relationalStore-sqlserver-execution-tests/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withSqlServerTestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withDatabricksTestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withH2TestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withPostgresTestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withRedshiftTestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withSnowflakeTestConnection.json
Labels: cla-present

#1023 unignore test failure in PR builds
  .github/workflows/build.yml
  pom.xml
Labels: cla-present

#1022 Update test server config to ignore unknown properties
  legend-engine-xt-relationalStore-sqlserver-execution-tests/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withSqlServerTestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withDatabricksTestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withH2TestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withPostgresTestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withRedshiftTestConnection.json
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withSnowflakeTestConnection.json
Labels: cla-present

#1025 Protocol Version v1_27_0
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/PureClientVersions.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_27_0/extension/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_27_0/models/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_27_0/models/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_27_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_27_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/extension/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/invocations/execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/invocations/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/invocations/testLoadModels.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/models/diagram.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/models/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/models/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/models/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/models/results.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/scan/buildBasePureModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/scan/buildPureModelAsText.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/scan/testBuildPureModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/transfers/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/transfers/mapping.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/transfers/store.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/transfers/valueSpecification.pure
  legend-engine-xt-avro-pure/src/main/resources/core_external_format_avro/protocol/protocol_v1_27_0.pure
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/protocol/protocol_v1_27_0.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_27_0/extension/extension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_27_0/extension/extension_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_27_0/invocations/execution_relation_executeInRelationalDb.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_27_0/invocations/execution_relational_execute.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_27_0/invocations/execution_relational_testConnection.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_27_0/invocations/execution_relational_testData.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_27_0/models/executionPlan_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_27_0/models/metamodel_connection.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_27_0/models/metamodel_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_27_0/models/results_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_27_0/models/testData_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_27_0/transfers/connection_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_27_0/transfers/metamodel_relational.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_27_0/extension/extension.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_27_0/extension/extension_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_27_0/models/executionPlan_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_27_0/models/metamodel_connection.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_27_0/models/metamodel_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_27_0/transfers/connection_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_27_0/transfers/metamodel_serviceStore.pure
Labels: cla-present

#1024 Configure heap size of surefire plugin
  pom.xml
Labels: enhancement, cla-present

#866 mapping testable mechanism
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperMappingBuilder.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PackageableElementFourthPassBuilder.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/data/core/EmbeddedDataCompilerHelper.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/test/core/TestCompilerHelper.java
  legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/data/embedded/modelStore/ModelStoreDataParserGrammar.g4
  legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/mapping/MappingLexerGrammar.g4
  legend-engine-language-pure-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/mapping/MappingParserGrammar.g4
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/PureGrammarParserUtility.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/data/embedded/ModelStoreDataParseTreeWalker.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/data/embedded/ModelStoreEmbeddedDataParser.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/MappingParseTreeWalker.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/DEPRECATED_PureGrammarComposerCore.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperMappingGrammarComposer.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/data/ModelStoreDataGrammarComposer.java
  legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/parser/TestMappingGrammarParser.java
  legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestMappingGrammarRoundtrip.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/CorePureProtocolExtension.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/extension/ConnectionFactoryExtension.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/Mapping.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/mappingTest/MappingTest.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/mappingTest/MappingTestSuite.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/mappingTest/MappingTest_Legacy.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/mappingTest/StoreTestData.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/ModelStore.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/connection/ModelStoreTestConnectionFactory.java
  legend-engine-protocol-pure/src/main/resources/META-INF/services/org.finos.legend.engine.protocol.pure.v1.extension.ConnectionFactoryExtension
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/metamodel.pure
  legend-engine-server/pom.xml
  legend-engine-test-runner-mapping/pom.xml
  legend-engine-test-runner-mapping/src/main/java/org/finos/legend/engine/test/runner/mapping/MappingTestRunner.java
  legend-engine-test-runner-mapping/src/main/java/org/finos/legend/engine/testable/mapping/extension/MappingTestRunner.java
  legend-engine-test-runner-mapping/src/main/java/org/finos/legend/engine/testable/mapping/extension/MappingTestableRunnerExtension.java
  legend-engine-test-runner-mapping/src/main/resources/META-INF/services/org.finos.legend.engine.testable.extension.TestableRunnerExtension
  legend-engine-test-runner-mapping/src/test/java/org/finos/legend/engine/test/runner/mapping/TestMappingTestRunner.java
  legend-engine-test-runner-mapping/src/test/java/org/finos/legend/engine/testable/mapping/extension/TestMappingTestRunner.java
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestRunner.java
  legend-engine-testable/pom.xml
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/assertion/TestAssertionEvaluator.java
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/assertion/TestAssertionHelper.java
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/connection/TestConnectionBuilder.java
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/helper/PrimitiveValueSpecificationToObjectVisitor.java
  legend-engine-testable/src/main/test/java/org/finos/legend/engine/testable/assertion/TestTestAssertionEvaluator.java
  legend-engine-testable/src/main/test/java/org/finos/legend/engine/testable/connection/TestTestConnectionBuilder.java
  legend-engine-xt-relationalStore-executionPlan/pom.xml
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/test/RelationalConnectionFactory.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/testable/mapping/TestMappingTestRunner.java
  legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/testable/mapping/relationalMappingTestSuites.pure
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalMappingGrammarParser.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalMappingGrammarRoundtrip.java
  legend-engine-xt-serviceStore-executionPlan/pom.xml
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/test/ServiceStoreTestConnectionFactory.java
  legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/testable/connection/TestServiceStoreTestConnectionBuilder.java
  legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/testable/mapping/TestMappingTestRunner.java
  legend-engine-xt-serviceStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceStoreMappingGrammarRoundtrip.java
Labels: enhancement, cla-present

#961 Introduce lineage analytics module
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/lineage/scanMapping.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/lineage/scanProject.pure
  legend-engine-pure-ide-light/src/main/java/org/finos/legend/engine/ide/PureIDELight.java
  legend-engine-server/pom.xml
  legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
  legend-engine-xt-analytics-lineage-api/pom.xml
  legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/LineageAnalytics.java
  legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/LineageAnalyticsInput.java
  legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/graph/Edge.java
  legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/graph/Graph.java
  legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/graph/GraphNode.java
  legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/report/Column.java
  legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/report/ColumnLineage.java
  legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/tree/PropertyPathTreeNode.java
  legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/tree/RelationalTreeNode.java
  legend-engine-xt-analytics-lineage-pure/pom.xml
  legend-engine-xt-analytics-lineage-pure/src/main/java/org/finos/legend/pure/code/core/CoreExternalLineageAnalysisCodeRepositoryProvider.java
  legend-engine-xt-analytics-lineage-pure/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.filesystem.repository.CodeRepositoryProvider
  legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage.definition.json
  legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/flow.pure
  legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/fullAnalytics.pure
  legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/graph.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/lineage/scanColumns/scanColumns.pure
  pom.xml
Labels: cla-present

#997 [Router clean up] Remove advanced routing
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetchExecutionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/XStore.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/mappingExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/modelToModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_main.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/chain.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/inMemory.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/storeContract.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/executionPlan/executionPlan_generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/storeContract.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/transform/fromPure/toSQLString.pure
Labels: cla-present

#1029 Fix new module versions
  legend-engine-xt-analytics-lineage-api/pom.xml
  legend-engine-xt-analytics-lineage-pure/pom.xml
Labels: cla-present

#1031 Fix decimal handling in relational graph fetch execution
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/graphFetch/dataTypes/TestRelationalGraphFetchExecutionDataTypes.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/javaRuntime/executionPlanNodes/graphFetch/graphFetchRelational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/javaRuntime/executionPlanNodes/relationalClassInstantiation/relationalClassResult.pure
Labels: bug, cla-present

#1027 Handle semi structured relational elements in milestoning filter application
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/milestoning.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/tests/testApplyMilestoningFilters.pure
Labels: bug, cla-present

#1000 Fix dockerfile - Individually copy files
  legend-engine-server/Dockerfile
Labels: cla-present

#1021 Milestoning: Bitemp VLF Exclude Source Validity From Time Column in Sink
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/BitemporalDeltaPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/BitemporalPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/IngestModeTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/bitemporal/BitemporalDeltaWithBatchIdTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/java/org/finos/legend/engine/persistence/components/TestUtils.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/bitemporal/BitemporalDeltaWithBatchIdTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/with_delete_ind/set_1/expected_pass1.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/with_delete_ind/set_1/expected_pass2.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/with_delete_ind/set_1/expected_pass3.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/with_delete_ind/set_1/expected_pass4.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/with_delete_ind/set_1/expected_pass5.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/with_delete_ind/set_2/expected_pass1.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/with_delete_ind/set_2/expected_pass2.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/with_delete_ind/set_3_with_data_split/expected_pass1.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/with_delete_ind/set_3_with_data_split/expected_pass2.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/with_delete_ind/set_3_with_data_split/expected_pass3.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/without_delete_ind/set_1/expected_pass1.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/without_delete_ind/set_1/expected_pass2.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/without_delete_ind/set_1/expected_pass3.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/without_delete_ind/set_1/expected_pass4.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/without_delete_ind/set_1/expected_pass5.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/without_delete_ind/set_2/expected_pass1.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/without_delete_ind/set_2/expected_pass2.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/without_delete_ind/set_3_with_data_split/expected_pass1.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/without_delete_ind/set_3_with_data_split/expected_pass2.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/without_delete_ind/set_3_with_data_split/expected_pass3.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/bitemporal-incremental-milestoning/expected/batch_id_based/source_specifies_from/without_delete_ind/set_3_with_data_split/expected_pass4.csv
Labels: cla-present

#1026 [Router Clean up] Move let function processing to platform store space
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetchExecutionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/modelToModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_cluster.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/chain.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/inMemory.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/executionPlan/executionPlan_generation.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
Labels: cla-present

#1038 Deserialize float value as BigDecimal in JSON assertion
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/assertion/TestAssertionHelper.java
  legend-engine-testable/src/main/test/java/org/finos/legend/engine/testable/assertion/TestTestAssertionEvaluator.java
  legend-engine-xt-persistence-test-runner/src/main/java/org/finos/legend/engine/testable/persistence/assertion/PersistenceTestAssertionEvaluator.java
Labels: bug, cla-present

#1042 Always set the user identity when executing
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/PlanExecutor.java
Labels: cla-present

#1044 Revert: Introduce lineage analytics module (#961)
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/lineage/scanMapping.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/lineage/scanProject.pure
  legend-engine-pure-ide-light/src/main/java/org/finos/legend/engine/ide/PureIDELight.java
  legend-engine-server/pom.xml
  legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
  legend-engine-xt-analytics-lineage-api/pom.xml
  legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/LineageAnalytics.java
  legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/LineageAnalyticsInput.java
  legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/graph/Edge.java
  legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/graph/Graph.java
  legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/graph/GraphNode.java
  legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/report/Column.java
  legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/report/ColumnLineage.java
  legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/tree/PropertyPathTreeNode.java
  legend-engine-xt-analytics-lineage-api/src/main/java/org/finos/legend/engine/api/analytics/model/tree/RelationalTreeNode.java
  legend-engine-xt-analytics-lineage-pure/pom.xml
  legend-engine-xt-analytics-lineage-pure/src/main/java/org/finos/legend/pure/code/core/CoreExternalLineageAnalysisCodeRepositoryProvider.java
  legend-engine-xt-analytics-lineage-pure/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.filesystem.repository.CodeRepositoryProvider
  legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage.definition.json
  legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/flow.pure
  legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/fullAnalytics.pure
  legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/graph.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/lineage/scanColumns/scanColumns.pure
  pom.xml
Labels: cla-present

#1049 BigQuery Tests - fix flowProviderConfig.json
  legend-engine-xt-relationalStore-bigquery-execution-tests/src/test/resources/org/finos/legend/engine/server/test/flowProviderConfig.json
Labels: cla-present

#1059 Bump apache commons text from 1.8 to 1.10.0
  pom.xml
Labels: cla-present

#1061 relational filter push down VarPlaceHolder fix
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/functions/in/TestPlanExecutionForIn.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/pushFiltersDownToJoin.pure
Labels: cla-present

#1055 Fix NPE bug in ServiceTestRunner
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ServiceTestRunner.java
Labels: cla-present

#1051 Fix processing of Inline embedded mapping
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestEmbeddedRelationalCompilationFromGrammar.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/embedded/testInlineEmbeddedNested.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/embedded/testInlineEmbeddedTargetIds.pure
Labels: bug, cla-present

#1035 enhance relational compiler extension - Allow connection to flow to postprocessor
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/IRelationalCompilerExtension.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/RelationalCompilerExtension.java
Labels: cla-present, not backwards compatible

#759 Support function overloading
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperModelBuilder.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestHelperModelBuilder.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRoundTripWithPureTransformation.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestMilestonedPropertyUsageInFunctionExpresions.java
  legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/SimpleRelationalServiceRunner.java
  legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/DomainParseTreeWalker.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperValueSpecificationGrammarComposer.java
  legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredFlattening.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredInheritanceMapping.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredJoinChainMapping.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredParseJsonMapping.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSimpleSemiStructuredMapping.java
Labels: cla-present, not backwards compatible

#1065 Persistence validation
  legend-engine-xt-persistence-cloud-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/cloud/compiler/toPureGraph/PersistenceCloudCompilerExtension.java
  legend-engine-xt-persistence-cloud-grammar/src/test/java/org/finos/legend/engine/pure/dsl/persistence/cloud/compiler/test/TestPersistenceCloudCompilationFromGrammar.java
  legend-engine-xt-persistence-cloud-grammar/src/test/java/org/finos/legend/engine/pure/dsl/persistence/cloud/compiler/test/ValidationRuleSetTest.java
  legend-engine-xt-persistence-cloud-pure/pom.xml
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/toPureGraph/HelperPersistenceBuilder.java
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/toPureGraph/IPersistenceCompilerExtension.java
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/toPureGraph/PersistenceCompilerExtension.java
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/toPureGraph/ValidationContext.java
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/validation/ValidationResult.java
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/validation/ValidationRule.java
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/validation/ValidationRuleSet.java
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/grammar/from/context/PersistencePlatformParser.java
  legend-engine-xt-persistence-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/test/TestPersistenceContextCompilationFromGrammar.java
  legend-engine-xt-persistence-pure/pom.xml
  legend-engine-xt-persistence-pure/src/main/resources/core_persistence/persistence/validation.pure
  legend-engine-xt-persistence-pure/src/main/resources/core_persistence/persistence/validations_rules.pure
  legend-engine-xt-persistence-pure/src/main/resources/core_persistence/test/validation_rules_test.pure
  legend-engine-xt-persistence-pure/src/main/resources/core_persistence/test/validation_test.pure
Labels: cla-present

#1073 Cleanup test dependencies in persistence milestoning modules.
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/pom.xml
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/pom.xml
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/pom.xml
  legend-engine-xt-persistence-component/pom.xml
Labels: cla-present

#1067 fixed issue related to dayOfWeek
  legend-engine-pure-code-compiled-core/src/main/resources/core/external/language/java/generation/conventions.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/query/datePeriods.pure
Labels: cla-present

#1076 Ensure empty sets of type String and mul 1 translate to empty String
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/CString.java
  legend-engine-protocol-pure/src/test/java/org/finos/legend/engine/protocol/test/TestCompatibilityAndMigration.java
  legend-engine-xt-graphQL-protocol/pom.xml
Labels: cla-present

#1084 Fix Relational Tree Scanning for Union with Views
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/lineage/scanRelations/scanRelations.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/lineage/scanRelations/scanRelationsTestWithViewsAndUnions.pure
Labels: cla-present

#1068 Add parameter values option to execute api
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/helpers/ExecuteNodeParameterTransformationHelper.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/HelperServiceBuilder.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/from/ServiceParseTreeWalker.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/HelperServiceGrammarComposer.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/ServiceTest.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/domain/ParameterValue.java
  legend-engine-query-pure/pom.xml
  legend-engine-query-pure/src/main/java/org/finos/legend/engine/query/pure/api/Execute.java
  legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestExecutionUtility.java
  legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestM2MGrammarCompileAndExecute.java
  legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestQueryExecutionWithParameters.java
  legend-engine-query-pure/src/test/resources/relationalQueryExecutionInputEnumZeroOne.json
  legend-engine-query-pure/src/test/resources/relationalQueryExecutionInputZeroMany.json
  legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/api/model/ExecuteInput.java
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestRunner.java
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/helper/PrimitiveValueSpecificationToObjectVisitor.java
Labels: enhancement, cla-present

#1070 Upgrade legend-pure version to 3.7.1
  pom.xml
Labels: cla-present, dependencies

#1089 Revert AssertForKeys
  legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceLexerGrammar.g4
  legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceParserGrammar.g4
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/from/ServiceParseTreeWalker.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarParser.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarRoundtrip.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/test/assertion/HelperTestAssertionGrammarComposer.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/assertion/TestAssertion.java
Labels: cla-present

#1033 new dayofweeknumber function
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/dateExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/date/testDayOfWeekNumber.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_routing.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/h2Extension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/sybaseIQExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/sqlFunction/testSqlFunctionsInMapping.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/query/testWithFunction.pure
Labels: cla-present
