Repository finos/legend-engine, pull requests merged in 2022-09, with the labels that each got.

#899 Ensure collection parameter and optional parameters with TimeZone are handled when null.
  legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
  legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/simpleRelationalService.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_execution.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/functions/tests/testIsEmpty1.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/processInOperation.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbExtension.pure
  legend-engine-xt-relationalStore-sqlserver-pure/src/main/resources/core_relational_sqlserver/relational/tests/dbSpecificTests/customSqlServerTests.pure
Labels: bug, cla-present

#890 Fix indentation for relational embedded data
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/data/HelperRelationalEmbeddedDataComposer.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalEmbeddedDataGrammarRoundtrip.java
Labels: bug, cla-present

#893 route context builder functions while building execution plan
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/extensions/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_main.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_routing.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
Labels: enhancement, cla-present

#902 Add support for defaultIfEmpty function in M2M mappings
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/collectionsLibrary.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/functionInMapping.pure
Labels: enhancement, cla-present

#854 Improve Error Categorisation
  legend-engine-executionPlan-execution-api/src/main/java/org/finos/legend/engine/plan/execution/api/ExecutePlan.java
  legend-engine-language-pure-compiler-api/src/main/java/org/finos/legend/engine/language/pure/compiler/api/Compile.java
  legend-engine-query-pure/src/main/java/org/finos/legend/engine/query/pure/api/Execute.java
  legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
  legend-engine-server/src/main/java/org/finos/legend/engine/server/ServerConfiguration.java
  legend-engine-server/src/main/java/org/finos/legend/engine/server/core/bundles/ErrorHandlingBundle.java
  legend-engine-server/src/main/java/org/finos/legend/engine/server/core/configuration/ErrorHandlingConfiguration.java
  legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig.json
  legend-engine-services-model-api/pom.xml
  legend-engine-services-model-api/src/main/java/org/finos/legend/engine/plan/execution/service/api/ServiceModelingApi.java
  legend-engine-services-model/src/main/java/org/finos/legend/engine/plan/execution/service/ServiceModeling.java
  legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/errorManagement/EngineException.java
  legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/errorManagement/ExceptionCategory.java
  legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/errorManagement/ExceptionCategoryData.java
  legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/logs/LoggingEventType.java
  legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/prometheus/MetricsHandler.java
  legend-engine-shared-core/src/main/resources/ExceptionData.json
  legend-engine-shared-core/src/test/java/org/finos/legend/engine/shared/core/operational/prometheus/TestErrorManagement.java
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ServiceTestRunner.java
Labels: cla-present

#904 Enable server to read configuration via environment variables
  legend-engine-server/pom.xml
  legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
  pom.xml
Labels: enhancement, cla-present

#908 Plan Platform Binding Refactor - Phase 1
  legend-engine-executionPlan-generation/src/main/java/org/finos/legend/engine/plan/platform/JavaPlatformBinder.java
  legend-engine-executionPlan-generation/src/main/java/org/finos/legend/engine/plan/platform/PlatformBinder.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/external/language/java/generation/conventions.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/javaRuntime/bindingLegendJavaPlatformBindingExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/javaRuntime/shared.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/graphFetchCommon.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/inMemory/graphFetchInMemory.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/inMemory/graphFetchStoreStreamReading.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/main.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/engineConventions.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/enginePlatformDependencies.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/shared/common.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/legendJavaPlatformBinding/bindPlanToLegendJavaPlatform.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/legendJavaPlatformBinding/legendJavaPlatformBinding.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/platformBinding/platformBinding.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/extensions/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/extensions/functions.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_18_0/invocations/execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_19_0/invocations/execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_20_0/invocations/execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/invocations/execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_22_0/invocations/execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_23_0/invocations/execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/invocations/execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/invocations/execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/invocations/execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/m2mLegendJavaPlatformBindingExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/executionPlan/javaRuntime/executionPlanNodes/platform/objectReference.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/executionPlan/javaRuntime/executionPlanNodes/platform/platform.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/executionPlan/javaRuntime/executionPlanNodes/platformMerge/platformMerge.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/executionPlan/javaRuntime/executionPlanNodes/platformUnion/platformUnion.pure
  legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestExecuteFunctionExecutionPlan.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/javaRuntime/relationalLegendJavaPlatformBindingExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/extensions/extension.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/javaRuntime/serviceStoreLegendJavaPlatformBindingExtension.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/extensions/extension.pure
Labels: enhancement, cla-present, not backwards compatible

#910 Add tests and connectionToString extension for modelStore
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/testUnion.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/storeContract.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/simpleObject.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/testUnitMeasure.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/router/tests/testRouting1.pure
Labels: enhancement, cla-present

#911 Adding initial GCP cloud-build config
  .gcp/cloud-build-release/cloudbuild.yaml
  .gcp/cloud-build-release/release.sh
Labels: cla-present

#912 Upgrade to legend-pure 3.6.1
  pom.xml
Labels: cla-present

#915 Fix parsing of strings in Mastery grammar
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/toPureGraph/HelperMasterRecordDefinitionBuilder.java
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/MasteryParseTreeWalker.java
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/to/HelperMasteryGrammarComposer.java
  legend-engine-xt-mastery-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/test/TestMasteryCompilationFromGrammar.java
Labels: bug, cla-present

#900 minor updates to ArtifactGenerationExtension
  legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
  legend-engine-language-pure-dsl-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/generation/extension/ArtifactGenerationExtension.java
  legend-engine-language-pure-dsl-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/generation/extension/ArtifactGenerationExtensionLoader.java
  legend-engine-xt-data-space-generation/pom.xml
  legend-engine-xt-data-space-generation/src/main/java/org/finos/legend/engine/generation/DataSpaceAnalyticsArtifactGenerationExtension.java
  legend-engine-xt-data-space-generation/src/test/java/org/finos/legend/engine/generation/TestDataSpaceAnalyticsArtifactGenerationExtension.java
  legend-engine-xt-data-space-generation/src/test/resources/models/DataspaceModel.pure
Labels: enhancement, cla-present

#916 Make M2M tests use defaultExtensions
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/legendJavaPlatformBinding/bindPlanToLegendJavaPlatform.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/autoMapping.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/chain/dataQualityChain.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/chain/filterChain.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/chain/parametersChain.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/chain/simpleChain.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/constraints.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/dataQuality.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/filterInMapping.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/functionInMapping.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/graphWithAssociations.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/graphWithoutAssociations.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/merge.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/multiStepFunctions.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/multiplicities.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/nilHandling.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/propertyUnion.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/qualifiedProperties.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/simpleObject.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/sourceAssociationRequiredByMapping.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/testExplosion.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/testUnitMeasure.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/toFromSameName.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/userFunctions.pure
Labels: bug, cla-present

#917 Move TypeInfo code out of Java platform binding
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/javaRuntime/descriptor.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/javaRuntime/shared.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/graphFetchCommon.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/inMemory/graphFetchInMemory.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/inMemory/graphFetchJson.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/inMemory/graphFetchStoreStreamReading.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/inMemory/graphFetchXml.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/main.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/langLibrary.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/metaLibrary.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/test/testUtils.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/shared/common.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/shared/constraints.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/shared/units.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/legendJavaPlatformBinding/bindPlanToLegendJavaPlatform.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/platformBinding/typeInfo/typeInfo.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/platformBinding/typeInfo/typeInfoTest.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/executionPlan/javaRuntime/executionPlanNodes/platform/objectReference.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/executionPlan/javaRuntime/executionPlanNodes/platform/platform.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/executionPlan/javaRuntime/executionPlanNodes/platform/serialize.pure
  legend-engine-xt-flatdata-pure/src/main/resources/core_external_format_flatdata/executionPlan/javaRuntime/externalize.pure
  legend-engine-xt-flatdata-pure/src/main/resources/core_external_format_flatdata/executionPlan/javaRuntime/internalize.pure
  legend-engine-xt-json-pure/src/main/resources/core_external_format_json/executionPlan/javaRuntime/externalize.pure
  legend-engine-xt-json-pure/src/main/resources/core_external_format_json/executionPlan/javaRuntime/internalize.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/javaRuntime/executionPlanNodes/graphFetch/graphFetchRelational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/javaRuntime/executionPlanNodes/relationalClassInstantiation/classResult.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/javaRuntime/executionPlanNodes/relationalClassInstantiation/relationalClassResult.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/javaRuntime/executionPlanNodes/limit/limit.pure
  legend-engine-xt-xml-pure/src/main/resources/core_external_format_xml/executionPlan/javaRuntime/internalize.pure
Labels: enhancement, cla-present

#923 Updating Dockerfile
  .github/workflows/docker.yml
  legend-engine-server/Dockerfile
Labels: cla-present

#924 Fix for javadoc that references classes produced by annotation processor (#921)
  legend-engine-xt-persistence-component/pom.xml
Labels: cla-present

#929 Remove deprecated platform binding code
  legend-engine-executionPlan-generation/src/main/java/org/finos/legend/engine/plan/platform/PlanPlatform.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/external/language/java/generation/conventions.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/extensions/extension.pure
Labels: enhancement, cla-present

#922 Isolate non-terminal group by with empty columns
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/functions/tests/testModelGroupBy.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tds/tests/testGroupBy.pure
Labels: bug, cla-present

#932 Remove recently added deprecated class usage
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/tests/executionPlanTests.pure
Labels: cla-present

#930 Adding modules legend-engine-xt-persistence-component-relational-memsql and legend-engine-xt-persistence-component-relational-snowflake
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/pom.xml
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/MemSqlSink.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/optimizer/LowerCaseOptimizer.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/optimizer/UpperCaseOptimizer.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sql/MemSqlDataTypeMapping.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sql/visitor/AlterVisitor.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sql/visitor/SQLUpdateVisitor.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sql/visitor/SchemaDefinitionVisitor.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sql/visitor/ShowVisitor.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sqldom/common/Clause.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sqldom/schema/Json.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sqldom/schemaops/statements/AlterTable.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sqldom/schemaops/statements/ShowCommand.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sqldom/schemaops/statements/UpdateStatement.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sqldom/tabletypes/GlobalTemporaryTableType.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/main/java/org/finos/legend/engine/persistence/components/relational/memsql/sqldom/tabletypes/ReferenceTableType.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/AppendOnlyTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/IngestModeTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/NontemporalDeltaTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/NontemporalSnapshotTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalDeltaTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalDeltaWithBatchIdTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalDeltaWithBatchTimeTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalSnapshotTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalSnapshotWithBatchIdTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalSnapshotWithBatchTimeTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/logicalplan/operations/AlterTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/logicalplan/operations/BaseTestUtils.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/logicalplan/operations/ShowTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/logicalplan/operations/UpdateTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/transformer/PlaceholderTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/pom.xml
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/SnowflakeSink.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/optmizer/LowerCaseOptimizer.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/optmizer/UpperCaseOptimizer.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/sql/SnowflakeDataTypeMapping.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/sql/visitor/AlterVisitor.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/sql/visitor/BatchEndTimestampVisitor.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/sql/visitor/SchemaDefinitionVisitor.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/sql/visitor/ShowVisitor.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/sql/visitor/TruncateVisitor.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/sqldom/schemaops/statements/AlterTable.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/sqldom/schemaops/statements/ShowCommand.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/BaseTestUtils.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/AppendOnlyTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/IngestModeTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/NontemporalDeltaMergeTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/NontemporalSnapshotTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalDeltaTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalSnapshotTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/logicalplan/operations/AlterTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/logicalplan/operations/CreateTableTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/logicalplan/operations/ShowTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/relational/snowflake/sql/DataTypeMappingTest.java
  legend-engine-xt-persistence-component/pom.xml
Labels: cla-present

#934 Fix java doc persistence comp
  legend-engine-xt-persistence-component/pom.xml
Labels: cla-present

#933 minor fix for dataspace analysis
  legend-engine-xt-data-space-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/DataSpaceGrammarComposerExtension.java
  legend-engine-xt-data-space-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestDataSpaceGrammarRoundtrip.java
  legend-engine-xt-diagram-api/src/test/java/org/finos/legend/engine/api/analytics/test/TestDiagramAnalyticsApi.java
  legend-engine-xt-diagram-api/src/test/resources/diagramAnalyticsTestDataWithMilestoning.json
  legend-engine-xt-diagram-pure/pom.xml
  legend-engine-xt-diagram-pure/src/main/resources/core_diagram/analytics/analytics.pure
Labels: bug, cla-present, approved

#937 skip java doc for persistence component
  legend-engine-xt-persistence-component/pom.xml
Labels: cla-present

#939 fix compiler for union subtypes
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ClassMappingSecondPassBuilder.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ClassMappingThirdPassBuilder.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PackageableElementFifthPassBuilder.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestMappingCompilationFromGrammar.java
  legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverage/analyticsTest.pure
Labels: cla-present

#938 Fix Maven Deploy workflow action
  .github/workflows/build.yml
  legend-engine-xt-persistence-component/pom.xml
Labels: cla-present

#941 Split deploy task into two commands to workaround maven-jar-plugin bug.
  .github/workflows/build.yml
Labels: cla-present

#940 New protocol v1_26_0
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/PureClientVersions.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_26_0/extension/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_26_0/models/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_26_0/models/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_26_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_26_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/extension/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/invocations/execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/invocations/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/invocations/testLoadModels.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/models/diagram.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/models/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/models/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/models/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/models/results.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/scan/buildBasePureModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/scan/buildPureModelAsText.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/scan/testBuildPureModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/transfers/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/transfers/mapping.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/transfers/store.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/transfers/valueSpecification.pure
  legend-engine-xt-avro-pure/src/main/resources/core_external_format_avro/protocol/protocol_v1_26_0.pure
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/protocol/protocol_v1_26_0.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_26_0/extension/extension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_26_0/extension/extension_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_26_0/invocations/execution_relation_executeInRelationalDb.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_26_0/invocations/execution_relational_execute.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_26_0/invocations/execution_relational_testConnection.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_26_0/invocations/execution_relational_testData.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_26_0/models/executionPlan_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_26_0/models/metamodel_connection.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_26_0/models/metamodel_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_26_0/models/results_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_26_0/models/testData_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_26_0/transfers/connection_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_26_0/transfers/metamodel_relational.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_26_0/extension/extension.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_26_0/extension/extension_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_26_0/models/executionPlan_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_26_0/models/metamodel_connection.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_26_0/models/metamodel_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_26_0/transfers/connection_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_26_0/transfers/metamodel_serviceStore.pure
Labels: enhancement, cla-present

#943 Add source data type info for constant columns
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalExtension.pure
Labels: bug, cla-present

#952 Revert "Add source data type info for constant columns (#943)"
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalExtension.pure
Labels: cla-present

#954 Fix error message in case of non-serializable model used with service store mapping
  legend-engine-xt-serviceStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperServiceStoreClassMappingBuilder.java
  legend-engine-xt-serviceStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceStoreMappingCompilationFromGrammar.java
Labels: cla-present

#944 Fix milestoning date propagation to sub select query
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/milestoning/tests/testBusinessDateMilestoning.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
Labels: bug, cla-present

#822 add setup based db tests
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/dbTestRunner/dynaFunctionTestRunner.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/dbTestRunner/shared.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/database/testValidNames.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/databricksTests.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/h2Tests.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/postgresTests.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/redshiftTests.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/snowflakeTests.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/ObjectNamingTests/testValidNames.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/aggregateFunctions/groupBy.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/aggregateFunctions/sliceTakeLimitDrop.pure
  legend-engine-xt-relationalStore-sqlserver-pure/src/main/resources/core_relational_sqlserver/relational/tests/dbSpecificTests/customSqlServerTests.pure
  legend-engine-xt-relationalStore-sqlserver-pure/src/main/resources/core_relational_sqlserver/relational/tests/dbSpecificTests/sqlServerTests.pure
Labels: cla-present

#958 Remove parser error listener subtypes.
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/ParserErrorListener.java
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/MasteryParserErrorListener.java
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/MasteryParserExtension.java
  legend-engine-xt-persistence-cloud-grammar/pom.xml
  legend-engine-xt-persistence-cloud-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/cloud/grammar/from/PersistenceCloudParserErrorListener.java
  legend-engine-xt-persistence-cloud-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/cloud/grammar/from/PersistenceCloudParserExtension.java
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/grammar/from/PersistenceParserErrorListener.java
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/grammar/from/PersistenceParserExtension.java
Labels: cla-present

#946 Make sure role on Snowflake DB spec is properly propagated to pure
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/DatasourceSpecificationBuilder.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalConnectionCompilationRoundtrip.java
Labels: bug, cla-present

#957 Adjust Parentheses for jsonToGrammar
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperValueSpecificationGrammarComposer.java
  legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java
Labels: cla-present

#959 decouple legend default flow provider
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/pom.xml
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/pom.xml
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/src/main/java/org/finos/legend/engine/authentication/flows/DatabricksWithApiTokenFlow.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/src/main/java/org/finos/legend/engine/authentication/flows/PostgresStaticWithUserPasswordFlow.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/src/main/java/org/finos/legend/engine/authentication/flows/RedshiftWithUserPasswordFlow.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/src/main/java/org/finos/legend/engine/authentication/flows/SnowflakeWithKeyPairFlow.java
  legend-engine-xt-relationalStore-sqlserver-execution-tests/src/test/java/org/finos/legend/engine/SqlServerRelationalTestServerInvoker.java
  legend-engine-xt-relationalStore-test-server/src/main/java/org/finos/legend/engine/server/test/shared/RelationalTestServer.java
  legend-engine-xt-relationalStore-test-server/src/test/java/org/finos/legend/engine/LegendDefaultRelationalTestServerInvoker.java
Labels: cla-present

#962 Fix/Add diagrams for testable/data models
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/data/diagram.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/test/diagram.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/metamodel/test/relationalTestDiagram.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/metamodel/testDataMetamodelDiagram.pure
Labels: cla-present

#942 Include default configuration files in Docker image
  legend-engine-server/Dockerfile
  legend-engine-server/src/main/resources/docker/config/config.json
  legend-engine-server/src/main/resources/docker/config/vault.properties
Labels: enhancement, cla-present

#935 Add quotes to column names containing special characters
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/defaultExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/sybaseIQExtension.pure
Labels: cla-present

#967 Tidy up persistence component and persistence test runner.
  legend-engine-extensions-collection-generation/pom.xml
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/TestBatch.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/test/testable.pure
  legend-engine-server/pom.xml
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/TestableRunner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-physical-plan/pom.xml
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/pom.xml
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-core/pom.xml
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/pom.xml
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/pom.xml
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/pom.xml
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/toPureGraph/HelperPersistenceBuilder.java
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/toPureGraph/PersistenceCompilerExtension.java
  legend-engine-xt-persistence-test-runner/pom.xml
  legend-engine-xt-persistence-test-runner/src/main/java/org/finos/legend/engine/testable/persistence/extension/PersistenceTestH2Connection.java
  legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/TestPersistenceBase.java
  legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/appendonly/TestAppendOnlyWithAllowDuplicates.java
  legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/appendonly/TestAppendOnlyWithFilterDuplicates.java
  legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/delta/bitemporal/TestPersistenceBitemporalDelta.java
  legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/delta/unitemporal/TestPersistenceUnitemporalDelta.java
  legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/snapshot/nontemporal/TestNonTemporalSnapshot.java
  legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/snapshot/unitemporal/TestPersistenceUnitemporalSnapshot.java
  pom.xml
Labels: cla-present

#966 fix dataSpace analytics
  legend-engine-external-shared/src/main/java/org/finos/legend/engine/external/shared/format/imports/PureModelContextDataGenerator.java
  legend-engine-xt-data-space-api/src/test/java/org/finos/legend/engine/api/analytics/test/TestDataSpaceAnalyticsApi.java
  legend-engine-xt-data-space-generation/src/test/java/org/finos/legend/engine/generation/TestDataSpaceAnalyticsArtifactGenerationExtension.java
Labels: bug, cla-present

#968 fix ID instantiation of some element to make `getUserPathForPackageableElement()` works properly
  legend-engine-language-pure-dsl-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/generation/compiler/toPureGraph/GenerationCompilerExtensionImpl.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/ServiceCompilerExtensionImpl.java
  legend-engine-xt-data-space-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/DataSpaceCompilerExtension.java
  legend-engine-xt-diagram-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/DiagramCompilerExtension.java
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/toPureGraph/MasteryCompilerExtension.java
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/toPureGraph/PersistenceCompilerExtension.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/RelationalCompilerExtension.java
  legend-engine-xt-serviceStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ServiceStoreCompilerExtension.java
  legend-engine-xt-text-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/TextCompilerExtension.java
Labels: cla-present

#955 association mapping implementation changes
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/inMemory/graphFetchInMemory.pure
Labels: enhancement, cla-present

#965 Fix milestoning date propagation bug
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperValueSpecificationBuilder.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/MilestoningDatePropagationContext.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/MilestoningDatePropagationHelper.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ProcessingContext.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/builder/CompositeFunctionExpressionBuilder.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestMilestonedPropertyUsageInFunctionExpresions.java
Labels: bug, cla-present

#976 Cleanup recent updates to persistence ingest library.
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/ingestmode/AppendOnlyAbstract.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/ingestmode/IngestModeVisitors.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/ingestmode/deduplication/DeduplicationStrategyVisitor.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/ingestmode/deduplication/DeduplicationStrategyVisitors.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/AppendOnlyPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/BitemporalDeltaPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-core/src/main/java/org/finos/legend/engine/persistence/components/relational/api/GeneratorResultAbstract.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-core/src/main/java/org/finos/legend/engine/persistence/components/relational/api/RelationalIngestorAbstract.java
Labels: cla-present

#980 Remove repeated call while merging generated java class
  legend-engine-pure-code-compiled-core/src/main/resources/core/external/language/java/metamodel_factories.pure
Labels: cla-present

#977 Adding GitHub action to trigger GCP build
  .gcp/cloud-build-release/cloudbuild.yaml
  .gcp/cloud-build-release/release.sh
  .gcp/cloud-build/build.sh
  .gcp/cloud-build/cloudbuild.yaml
  .github/workflows/trigger-gcp-build.yml
  legend-engine-server-integration-tests/src/test/java/org/finos/legend/engine/server/integration/tests/AbstractMiddleTierExecutionTest.java
Labels: enhancement, cla-present

#982 added select based db tests
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/postgresTests.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/redshiftTests.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/ObjectNamingTests/testValidNames.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/aggregateFunctions/groupBy.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/aggregateFunctions/windowColumn.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/selectSubClauses/filters.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/selectSubClauses/join.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/selectSubClauses/mixtureOfClauses.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/selectSubClauses/orderBy.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/selectSubClauses/union.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/selectSubClauses/view.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/dbSpecificTests/suite/sqlQueryTests/shared.pure
  legend-engine-xt-relationalStore-sqlserver-pure/src/main/resources/core_relational_sqlserver/relational/tests/dbSpecificTests/sqlServerTests.pure
Labels: cla-present

#987 turn off certain Github workflows in forks
  .github/workflows/database-postgresql-sql-generation-integration-test.yml
  .github/workflows/stale.yml
Labels: enhancement, cla-present, approved

#913 Use separate github env for release and allow manual running of integration tests
  .github/workflows/database-bigquery-integration-test.yml
  .github/workflows/database-databricks-integration-test.yml
  .github/workflows/database-databricks-sql-generation-integration-test.yml
  .github/workflows/database-mssqlserver-integration-test.yml
  .github/workflows/database-mssqlserver-sql-generation-integration-test.yml
  .github/workflows/database-postgresql-integration-test.yml
  .github/workflows/database-postgresql-sql-generation-integration-test.yml
  .github/workflows/database-redshift-integration-test.yml
  .github/workflows/database-redshift-sql-generation-integration-test.yml
  .github/workflows/database-snowflake-integration-test.yml
  .github/workflows/database-snowflake-sql-generation-integration-test.yml
Labels: cla-present

#983 added olapGroupBy in handlers
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
Labels: enhancement, cla-present

#981 fix multiplicity for pure platform expression node
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
Labels: bug, cla-present

#989 minor fixes for query API error response
  legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/api/ApplicationQueryException.java
Labels: bug

#985 Remove Embedded Store
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/extensions/functions.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetch_routing.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/mappingExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_cluster.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_main.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_printer.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/contract/storeContract.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/contract/storeContract.pure
Labels: cla-present

#993 Streaming GCP build logs
  .gcp/cloud-build/cloudbuild.yaml
  .github/workflows/trigger-gcp-build.yml
Labels: enhancement, cla-present

#995 fixed subtype problem and added tests
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/testSourceTreeCalc.pure
Labels: bug, cla-present
