Repository finos/legend-engine, pull requests merged in 2022-08, with the labels that each got.

#842 Middle tier authz - Postgres tests module
  legend-engine-server/config/config.json
  legend-engine-xt-relationalStore-postgres-execution-tests/pom.xml
  legend-engine-xt-relationalStore-postgres-execution-tests/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/postgres/test/PostgresTestContainerWrapper.java
  legend-engine-xt-relationalStore-postgres-execution-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/postgres/test/TestPostgresTestContainerWrapper.java
  pom.xml
Labels: cla-present, legend-stack-08-01-2022

#841 Middle tier authz - Credential
  legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestGrammarParser.java
  legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/identity/credential/middletier/MiddleTierUserPasswordCredential.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/MiddleTierUserNamePasswordAuthenticationStrategy.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/keys/MiddleTierUserNamePasswordAuthenticationStrategyKey.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/AuthenticationStrategyKeyGenerator.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/AuthenticationStrategyTransformer.java
  legend-engine-xt-relationalStore-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/authentication/AuthenticationStrategyLexerGrammar.g4
  legend-engine-xt-relationalStore-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/authentication/AuthenticationStrategyParserGrammar.g4
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/AuthenticationStrategyBuilder.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalGrammarParserExtension.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/authentication/AuthenticationStrategyParseTreeWalker.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperRelationalGrammarComposer.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalConnectionCompilationRoundtrip.java
  legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/RelationalProtocolExtension.java
  legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/authentication/MiddleTierUserNamePasswordAuthenticationStrategy.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/invocations/execution_relational_testConnection.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/models/metamodel_connection.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/transfers/connection_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/runtime/connection/authenticationStrategy.pure
Labels: cla-present, legend-stack-08-01-2022

#840 Middle tier authz - Runtime context injection
  legend-engine-executionPlan-execution-store-inMemory/src/main/java/org/finos/legend/engine/plan/execution/stores/inMemory/plugin/InMemoryStoreExecutionState.java
  legend-engine-executionPlan-execution-store-inMemory/src/test/java/org/finos/legend/engine/plan/execution/stores/inMemory/TestPlanExecutor.java
  legend-engine-executionPlan-execution-store-inMemory/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/FakeRelationalStoreExecutorBuilder.java
  legend-engine-executionPlan-execution-store-inMemory/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/FakeServiceStoreExecutorBuilder.java
  legend-engine-executionPlan-execution-store-inMemory/src/test/resources/plans/plan1.json
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/PlanExecutor.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/StoreExecutionState.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/src/main/java/org/finos/legend/engine/authentication/DatabaseAuthenticationFlow.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/src/main/java/org/finos/legend/engine/authentication/credential/CredentialSupplier.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/RelationalExecutor.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/blockConnection/BlockConnectionContext.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/ConnectionManagerSelector.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/RelationalConnectionManager.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalStoreExecutionState.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/TestRelationalConnectionManager.java
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/plugin/ServiceStoreExecutionState.java
Labels: cla-present, legend-stack-08-01-2022

#849 Add methods to generate identifiers for graph fetch cache keys
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/cache/graphFetch/GraphFetchCacheKey.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalGraphFetchUtils.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/graphFetch/cache/TestPlanExecutionWithGraphFetchCrossKeyCache.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/graphFetch/cache/TestPlanExecutionWithGraphFetchEqualityCache.java
Labels: cla-present, legend-stack-08-01-2022

#838 Add protocol models for externalize & internalize nodes
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocol/vX_X_X/models/executionPlan.pure
Labels: cla-present, legend-stack-08-01-2022

#836 fix a problem with data-space analytics
  legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
  legend-engine-external-shared/src/main/java/org/finos/legend/engine/external/shared/format/imports/PureModelContextDataGenerator.java
  legend-engine-xt-analytics-mapping-api/pom.xml
  legend-engine-xt-analytics-mapping-api/src/main/java/org/finos/legend/engine/api/analytics/MappingAnalytics.java
  legend-engine-xt-analytics-mapping-api/src/main/java/org/finos/legend/engine/api/analytics/MappingAnalyticsHelper.java
  legend-engine-xt-analytics-mapping-api/src/main/java/org/finos/legend/engine/api/analytics/model/MappedPropertyInfo.java
  legend-engine-xt-analytics-mapping-api/src/test/java/org/finos/legend/engine/api/analytics/test/TestMappingAnalyticsApi.java
  legend-engine-xt-analytics-mapping-api/src/test/resources/mappingModelCoverageAnalysisTestData.json
  legend-engine-xt-analytics-mapping-protocol/pom.xml
  legend-engine-xt-analytics-mapping-protocol/src/main/java/org/finos/legend/engine/protocol/analytics/model/EntityMappedProperty.java
  legend-engine-xt-analytics-mapping-protocol/src/main/java/org/finos/legend/engine/protocol/analytics/model/EnumMappedProperty.java
  legend-engine-xt-analytics-mapping-protocol/src/main/java/org/finos/legend/engine/protocol/analytics/model/MappedEntity.java
  legend-engine-xt-analytics-mapping-protocol/src/main/java/org/finos/legend/engine/protocol/analytics/model/MappedEntityInfo.java
  legend-engine-xt-analytics-mapping-protocol/src/main/java/org/finos/legend/engine/protocol/analytics/model/MappedProperty.java
  legend-engine-xt-analytics-mapping-protocol/src/main/java/org/finos/legend/engine/protocol/analytics/model/MappedPropertyInfo.java
  legend-engine-xt-analytics-mapping-protocol/src/main/java/org/finos/legend/engine/protocol/analytics/model/MappedPropertyType.java
  legend-engine-xt-analytics-mapping-protocol/src/main/java/org/finos/legend/engine/protocol/analytics/model/MappingModelCoverageAnalysisResult.java
  legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverage/analytics.pure
  legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverage/analyticsHelper.pure
  legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverage/analyticsTest.pure
  legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverage/mappedEntityBuilder.pure
  legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverage/serializer.pure
  legend-engine-xt-analytics-mapping-pure/src/main/resources/core_analytics_mapping/modelCoverage/utility.pure
  legend-engine-xt-data-space-api/pom.xml
  legend-engine-xt-data-space-api/src/main/java/org/finos/legend/engine/api/analytics/DataSpaceAnalytics.java
  legend-engine-xt-data-space-api/src/test/java/org/finos/legend/engine/api/analytics/test/TestDataSpaceAnalyticsApi.java
  legend-engine-xt-data-space-api/src/test/resources/dataSpaceAnalyticsWithSubstantialMappingTestData.json
  legend-engine-xt-data-space-compiler/pom.xml
  legend-engine-xt-data-space-compiler/src/main/java/org/finos/legend/engine/analytics/DataSpaceAnalyticsHelper.java
  legend-engine-xt-data-space-compiler/src/main/java/org/finos/legend/engine/analytics/model/DataSpaceAnalysisResult.java
  legend-engine-xt-diagram-api/src/main/java/org/finos/legend/engine/api/analytics/DiagramAnalytics.java
  legend-engine-xt-diagram-api/src/test/java/org/finos/legend/engine/api/analytics/test/TestDiagramAnalyticsApi.java
  legend-engine-xt-diagram-api/src/test/resources/diagramAnalyticsTestDataWithAssociation.json
  legend-engine-xt-diagram-api/src/test/resources/diagramAnalyticsTestDataWithDerivedProperties.json
  legend-engine-xt-diagram-api/src/test/resources/diagramAnalyticsTestDataWithShouldBeExcludedProfile.json
  legend-engine-xt-diagram-pure/src/main/resources/core_diagram/analytics/analytics.pure
  pom.xml
Labels: cla-present, legend-stack-08-01-2022

#848 Add CSV_FIXED serializationFormat
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/serialization/SerializationFormat.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/RelationalResult.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/serialization/RelationalResultToCSVSerializerWithTransformersApplied.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/execution/TestRelationalExecutor.java
Labels: cla-present, legend-stack-08-01-2022

#843 Fix FreeMarker in SQL generation as part of execution plan for property With Path.
  legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
  legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/simpleRelationalService.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/query/datePeriods.pure
Labels: cla-present

#847 Add protocol v1_24_0
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/PureClientVersions.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocol/v1_24_0/extension/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocol/v1_24_0/models/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocol/v1_24_0/models/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocol/v1_24_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocol/v1_24_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/test/langLibraryTests.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/extension/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/invocations/execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/invocations/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/invocations/testLoadModels.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/models/diagram.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/models/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/models/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/models/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/models/results.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/scan/buildBasePureModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/scan/buildPureModelAsText.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/scan/testBuildPureModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/transfers/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/transfers/mapping.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/transfers/store.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/transfers/valueSpecification.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/merge.pure
  legend-engine-xt-avro-pure/src/main/resources/core_external_format_avro/protocol/protocol_v1_24_0.pure
  legend-engine-xt-flatdata-pure/src/main/resources/core_external_format_flatdata/protocol_v1_24_0.pure
  legend-engine-xt-json-pure/src/main/resources/core_external_format_json/protocols/pure/v1_24_0/extension/extension_external_format_json.pure
  legend-engine-xt-json-pure/src/main/resources/core_external_format_json/protocols/pure/v1_24_0/models/executionPlan_external_format_json.pure
  legend-engine-xt-json-pure/src/main/resources/core_external_format_json/protocols/pure/v1_24_0/transfers/executionPlan_external_format_json.pure
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/protocol/protocol_v1_24_0.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_24_0/extension/extension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_24_0/extension/extension_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_24_0/invocations/execution_relation_executeInRelationalDb.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_24_0/invocations/execution_relational_execute.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_24_0/invocations/execution_relational_testConnection.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_24_0/invocations/execution_relational_testData.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_24_0/models/executionPlan_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_24_0/models/metamodel_connection.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_24_0/models/metamodel_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_24_0/models/results_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_24_0/models/testData_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_24_0/transfers/connection_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_24_0/transfers/metamodel_relational.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_24_0/extension/extension.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_24_0/extension/extension_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_24_0/models/executionPlan_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_24_0/models/metamodel_connection.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_24_0/models/metamodel_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_24_0/transfers/connection_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_24_0/transfers/metamodel_serviceStore.pure
  legend-engine-xt-xml-pure/src/main/resources/core_external_format_xml/protocol_v1_24_0.pure
Labels: cla-present, legend-stack-08-01-2022, protocol-release

#852 Continue cleaning Extensions
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_print.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/extensions.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/extensions/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/extensions/functions.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetchExecutionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/mappingExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/modelToModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/router_extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/runtime/runtimeExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/store/storeContract.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/storeContract.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/contract/storeContract.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/extensions/extension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/testDataGeneration/testDataGeneration.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/contract/storeContract.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan_generation.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/extensions/extension.pure
Labels: cla-present

#861 Remove unused mapping adaptor code
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/inMemory/graphFetchInMemory.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/shared/mappingAdaptor.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/extensions/extension.pure
Labels: cla-present

#871 Add stale bot automation
  .github/stale.yml
Labels: cla-present

#846 Standardize compile error handling to avoid infinite loop when serializing
  legend-engine-language-pure-compiler-api/pom.xml
  legend-engine-language-pure-compiler-api/src/main/java/org/finos/legend/engine/language/pure/compiler/api/Compile.java
  legend-engine-language-pure-compiler-api/src/test/java/org/finos/legend/engine/language/pure/compiler/api/test/TestCompileApi.java
  legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/errorManagement/ExceptionError.java
Labels: cla-present

#857 Rename CSV_FIXED to CSV_TRANSFORMED
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/serialization/SerializationFormat.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/RelationalResult.java
Labels: cla-present

#865 refactor bigquery execution
  legend-engine-server/pom.xml
  legend-engine-xt-relationalStore-bigquery-execution/pom.xml
  legend-engine-xt-relationalStore-bigquery-execution/src/main/java/org/finos/legend/engine/authentication/flows/BigQueryWithGCPApplicationDefaultCredentialsFlow.java
  legend-engine-xt-relationalStore-bigquery-execution/src/main/java/org/finos/legend/engine/authentication/flows/BigQueryWithGCPWorkloadIdentityFederationFlow.java
  legend-engine-xt-relationalStore-bigquery-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/BigQueryConnectionExtension.java
  legend-engine-xt-relationalStore-bigquery-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/bigquery/BigQueryCommands.java
  legend-engine-xt-relationalStore-bigquery-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/bigquery/BigQueryDriver.java
  legend-engine-xt-relationalStore-bigquery-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/bigquery/BigQueryManager.java
  legend-engine-xt-relationalStore-bigquery-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/BigQueryDataSourceSpecification.java
  legend-engine-xt-relationalStore-bigquery-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/keys/BigQueryDataSourceSpecificationKey.java
  legend-engine-xt-relationalStore-bigquery-execution/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.RelationalConnectionExtension
  legend-engine-xt-relationalStore-bigquery-execution/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.connection.ConnectionExtension
  legend-engine-xt-relationalStore-bigquery-execution/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.connection.manager.strategic.StrategicConnectionExtension
  legend-engine-xt-relationalStore-bigquery-grammar/pom.xml
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/BigQueryLexerGrammar.g4
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/BigQueryParserGrammar.g4
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/BigQueryCompilerExtension.java
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/BigQueryGrammarParserExtension.java
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/BigQueryGrammarComposerExtension.java
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.compiler.toPureGraph.extension.CompilerExtension
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.grammar.from.IRelationalGrammarParserExtension
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.grammar.to.extension.PureGrammarComposerExtension
  legend-engine-xt-relationalStore-bigquery-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestBigQueryConnectionGrammarRoundtrip.java
  legend-engine-xt-relationalStore-bigquery-protocol/pom.xml
  legend-engine-xt-relationalStore-bigquery-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/BigQueryProtocolExtension.java
  legend-engine-xt-relationalStore-bigquery-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/specification/BigQueryDatasourceSpecification.java
  legend-engine-xt-relationalStore-bigquery-protocol/src/main/resources/META-INF/services/org.finos.legend.engine.protocol.pure.v1.extension.PureProtocolExtension
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/pom.xml
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/main/java/org/finos/legend/engine/authentication/LegendDefaultDatabaseAuthenticationFlowProvider.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/main/java/org/finos/legend/engine/authentication/LegendDefaultDatabaseAuthenticationFlowProviderConfiguration.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/test/java/org/finos/legend/engine/authentication/flows/ExternalIntegration_TestBigQueryWithGCPWorkloadIdentityFederationFlow.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/src/main/java/org/finos/legend/engine/authentication/cloud/AWSConfig.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/src/main/java/org/finos/legend/engine/authentication/cloud/GCPWorkloadConfig.java
  legend-engine-xt-relationalStore-executionPlan-connection-tests/pom.xml
  legend-engine-xt-relationalStore-executionPlan-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProvider_BigQuery.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/DatabaseManager.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/bigquery/BigQueryConnectionExtension.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.connection.ConnectionExtension
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/StreamResultToTempTableVisitor.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/DataSourceSpecificationKeyGenerator.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/DataSourceSpecificationTransformer.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/RelationalConnectionManager.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/StrategicConnectionExtension.java
  legend-engine-xt-relationalStore-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/datasource/DataSourceSpecificationLexerGrammar.g4
  legend-engine-xt-relationalStore-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/datasource/DataSourceSpecificationParserGrammar.g4
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/DatasourceSpecificationBuilder.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/IRelationalCompilerExtension.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/IRelationalGrammarParserExtension.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalGrammarParserExtension.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/datasource/DataSourceSpecificationParseTreeWalker.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperRelationalGrammarComposer.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalConnectionGrammarRoundtrip.java
  legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/RelationalProtocolExtension.java
  pom.xml
Labels: cla-present

#874 Revert "refactor bigquery execution"
  legend-engine-server/pom.xml
  legend-engine-xt-relationalStore-bigquery-execution/pom.xml
  legend-engine-xt-relationalStore-bigquery-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/BigQueryConnectionExtension.java
  legend-engine-xt-relationalStore-bigquery-execution/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.RelationalConnectionExtension
  legend-engine-xt-relationalStore-bigquery-execution/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.connection.ConnectionExtension
  legend-engine-xt-relationalStore-bigquery-execution/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.connection.manager.strategic.StrategicConnectionExtension
  legend-engine-xt-relationalStore-bigquery-grammar/pom.xml
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/BigQueryLexerGrammar.g4
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/BigQueryParserGrammar.g4
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/BigQueryCompilerExtension.java
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/BigQueryGrammarParserExtension.java
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/BigQueryGrammarComposerExtension.java
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.compiler.toPureGraph.extension.CompilerExtension
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.grammar.from.IRelationalGrammarParserExtension
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.grammar.to.extension.PureGrammarComposerExtension
  legend-engine-xt-relationalStore-bigquery-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestBigQueryConnectionGrammarRoundtrip.java
  legend-engine-xt-relationalStore-bigquery-protocol/pom.xml
  legend-engine-xt-relationalStore-bigquery-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/BigQueryProtocolExtension.java
  legend-engine-xt-relationalStore-bigquery-protocol/src/main/resources/META-INF/services/org.finos.legend.engine.protocol.pure.v1.extension.PureProtocolExtension
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/pom.xml
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/main/java/org/finos/legend/engine/authentication/LegendDefaultDatabaseAuthenticationFlowProvider.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/main/java/org/finos/legend/engine/authentication/LegendDefaultDatabaseAuthenticationFlowProviderConfiguration.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/main/java/org/finos/legend/engine/authentication/flows/BigQueryWithGCPApplicationDefaultCredentialsFlow.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/main/java/org/finos/legend/engine/authentication/flows/BigQueryWithGCPWorkloadIdentityFederationFlow.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/test/java/org/finos/legend/engine/authentication/flows/ExternalIntegration_TestBigQueryWithGCPWorkloadIdentityFederationFlow.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/src/main/java/org/finos/legend/engine/authentication/cloud/AWSConfig.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/src/main/java/org/finos/legend/engine/authentication/cloud/GCPWorkloadConfig.java
  legend-engine-xt-relationalStore-executionPlan-connection-tests/pom.xml
  legend-engine-xt-relationalStore-executionPlan-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProvider_BigQuery.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/DatabaseManager.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/bigquery/BigQueryCommands.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/bigquery/BigQueryConnectionExtension.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/bigquery/BigQueryDriver.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/bigquery/BigQueryManager.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/BigQueryDataSourceSpecification.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/keys/BigQueryDataSourceSpecificationKey.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.connection.ConnectionExtension
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/StreamResultToTempTableVisitor.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/DataSourceSpecificationKeyGenerator.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/DataSourceSpecificationTransformer.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/RelationalConnectionManager.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/StrategicConnectionExtension.java
  legend-engine-xt-relationalStore-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/datasource/DataSourceSpecificationLexerGrammar.g4
  legend-engine-xt-relationalStore-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/datasource/DataSourceSpecificationParserGrammar.g4
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/DatasourceSpecificationBuilder.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/IRelationalCompilerExtension.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/IRelationalGrammarParserExtension.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalGrammarParserExtension.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/datasource/DataSourceSpecificationParseTreeWalker.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperRelationalGrammarComposer.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalConnectionGrammarRoundtrip.java
  legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/RelationalProtocolExtension.java
  legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/specification/BigQueryDatasourceSpecification.java
  pom.xml
Labels: cla-present

#875 Upgrade to Pure 3.4.0
  pom.xml
Labels: cla-present

#872 Allow relational XStore keys to be mapped to RelOpWithJoins
  legend-engine-server/src/test/java/org/finos/legend/engine/server/test/pureClient/stores/Test_Relational_UsingPureClientTestSuite.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/relationalGraphFetch.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/testCrossDatabaseGraphFetch.pure
Labels: cla-present

#878 Remove deprecated mappingAdaptor extensions
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/extensions/extension.pure
Labels: cla-present

#867 Create and enable protocol version v1_25_0
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/PureClientVersions.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocol/v1_25_0/extension/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocol/v1_25_0/models/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocol/v1_25_0/models/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocol/v1_25_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocol/v1_25_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/extension/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/invocations/execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/invocations/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/invocations/testLoadModels.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/models/diagram.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/models/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/models/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/models/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/models/results.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/scan/buildBasePureModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/scan/buildPureModelAsText.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/scan/testBuildPureModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/transfers/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/transfers/mapping.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/transfers/store.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/transfers/valueSpecification.pure
  legend-engine-xt-avro-pure/src/main/resources/core_external_format_avro/protocol/protocol_v1_25_0.pure
  legend-engine-xt-flatdata-pure/src/main/resources/core_external_format_flatdata/protocol_v1_25_0.pure
  legend-engine-xt-json-pure/src/main/resources/core_external_format_json/protocols/pure/v1_25_0/extension/extension_external_format_json.pure
  legend-engine-xt-json-pure/src/main/resources/core_external_format_json/protocols/pure/v1_25_0/models/executionPlan_external_format_json.pure
  legend-engine-xt-json-pure/src/main/resources/core_external_format_json/protocols/pure/v1_25_0/transfers/executionPlan_external_format_json.pure
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/protocol/protocol_v1_25_0.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_25_0/extension/extension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_25_0/extension/extension_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_25_0/invocations/execution_relation_executeInRelationalDb.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_25_0/invocations/execution_relational_execute.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_25_0/invocations/execution_relational_testConnection.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_25_0/invocations/execution_relational_testData.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_25_0/models/executionPlan_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_25_0/models/metamodel_connection.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_25_0/models/metamodel_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_25_0/models/results_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_25_0/models/testData_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_25_0/transfers/connection_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_25_0/transfers/metamodel_relational.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_25_0/extension/extension.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_25_0/extension/extension_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_25_0/models/executionPlan_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_25_0/models/metamodel_connection.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_25_0/models/metamodel_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_25_0/transfers/connection_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_25_0/transfers/metamodel_serviceStore.pure
  legend-engine-xt-xml-pure/src/main/resources/core_external_format_xml/protocol_v1_25_0.pure
Labels: cla-present

#880 Update CODEOWNERS
  CODEOWNERS
Labels: cla-present

#821 Refactor union and merge to use specialized nodes
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/ExecutionNodeExecutor.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/ExecutionNode.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/PlatformMergeExecutionNode.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/PlatformUnionExecutionNode.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_diagram.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_print.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/main.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/enginePlatformDependencies.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetchExecutionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/modelToModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/executionPlan/executionPlan_generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/executionPlan/javaRuntime/executionPlanNodes/platform/platform.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/executionPlan/javaRuntime/executionPlanNodes/platformMerge/platformMerge.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/platform/executionPlan/javaRuntime/executionPlanNodes/platformUnion/platformUnion.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/testCrossStoreUnion.pure
Labels: enhancement, cla-present

#672 Invalidate usage of new function call in mapping
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/validator/MappingValidator.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestMappingCompilationFromGrammar.java
Labels: bug, cla-present

#885 Post process groupBy, havingOperation and orderBy
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/postProcessor.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/tests/testPostProcessor.pure
Labels: bug, cla-present

#850 Add support for 'dayOfMonth' function in SybaseIQ
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/sybaseIQExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/transform/fromPure/tests/testToSQLString.pure
Labels: enhancement, cla-present

#882 refactor bigquery execution
  legend-engine-extensions-collection-generation/pom.xml
  legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
  legend-engine-server/pom.xml
  legend-engine-xt-relationalStore-bigquery-execution/pom.xml
  legend-engine-xt-relationalStore-bigquery-execution/src/main/java/org/finos/legend/engine/authentication/flows/BigQueryWithGCPApplicationDefaultCredentialsFlow.java
  legend-engine-xt-relationalStore-bigquery-execution/src/main/java/org/finos/legend/engine/authentication/flows/BigQueryWithGCPWorkloadIdentityFederationFlow.java
  legend-engine-xt-relationalStore-bigquery-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/BigQueryConnectionExtension.java
  legend-engine-xt-relationalStore-bigquery-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/bigquery/BigQueryCommands.java
  legend-engine-xt-relationalStore-bigquery-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/bigquery/BigQueryDriver.java
  legend-engine-xt-relationalStore-bigquery-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/bigquery/BigQueryManager.java
  legend-engine-xt-relationalStore-bigquery-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/BigQueryDataSourceSpecification.java
  legend-engine-xt-relationalStore-bigquery-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/keys/BigQueryDataSourceSpecificationKey.java
  legend-engine-xt-relationalStore-bigquery-execution/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.RelationalConnectionExtension
  legend-engine-xt-relationalStore-bigquery-execution/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.connection.ConnectionExtension
  legend-engine-xt-relationalStore-bigquery-execution/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.connection.manager.strategic.StrategicConnectionExtension
  legend-engine-xt-relationalStore-bigquery-grammar/pom.xml
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/BigQueryLexerGrammar.g4
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/BigQueryParserGrammar.g4
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/BigQueryCompilerExtension.java
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/BigQueryGrammarParserExtension.java
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/BigQueryGrammarComposerExtension.java
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.compiler.toPureGraph.extension.CompilerExtension
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.grammar.from.IRelationalGrammarParserExtension
  legend-engine-xt-relationalStore-bigquery-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.grammar.to.extension.PureGrammarComposerExtension
  legend-engine-xt-relationalStore-bigquery-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestBigQueryConnectionGrammarRoundtrip.java
  legend-engine-xt-relationalStore-bigquery-protocol/pom.xml
  legend-engine-xt-relationalStore-bigquery-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/BigQueryProtocolExtension.java
  legend-engine-xt-relationalStore-bigquery-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/specification/BigQueryDatasourceSpecification.java
  legend-engine-xt-relationalStore-bigquery-protocol/src/main/resources/META-INF/services/org.finos.legend.engine.protocol.pure.v1.extension.PureProtocolExtension
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/pom.xml
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/main/java/org/finos/legend/engine/authentication/LegendDefaultDatabaseAuthenticationFlowProvider.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/main/java/org/finos/legend/engine/authentication/LegendDefaultDatabaseAuthenticationFlowProviderConfiguration.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/test/java/org/finos/legend/engine/authentication/flows/ExternalIntegration_TestBigQueryWithGCPWorkloadIdentityFederationFlow.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/src/main/java/org/finos/legend/engine/authentication/cloud/AWSConfig.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/src/main/java/org/finos/legend/engine/authentication/cloud/GCPWorkloadConfig.java
  legend-engine-xt-relationalStore-executionPlan-connection-tests/pom.xml
  legend-engine-xt-relationalStore-executionPlan-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProvider_BigQuery.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/DatabaseManager.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/bigquery/BigQueryConnectionExtension.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.connection.ConnectionExtension
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/StreamResultToTempTableVisitor.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/DataSourceSpecificationKeyGenerator.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/DataSourceSpecificationTransformer.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/RelationalConnectionManager.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/manager/strategic/StrategicConnectionExtension.java
  legend-engine-xt-relationalStore-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/datasource/DataSourceSpecificationLexerGrammar.g4
  legend-engine-xt-relationalStore-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/datasource/DataSourceSpecificationParserGrammar.g4
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/DatasourceSpecificationBuilder.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/IRelationalCompilerExtension.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/IRelationalGrammarParserExtension.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/RelationalGrammarParserExtension.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/datasource/DataSourceSpecificationParseTreeWalker.java
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperRelationalGrammarComposer.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalConnectionGrammarRoundtrip.java
  legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/RelationalProtocolExtension.java
  pom.xml
Labels: enhancement, cla-present, not backwards compatible

#883 Rebase to 3.13.1 and re-apply all changes to add Mastery to Engine
  legend-engine-extensions-collection-generation/pom.xml
  legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
  legend-engine-pure-ide-light/src/main/java/org/finos/legend/engine/ide/PureIDELight.java
  legend-engine-server/pom.xml
  legend-engine-xt-mastery-grammar/pom.xml
  legend-engine-xt-mastery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/MasteryLexerGrammar.g4
  legend-engine-xt-mastery-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/MasteryParserGrammar.g4
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/toPureGraph/HelperMasterRecordDefinitionBuilder.java
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/toPureGraph/MasteryCompilerExtension.java
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/MasteryParseTreeWalker.java
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/MasteryParserErrorListener.java
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/from/MasteryParserExtension.java
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/to/HelperMasteryGrammarComposer.java
  legend-engine-xt-mastery-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/to/MasteryGrammarComposerExtension.java
  legend-engine-xt-mastery-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.compiler.toPureGraph.extension.CompilerExtension
  legend-engine-xt-mastery-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.grammar.from.extension.PureGrammarParserExtension
  legend-engine-xt-mastery-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.grammar.to.extension.PureGrammarComposerExtension
  legend-engine-xt-mastery-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/test/TestMasteryCompilationFromGrammar.java
  legend-engine-xt-mastery-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/test/TestMasteryGrammarParser.java
  legend-engine-xt-mastery-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/mastery/grammar/test/TestMasteryGrammarRoundtrip.java
  legend-engine-xt-mastery-protocol/pom.xml
  legend-engine-xt-mastery-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/MasteryProtocolExtension.java
  legend-engine-xt-mastery-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mastery/MasterRecordDefinition.java
  legend-engine-xt-mastery-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mastery/RecordSource.java
  legend-engine-xt-mastery-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mastery/RecordSourcePartition.java
  legend-engine-xt-mastery-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mastery/RecordSourceStatus.java
  legend-engine-xt-mastery-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mastery/RecordSourceVisitor.java
  legend-engine-xt-mastery-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mastery/Tagable.java
  legend-engine-xt-mastery-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mastery/identity/IdentityResolution.java
  legend-engine-xt-mastery-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mastery/identity/IdentityResolutionVisitor.java
  legend-engine-xt-mastery-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mastery/identity/ResolutionKeyType.java
  legend-engine-xt-mastery-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mastery/identity/ResolutionQuery.java
  legend-engine-xt-mastery-protocol/src/main/resources/META-INF/services/org.finos.legend.engine.protocol.pure.v1.extension.PureProtocolExtension
  legend-engine-xt-mastery-pure/pom.xml
  legend-engine-xt-mastery-pure/src/main/java/org/finos/legend/pure/code/core/CoreMasteryCodeRepositoryProvider.java
  legend-engine-xt-mastery-pure/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.filesystem.repository.CodeRepositoryProvider
  legend-engine-xt-mastery-pure/src/main/resources/core_mastery.definition.json
  legend-engine-xt-mastery-pure/src/main/resources/core_mastery/mastery/metamodel.pure
  legend-engine-xt-mastery-pure/src/main/resources/core_mastery/mastery/metamodel_diagram.pure
  legend-engine-xt-mastery-pure/src/test/java/org/finos/legend/pure/code/core/mastery/Test_Pure_Mastery.java
  pom.xml
Labels: enhancement, cla-present

#833 artifact generation + dataspace impl
  legend-engine-executionPlan-execution-authorizer/pom.xml
  legend-engine-extensions-collection-generation/pom.xml
  legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
  legend-engine-language-pure-dsl-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/generation/extension/Artifact.java
  legend-engine-language-pure-dsl-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/generation/extension/ArtifactGenerationExtension.java
  legend-engine-server-integration-tests/pom.xml
  legend-engine-xt-data-space-api/pom.xml
  legend-engine-xt-data-space-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperDataSpaceBuilder.java
  legend-engine-xt-data-space-generation/pom.xml
  legend-engine-xt-data-space-generation/src/main/java/org/finos/legend/engine/generation/DataSpaceAnalyticsArtifactGenerationExtension.java
  legend-engine-xt-data-space-generation/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.dsl.generation.extension.ArtifactGenerationExtension
  legend-engine-xt-mastery-grammar/pom.xml
  legend-engine-xt-mastery-pure/pom.xml
  legend-engine-xt-persistence-cloud-grammar/pom.xml
  legend-engine-xt-relationalStore-executionPlan-authorizer/pom.xml
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/pom.xml
  legend-engine-xt-relationalStore-executionPlan/pom.xml
  pom.xml
Labels: bug, enhancement, cla-present

#889 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-present

#888 Update stale bot settings
  .github/stale.yml
Labels: cla-present

#891 Revert "Add quoting for identifier with spaces (#835)"
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/defaultExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/prestoExtension.pure
Labels: cla-present

#897 Revert "Invalidate usage of new function call in mapping (#672)"
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/validator/MappingValidator.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestMappingCompilationFromGrammar.java
Labels: cla-present
