Repository finos/legend-engine, pull requests merged in 2023-03, with the labels that each got.

#1451 Revert IDELight port change
  legend-engine-pure-ide-light/src/main/resources/ideLightConfig.json
Labels: cla-present

#1452 Temporarily remove flaky assert
  legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/concurrent/TestConcurrentExecutionNodeExecution.java
Labels: cla-present

#1453 Ignore Snowflake Key Pair tests
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/test/java/org/finos/legend/engine/authentication/flows/TestSnowflakeWithKeyPairFlow.java
Labels: cla-present

#1449 Add logic for returning default incoming credential in CredentialProvider
  legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/authentication/credentialprovider/CredentialProvider.java
  legend-engine-xt-authentication-implementation-core/src/test/java/org/finos/legend/authentication/TestDefaultCredentialCreation.java
Labels: cla-present

#1412 Integrate credential provider with service store execution
  legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
  legend-engine-service-post-validation-runner/pom.xml
  legend-engine-service-post-validation-runner/src/main/java/org/finos/legend/engine/service/post/validation/runner/LegendServicePostValidationRunner.java
  legend-engine-service-post-validation-runner/src/main/java/org/finos/legend/engine/service/post/validation/runner/ServicePostValidationRunner.java
  legend-engine-service-post-validation-runner/src/test/java/org/finos/legend/engine/service/post/validation/runner/TestLegendServicePostValidationRunner.java
  legend-engine-services-model-api/src/main/java/org/finos/legend/engine/plan/execution/service/api/ServiceModelingApi.java
  legend-engine-services-model/pom.xml
  legend-engine-services-model/src/main/java/org/finos/legend/engine/plan/execution/service/ServiceModeling.java
  legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/connection/ConnectionProvider.java
  legend-engine-xt-serviceStore-executionPlan/pom.xml
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/IServiceStoreExecutionExtension.java
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/ServiceExecutor.java
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/ServiceStoreExecutionExtension.java
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/auth/HttpConnectionBuilder.java
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/auth/ServiceStoreAuthenticationSpecification.java
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/auth/ServiceStoreConnectionProvider.java
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/auth/ServiceStoreConnectionSpecification.java
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/plugin/ServiceExecutionNodeExecutor.java
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/plugin/ServiceStore.java
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/plugin/ServiceStoreExecutionConfiguration.java
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/plugin/ServiceStoreExecutionState.java
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/plugin/ServiceStoreExecutor.java
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/plugin/ServiceStoreExecutorBuilder.java
  legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/utils/ServiceStoreTestUtils.java
  legend-engine-xt-serviceStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/IServiceStoreCompilerExtension.java
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/vX_X_X/extension/extension_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/vX_X_X/models/executionPlan_serviceStore.pure
  legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/execute/SqlExecute.java
Labels: cla-present

#1458 Add Supported Function for OLAP
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/contract/storeContract.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tds/tests/testCanRouteWrappedFunctions.pure
Labels: cla-present

#1416 update alloy metadata config to point to correct legend depot port and prefix
  legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig.json
  legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withMetadataFromIDELight.json
Labels: cla-present

#1461 Relax Access modifier for modelLoaders
  legend-engine-language-pure-modelManager/src/main/java/org/finos/legend/engine/language/pure/modelManager/ModelManager.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tds/tests/testCanRouteWrappedFunctions.pure
Labels: cla-present

#1467 key exp java gen bug fix
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/valueSpecification.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/nilHandling.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchInMemory.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/langLibrary.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/shared/common.pure
Labels: cla-present

#1468 Preeval - handle constants in AggregateValue automaps
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/preeval.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/tests.pure
Labels: cla-present

#1471 Fix source tree calculation in presence of match/instanceOf
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/platformBinding/typeInfo/typeInfo.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/platformBinding/typeInfo/typeInfoTest.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/scan/buildBasePureModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/scan/buildBasePureModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/graphWithSubTypes/testOnSourceRoot.pure
  legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestM2MGrammarCompileAndExecute.java
Labels: cla-present

#1469 add query stats api
  legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/api/ApplicationQuery.java
  legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/api/QueryStoreManager.java
  legend-engine-application-query/src/main/java/org/finos/legend/engine/application/query/model/QueryStoreStats.java
  legend-engine-application-query/src/test/java/org/finos/legend/engine/application/query/api/TestQueryStoreManager.java
  legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/logs/LoggingEventType.java
Labels: cla-present

#1474 GrpahQL - Introspection for Date,DateTime,Decimal,StrictDate
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/introspection/fromPure_Introspection.pure
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/transformation/tests/testIntrospectionQuery.pure
Labels: cla-present

#1478 disable usage of large runner on default branch of forks
  .github/workflows/build.yml
Labels: cla-present

#1481 Skip build job on default branch of forks
  .github/workflows/build.yml
Labels: cla-present

#1466 renaming test data in mapping test suites
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperMappingBuilder.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/MappingParseTreeWalker.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperMappingGrammarComposer.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/mappingTest/MappingStoreTestData.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/mappingTest/MappingTestSuite.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/metamodel.pure
  legend-engine-test-runner-mapping/src/main/java/org/finos/legend/engine/testable/mapping/extension/MappingTestRunner.java
Labels: enhancement, cla-present

#1450 Persistence Component: Fix for empty table check SQL for snowflake
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/logicalplan/LogicalPlanFactory.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/logicalplan/datasets/SelectionAbstract.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/main/java/org/finos/legend/engine/persistence/components/relational/ansi/sql/visitors/SelectionVisitor.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/logicalplan/operations/SelectTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/util/LogicalPlanFactoryTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-core/src/main/java/org/finos/legend/engine/persistence/components/relational/api/RelationalIngestorAbstract.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-core/src/main/java/org/finos/legend/engine/persistence/components/relational/sqldom/common/Clause.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-core/src/main/java/org/finos/legend/engine/persistence/components/relational/sqldom/schemaops/statements/SelectStatement.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-core/src/test/java/org/finos/legend/engine/persistence/components/relational/sqldom/schemaops/SelectExpressionTest.java
Labels: cla-present

#1483 Rename sample JUnit test reports
  legend-engine-test-reports/src/test/resources/example-reports/postgresql/sanple-postgres-report.xml
  legend-engine-test-reports/src/test/resources/example-reports/snowflake/sanple-snowflake-report.xml
Labels: cla-present

#1484 Update legend-pure to 4.3.0
  pom.xml
Labels: cla-present

#1422 Fix java generation of enum with special characters
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/dataQuality/EnforcementLevel.java
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/dataQuality/RuleType.java
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/date/DayOfWeek.java
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/date/DurationUnit.java
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/date/Month.java
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/date/Quarter.java
  legend-engine-external-shared-format-runtime/src/test/java/org/finos/legend/engine/external/shared/runtime/fixtures/firmModel/AddressType.java
  legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestM2MGrammarCompileAndExecute.java
  legend-engine-xt-flatdata-javaPlatformBinding-pure/src/main/resources/core_external_format_flatdata_java_platform_binding/legendJavaPlatformBinding/internalize.pure
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/expressionGeneration.pure
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/metamodel_factories.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchInMemory.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchJson.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchXml.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/jacksonSupport.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/metaLibrary.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/pureDateLibraryTests.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/platform/executionPlanNodes/platform/serialize.pure
  legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/graphFetchRelational.pure
  legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/relationalClassInstantiation/relationalClassResult.pure
  legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/executionPlanTest.pure
  legend-engine-xt-xml-runtime/src/main/java/org/finos/legend/engine/external/format/xml/read/valueProcessors/AddEnumToObject.java
Labels: cla-present

#1482 GraphQL caching fix
  legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/operational/logs/LoggingEventType.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecute.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/model/GraphQLCachableVisitorHelper.java
  legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLAPI.java
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Project1_Workspace2.pure
Labels: cla-present

#1393 Delete Legacy Flatdata Serialize/Deserialize nodes
  legend-engine-extensions-collection-execution/src/test/java/org/finos/legend/engine/extensions/collection/execution/TestExtensions.java
  legend-engine-extensions-collection-generation/pom.xml
  legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
  legend-engine-xt-flatdata-protocol/pom.xml
  legend-engine-xt-flatdata-protocol/src/main/java/org/finos/legend/engine/external/format/flatdata/FlatDataProtocolExtension.java
  legend-engine-xt-flatdata-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/external/format/flatdata/FlatDataDeserializeExecutionNode.java
  legend-engine-xt-flatdata-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/external/format/flatdata/FlatDataSerializeExecutionNode.java
  legend-engine-xt-flatdata-protocol/src/main/resources/META-INF/services/org.finos.legend.engine.protocol.pure.v1.extension.PureProtocolExtension
  legend-engine-xt-flatdata-runtime/pom.xml
  legend-engine-xt-flatdata-runtime/src/main/java/org/finos/legend/engine/external/format/flatdata/FlatDataExecutionExtension.java
  legend-engine-xt-flatdata-runtime/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.extension.ExecutionExtension
  legend-engine-xt-serviceStore-executionPlan/pom.xml
  pom.xml
Labels: cla-present

#1476 make legacy test optional, add warning for missing mapping in runtime
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRuntimeBuilder.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestRuntimeCompilationFromGrammar.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/legend/service/metamodel.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanExecutionTest.pure
Labels: cla-present

#1489 bump Pure 4.3.1
  pom.xml
Labels: cla-present

#1465 Search Document Generation
  legend-engine-extensions-collection-generation/pom.xml
  legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
  legend-engine-pure-ide-light/src/main/java/org/finos/legend/engine/ide/PureIDELight.java
  legend-engine-xt-analytics-lineage-pure/src/main/resources/core_analytics_lineage/fullAnalytics.pure
  legend-engine-xt-analytics-search-generation/pom.xml
  legend-engine-xt-analytics-search-generation/src/main/java/org/finos/legend/engine/generation/SearchDocumentArtifactGenerationExtension.java
  legend-engine-xt-analytics-search-generation/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.dsl.generation.extension.ArtifactGenerationExtension
  legend-engine-xt-analytics-search-generation/src/test/java/org/finos/legend/engine/generation/TestSearchDocumentArtifactGenerationExtension.java
  legend-engine-xt-analytics-search-generation/src/test/resources/models/Model.pure
  legend-engine-xt-analytics-search-pure/pom.xml
  legend-engine-xt-analytics-search-pure/src/main/java/org/finos/legend/pure/code/core/CoreExternalAnalyticsSearchCodeRepositoryProvider.java
  legend-engine-xt-analytics-search-pure/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.filesystem.repository.CodeRepositoryProvider
  legend-engine-xt-analytics-search-pure/src/main/resources/core_analytics_search.definition.json
  legend-engine-xt-analytics-search-pure/src/main/resources/core_analytics_search/metamodel.pure
  legend-engine-xt-analytics-search-pure/src/main/resources/core_analytics_search/trans.pure
  legend-engine-xt-analytics-search-pure/src/main/resources/core_analytics_search/transTest.pure
  pom.xml
Labels: cla-present

#1492 Bump version of legend-engine-xt-analytics-search-generation-* modules
  legend-engine-xt-analytics-search-generation/pom.xml
  legend-engine-xt-analytics-search-pure/pom.xml
Labels: cla-present

#1487 Optimizing Connection Data setup for MultiExecution Services
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestRunner.java
  legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java
  legend-engine-test-runner-service/src/test/resources/testable/service/serviceGrammarTestWithOptimizedWorkflow.pure
Labels: cla-present

#1494 Preval - simplify filter with constant boolean return
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/preeval.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/tests.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/serialization/toPureGrammar.pure
Labels: cla-present

#1488 Fix Qualified/Derived Property Composer for Multiple Statements
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperDomainGrammarComposer.java
  legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestDomainGrammarRoundtrip.java
Labels: cla-present

#1496 Improve identifier sanitization by using a map of Java keyword replacements
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/conventions.pure
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/protocol/generation/generator.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchJson.pure
Labels: enhancement

#1477 Features/databricks catalog
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/databricks/customDatabricksTests.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/databricks/databricksExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/dynaFunctions/string.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/selectSubClauses/windowColumn.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/relationalSetUp.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/testModel/simpleTestModel.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/transform/fromPure/tests/testToSQLString.pure
Labels: cla-present

#1491 Handle dependencies in GraphQL Dev API
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/GraphQL.java
  legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLAPI.java
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Project3_Workspace1.pure
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Project3_upstreamProjects.json
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Project4_Version_2.0.1.pure
Labels: cla-present

#1463 Assert on concurrent poolstate
  legend-engine-executionPlan-execution/src/test/java/org/finos/legend/engine/plan/execution/concurrent/TestConcurrentExecutionNodeExecution.java
Labels: cla-present

#1510 Correctly handle property mapping overrides with extends and union mappings
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/extends/union/testExtendsForPropertyMappingWithUnion.pure
Labels: bug

#1546 Action for handling release failures
  .github/workflows/clean-after-failed-release.yml
Labels: enhancement

#1464 Trino Connector | Initial Commit
  legend-engine-xt-relationalStore-trino-execution-tests/pom.xml
  legend-engine-xt-relationalStore-trino-execution-tests/src/main/java/org/finos/legend/engine/authentication/TrinoTestDatabaseAuthenticationFlowProvider.java
  legend-engine-xt-relationalStore-trino-execution-tests/src/main/java/org/finos/legend/engine/authentication/TrinoTestDatabaseAuthenticationFlowProviderConfiguration.java
  legend-engine-xt-relationalStore-trino-execution-tests/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/tests/api/dynamicTestConnections/TrinoTestContainersWithDelegatedKerberosAuth.java
  legend-engine-xt-relationalStore-trino-execution-tests/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/tests/api/dynamicTestConnections/TrinoTestContainersWithUserAndPasswordAuth.java
  legend-engine-xt-relationalStore-trino-execution-tests/src/main/resources/META-INF/services/org.finos.legend.engine.authentication.provider.DatabaseAuthenticationFlowProvider
  legend-engine-xt-relationalStore-trino-execution-tests/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.connection.tests.api.DynamicTestConnection
  legend-engine-xt-relationalStore-trino-execution-tests/src/test/java/org/finos/legend/engine/TrinoRelationalTestServerInvoker.java
  legend-engine-xt-relationalStore-trino-execution-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProviderWithDelegatedKerberosAuth_Trino.java
  legend-engine-xt-relationalStore-trino-execution-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProviderWithUserPasswordAuth_Trino.java
  legend-engine-xt-relationalStore-trino-execution-tests/src/test/java/org/finos/legend/engine/server/test/pureClient/stores/dbSpecific/Test_Relational_DbSpecific_Trino_UsingPureClientTestSuite.java
  legend-engine-xt-relationalStore-trino-execution-tests/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withTrinoTestConnection.json
  legend-engine-xt-relationalStore-trino-execution/pom.xml
  legend-engine-xt-relationalStore-trino-execution/src/main/java/org/finos/legend/engine/authentication/flows/TrinoWithDelegatedKerberosFlow.java
  legend-engine-xt-relationalStore-trino-execution/src/main/java/org/finos/legend/engine/authentication/flows/TrinoWithUserPasswordFlow.java
  legend-engine-xt-relationalStore-trino-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/TrinoConnectionExtension.java
  legend-engine-xt-relationalStore-trino-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/TrinoDelegatedKerberosAuthenticationStrategyRuntime.java
  legend-engine-xt-relationalStore-trino-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/keys/TrinoDelegatedKerberosAuthenticationStrategyKey.java
  legend-engine-xt-relationalStore-trino-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/trino/TrinoCommands.java
  legend-engine-xt-relationalStore-trino-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/trino/TrinoDriver.java
  legend-engine-xt-relationalStore-trino-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/trino/TrinoManager.java
  legend-engine-xt-relationalStore-trino-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/TrinoDatasourceSpecificationRuntime.java
  legend-engine-xt-relationalStore-trino-execution/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/specifications/keys/TrinoDatasourceSpecificationKey.java
  legend-engine-xt-relationalStore-trino-execution/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.RelationalConnectionExtension
  legend-engine-xt-relationalStore-trino-execution/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.connection.ConnectionExtension
  legend-engine-xt-relationalStore-trino-execution/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.stores.relational.connection.manager.strategic.StrategicConnectionExtension
  legend-engine-xt-relationalStore-trino-grammar/pom.xml
  legend-engine-xt-relationalStore-trino-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/TrinoLexerGrammar.g4
  legend-engine-xt-relationalStore-trino-grammar/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/TrinoParserGrammar.g4
  legend-engine-xt-relationalStore-trino-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/TrinoCompilerExtension.java
  legend-engine-xt-relationalStore-trino-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/TrinoGrammarParserExtension.java
  legend-engine-xt-relationalStore-trino-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/TrinoGrammarComposerExtension.java
  legend-engine-xt-relationalStore-trino-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.compiler.toPureGraph.extension.CompilerExtension
  legend-engine-xt-relationalStore-trino-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.grammar.from.IRelationalGrammarParserExtension
  legend-engine-xt-relationalStore-trino-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.grammar.to.extension.PureGrammarComposerExtension
  legend-engine-xt-relationalStore-trino-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestTrinoConnectionGrammarCompiler.java
  legend-engine-xt-relationalStore-trino-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestTrinoConnectionGrammarRoundtrip.java
  legend-engine-xt-relationalStore-trino-protocol/pom.xml
  legend-engine-xt-relationalStore-trino-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/TrinoProtocolExtension.java
  legend-engine-xt-relationalStore-trino-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/authentication/TrinoDelegatedKerberosAuthenticationStrategy.java
  legend-engine-xt-relationalStore-trino-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/specification/TrinoDatasourceSpecification.java
  legend-engine-xt-relationalStore-trino-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/specification/TrinoSSLSpecification.java
  legend-engine-xt-relationalStore-trino-protocol/src/main/resources/META-INF/services/org.finos.legend.engine.protocol.pure.v1.extension.PureProtocolExtension
  legend-engine-xt-relationalStore-trino-pure/pom.xml
  legend-engine-xt-relationalStore-trino-pure/src/main/java/org/finos/legend/pure/code/core/CoreRelationalTrinoCodeRepositoryProvider.java
  legend-engine-xt-relationalStore-trino-pure/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.filesystem.repository.CodeRepositoryProvider
  legend-engine-xt-relationalStore-trino-pure/src/main/resources/core_relational_trino.definition.json
  legend-engine-xt-relationalStore-trino-pure/src/main/resources/core_relational_trino/relational/connection/metamodel.pure
  legend-engine-xt-relationalStore-trino-pure/src/main/resources/core_relational_trino/relational/protocols/pure/vX_X_X/extension/extension_trino.pure
  legend-engine-xt-relationalStore-trino-pure/src/main/resources/core_relational_trino/relational/protocols/pure/vX_X_X/extension/metamodel_connection.pure
  legend-engine-xt-relationalStore-trino-pure/src/main/resources/core_relational_trino/relational/sqlQueryToString/trinoExtension.pure
  legend-engine-xt-relationalStore-trino-pure/src/main/resources/core_relational_trino/relational/sqlQueryToString/trinoTestSuiteInvoker.pure
  legend-engine-xt-relationalStore-trino-pure/src/test/java/org/finos/legend/pure/code/core/PureIDELight.java
  legend-engine-xt-relationalStore-trino-pure/src/test/java/org/finos/legend/pure/code/core/Test_Pure_Relational_DbSpecific_Trino.java
  legend-engine-xt-relationalStore-trino-pure/src/test/resources/ideLightConfig.json
  pom.xml
Labels: cla-present

#1397 Delete Legacy Json Serialize/Deserialize nodes
  legend-engine-extensions-collection-execution/src/test/java/org/finos/legend/engine/extensions/collection/execution/TestExtensions.java
  legend-engine-extensions-collection-generation/pom.xml
  legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
  legend-engine-xt-json-protocol/pom.xml
  legend-engine-xt-json-protocol/src/main/java/org/finos/legend/engine/external/format/json/JsonProtocolExtension.java
  legend-engine-xt-json-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/external/format/json/JsonDeserializeExecutionNode.java
  legend-engine-xt-json-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/external/format/json/JsonPathReference.java
  legend-engine-xt-json-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/external/format/json/JsonSerializeExecutionNode.java
  legend-engine-xt-json-protocol/src/main/resources/META-INF/services/org.finos.legend.engine.protocol.pure.v1.extension.PureProtocolExtension
  legend-engine-xt-json-runtime/pom.xml
  legend-engine-xt-json-runtime/src/main/java/org/finos/legend/engine/external/format/json/JsonExecutionExtension.java
  legend-engine-xt-json-runtime/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.extension.ExecutionExtension
  legend-engine-xt-serviceStore-executionPlan/pom.xml
  pom.xml
Labels: cla-present

#1337 activate Reproducible Builds
  pom.xml
Labels: cla-present
