Repository finos/legend-engine, pull requests merged in 2023-06, with the labels that each got.

#1874 Upgrade jacoco-maven-plugin version to 0.8.10
  pom.xml
Labels: dependencies

#1805 Tracking worflow telemetry
  .github/workflows/build.yml
Labels: enhancement

#1903 Make LegendPlanTransformers.transformers immutable
  legend-engine-configuration/src/main/java/org/finos/legend/engine/plan/generation/extension/LegendPlanGeneratorExtension.java
  legend-engine-executionPlan-generation/src/main/java/org/finos/legend/engine/plan/generation/transformers/DevPlanTransformer.java
  legend-engine-executionPlan-generation/src/main/java/org/finos/legend/engine/plan/generation/transformers/LegendPlanTransformers.java
  legend-engine-language-pure-dsl-service-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/service/generation/ServicePlanGenerator.java
  legend-engine-language-pure-dsl-service-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/service/generation/extension/ServiceExecutionExtension.java
  legend-engine-query-pure/pom.xml
  legend-engine-query-pure/src/main/java/org/finos/legend/engine/query/pure/api/Execute.java
  legend-engine-service-post-validation-runner/src/main/java/org/finos/legend/engine/service/post/validation/runner/LegendServicePostValidationRunner.java
  legend-engine-service-post-validation-runner/src/main/java/org/finos/legend/engine/service/post/validation/runner/ServicePostValidationRunner.java
  legend-engine-test-runner-mapping/src/main/java/org/finos/legend/engine/test/runner/mapping/MappingTestRunner.java
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ServiceTestRunner.java
  legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-V7-grammar/src/main/java/org/finos/legend/engine/language/stores/elasticsearch/v7/plan/generation/ElasticsearchPlanGeneratorExtension.java
  legend-engine-xt-elasticsearch/legend-engine-xt-elasticsearch-executionPlan-test/src/test/java/org/finos/legend/engine/plan/execution/stores/elasticsearch/test/TestElasticsearchExecutionPlanFromGrammarIntegration.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecute.java
  legend-engine-xt-nonrelationalStore-mongodb-grammar-integration/src/main/java/org/finos/legend/engine/language/pure/grammar/integration/plan/MongoDBPlanGeneratorExtension.java
  legend-engine-xt-sql-query/src/main/java/org/finos/legend/engine/query/sql/api/execute/SqlExecute.java
Labels: bug

#1899 support comma in column value for service test csv data
  legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java
  legend-engine-test-runner-service/src/test/resources/testable/relational/legend-testable-relational-service-csv-test-data.pure
  legend-engine-test-runner-service/src/test/resources/testable/relational/legend-testable-relational-service-embeddedData.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/helperFunctions/helperFunctions.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/DDL/testDDL.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuite/naming/naming.pure
Labels: not backwards compatible
