Repository finos/legend-engine, pull requests merged in 2023-04, with the labels that each got.

#1620 In scanProperties, only generate debug string if printing debug info
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/lineage/scanProperties.pure
Labels: enhancement

#1629 Engine Java compiler improvements
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/helpers/platform/JavaHelper.java
  legend-engine-external-shared-format-runtime/src/main/java/org/finos/legend/engine/external/shared/ExternalFormatJavaCompilerExtension.java
  legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/ClassJavaSource.java
  legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/ClassListFilter.java
  legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/ClassPathFilter.java
  legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/ClassPathFilters.java
  legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/CompositeClassPathFilter.java
  legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/EngineJavaCompiler.java
  legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/JavaCompileException.java
  legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/MemoryClassLoader.java
  legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/MemoryFileManager.java
  legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/SingleFileCompiler.java
  legend-engine-shared-javaCompiler/src/test/java/org/finos/legend/engine/shared/javaCompiler/test/TestJavaCompileClassPathFilter.java
  legend-engine-xt-flatdata-runtime/src/main/java/org/finos/legend/engine/external/format/flatdata/FlatDataJavaCompilerExtension.java
  legend-engine-xt-json-runtime/src/main/java/org/finos/legend/engine/external/format/json/JsonJavaCompilerExtension.java
  legend-engine-xt-xml-runtime/src/main/java/org/finos/legend/engine/external/format/xml/XmlJavaCompilerExtension.java
Labels: enhancement

#1647 In typeInfo.pure, reduce calls to elementToPath
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/platformBinding/typeInfo/typeInfo.pure
Labels: enhancement

#1644 Compiler validation for element names
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperModelBuilder.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PackageableElementFirstPassBuilder.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/extension/CompilerExtensions.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/extension/Processor.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestAggregationAwareCompilationFromGrammar.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestMappingCompilationFromGrammar.java
  legend-engine-language-pure-compiler/src/test/resources/functionExample.json
  legend-engine-language-pure-compiler/src/test/resources/functionWithLambdaVariable.json
  legend-engine-language-pure-compiler/src/test/resources/queryWithPathVariable.json
  legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/test/runner/service/TestRuntimeGenerationForServiceTests.java
  legend-engine-xt-mastery-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/test/TestMasteryCompilationFromGrammar.java
  legend-engine-xt-morphir/pom.xml
  legend-engine-xt-morphir/src/test/java/org/finos/legend/engine/external/language/morphir/tests/TestMorphirFileGeneration.java
  legend-engine-xt-morphir/src/test/resources/org/finos/legend/engine/external/language/morphir/tests/simpleFileGeneration.json
  legend-engine-xt-serviceStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperServiceStoreClassMappingBuilder.java
Labels: bug

#1667 Allow function name to be different between protocol and model
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PackageableElementFirstPassBuilder.java
  legend-engine-language-pure-compiler/src/test/resources/functionExample.json
  legend-engine-language-pure-compiler/src/test/resources/functionWithLambdaVariable.json
  legend-engine-language-pure-compiler/src/test/resources/queryWithPathVariable.json
Labels: bug

#1676 Upgrade legend-pure to 4.4.0
  pom.xml
Labels: dependencies

#1681 Generate freemarker functions for included enumeration mappings
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/mappingExtension.pure
  legend-engine-pure-ide-light/pom.xml
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/functions/tests/projection/testFilter.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure
Labels: bug

#1694 Uniform withHeader flag in temp table creation for different result types
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/StreamResultToTempTableVisitor.java
Labels: bug

#1703 Fix bug with usage of enumeration mappings with M2M explosion
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/testExplosion.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchInMemory.pure
Labels: bug
