Repository finos/legend-engine, pull requests merged in 2023-02, with the labels that each got.

#1350 Add temp table support for Snowflake
  docs/store/extensions/Relational/Databases/snowflake/README.md
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/serialization/RequestIdGenerator.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/serialization/TemporaryFile.java
  legend-engine-xt-relationalStore-executionPlan-connection-tests/pom.xml
  legend-engine-xt-relationalStore-executionPlan-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProvider_Snowflake.java
  legend-engine-xt-relationalStore-executionPlan-connection-tests/src/test/resources/snowflake-graph-fetch-model.pure
  legend-engine-xt-relationalStore-executionPlan-connection-tests/src/test/resources/snowflake-graph-fetch-plan.json
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/driver/vendors/snowflake/SnowflakeCommands.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/ds/TestSnowflakeCommands.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/StreamResultToTempTableVisitor.java
Labels: cla-present

#1365 Fix firstDayOfQuarter dynafunc for memsql
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/memSqlExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/transform/fromPure/tests/testToSQLString.pure
Labels: cla-present

#1363 Always set identity on ExecuteWithArgs
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/PlanExecutor.java
Labels: cla-present

#1347 Persistence: Optimization Filter Support, Data split tests and Test restructure
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/common/OptimizationFilterAbstract.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalDeltaAbstract.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/logicalplan/datasets/DataType.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/UnitemporalDeltaPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/planner/UnitemporalPlanner.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-logical-plan/src/main/java/org/finos/legend/engine/persistence/components/util/LogicalPlanUtils.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/unitemporal/UnitemporalDeltaBatchIdBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/unitemporal/UnitemporalSnapshotBatchIdBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/unitemporal/UnitemporalSnapshotBatchIdDateTimeBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/unitemporal/UnitemporalSnapshotDateTimeBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/unitemporal/UnitemporalSnapshotTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/unitemporal/UnitemporalSnapshotWithBatchIdTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-ansi/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/unitemporal/UnitemporalSnapshotWithBatchTimeTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-core/src/main/java/org/finos/legend/engine/persistence/components/relational/api/RelationalIngestorAbstract.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/unitemporal/UnitemporalDeltaWithBatchIdTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/unitemporal-incremental-milestoning/expected/batch_id_based/with_data_splits/expected_pass1.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/unitemporal-incremental-milestoning/expected/batch_id_based/with_data_splits/expected_pass2.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/unitemporal-incremental-milestoning/expected/batch_id_based/with_data_splits/expected_pass3.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/unitemporal-incremental-milestoning/input/batch_id_based/with_data_splits/staging_data_pass1.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/unitemporal-incremental-milestoning/input/batch_id_based/with_data_splits/staging_data_pass2.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-h2/src/test/resources/data/unitemporal-incremental-milestoning/input/batch_id_based/with_data_splits/staging_data_pass3.csv
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalDeltaBatchIdBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalSnapshotBatchIdBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalSnapshotBatchIdDateTimeBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalSnapshotDateTimeBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalSnapshotTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalSnapshotWithBatchIdTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-memsql/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalSnapshotWithBatchTimeTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/sql/SnowflakeDataTypeMapping.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/sqldom/schema/Array.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/sqldom/schema/Object.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/main/java/org/finos/legend/engine/persistence/components/relational/snowflake/sqldom/schema/Variant.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/BaseTestUtils.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalSnapshotBatchIdBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalSnapshotBatchIdDateTimeBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalSnapshotDateTimeBasedTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/ingestmode/UnitemporalSnapshotTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-snowflake/src/test/java/org/finos/legend/engine/persistence/components/relational/snowflake/sql/DataTypeMappingTest.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/scenarios/UnitemporalDeltaBatchIdBasedScenarios.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/scenarios/UnitemporalSnapshotBatchIdBasedScenarios.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/scenarios/UnitemporalSnapshotBatchIdDateTimeBasedScenarios.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/scenarios/UnitemporalSnapshotDateTimeBasedScenarios.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/testcases/ingestmode/unitemporal/UnitmemporalDeltaBatchIdBasedTestCases.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/testcases/ingestmode/unitemporal/UnitmemporalSnapshotBatchIdBasedTestCases.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/testcases/ingestmode/unitemporal/UnitmemporalSnapshotBatchIdDateTimeBasedTestCases.java
  legend-engine-xt-persistence-component/legend-engine-xt-persistence-component-relational-test/src/test/java/org/finos/legend/engine/persistence/components/testcases/ingestmode/unitemporal/UnitmemporalSnapshotDateTimeBasedTestCases.java
Labels: cla-present

#1369 Add zipkin taces
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestRunner.java
Labels: cla-present

#1341 GraphQL File Generation - fix duplication of content in all files
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/sdl/fromPure_sdl.pure
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/sdl/tests/simpleTest.pure
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/deprecated/generation.pure
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/deprecated/tests/generationTests.pure
  legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLFileGeneration.java
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Address.graphql
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Firm.graphql
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/OtherClass.graphql
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Person.graphql
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/schema.graphql
Labels: cla-present

#1372 Revert "Add new security schemes/authentication metamodels to service…
  legend-engine-extensions-collection-generation/pom.xml
  legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
  legend-engine-xt-serviceStore-grammar/pom.xml
  legend-engine-xt-serviceStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperServiceStoreBuilder.java
  legend-engine-xt-serviceStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/IServiceStoreCompilerExtension.java
  legend-engine-xt-serviceStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ServiceStoreCompilerExtension.java
  legend-engine-xt-serviceStore-protocol/pom.xml
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/ServiceStoreProtocolExtension.java
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/AuthenticationSchemeRequirement.java
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/RestServiceExecutionNode.java
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/SingleAuthenticationSchemeRequirement.java
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/service/connection/ServiceStoreConnection.java
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/service/model/ApiKeySecurityScheme.java
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/service/model/HttpSecurityScheme.java
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/service/model/SecurityScheme.java
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/service/model/SecuritySchemeRequirement.java
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/service/model/Service.java
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/service/model/ServiceStore.java
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/service/model/SingleSecuritySchemeRequirement.java
  legend-engine-xt-serviceStore-pure/pom.xml
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore.definition.json
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan_generation.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan_print.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/metamodel/metamodelDiagram.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/metamodel/serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/metamodel/serviceStoreRuntime.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_21_0/extension/extension_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_21_0/transfers/metamodel_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_22_0/extension/extension_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_22_0/transfers/metamodel_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_23_0/extension/extension_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_23_0/transfers/metamodel_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_24_0/extension/extension_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_24_0/transfers/metamodel_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_25_0/extension/extension_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_25_0/transfers/metamodel_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_26_0/extension/extension_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_26_0/transfers/metamodel_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_27_0/extension/extension_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_27_0/transfers/metamodel_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_28_0/extension/extension_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_28_0/transfers/metamodel_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/vX_X_X/extension/extension_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/vX_X_X/models/executionPlan_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/vX_X_X/models/metamodel_connection.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/vX_X_X/models/metamodel_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/vX_X_X/transfers/connection_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/vX_X_X/transfers/metamodel_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/tests/store.pure
Labels: cla-present

#1367 handling empty classes for avro generation
  legend-engine-xt-avro-pure/src/main/resources/core_external_format_avro/metamodel/metamodel.pure
  legend-engine-xt-avro-pure/src/main/resources/core_external_format_avro/transformation/serialization_avroSchemaToJSON.pure
  legend-engine-xt-avro-pure/src/main/resources/core_external_format_avro/transformation/tests/testAvroSchemaGenerator.pure
  legend-engine-xt-avro-pure/src/main/resources/core_external_format_avro/transformation/transformation_avroSchemaGenerator.pure
Labels: cla-present

#1378 Remove Test Debug Line
  legend-engine-server/src/test/java/org/finos/legend/engine/server/test/shared/PureTestHelper.java
Labels: cla-present

#1371 Support for BigDecimal in GenerateMetaClasses, used for protocol file
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/metamodel_factories.pure
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/metamodel_factories_tests.pure
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/protocol/generation/generation.pure
Labels: cla-present

#1377 fix compilation of diagram with association on milestone class
  legend-engine-xt-diagram-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperDiagramBuilder.java
  legend-engine-xt-diagram-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestDiagramCompilationFromGrammar.java
Labels: cla-present

#1353 Add Java return value to compileAndExecuteJava result
  legend-engine-xt-java-runtime-compiler/src/main/java/org/finos/legend/engine/external/language/java/runtime/compiler/compiled/JavaRuntimeCompilerCompiledExtension.java
  legend-engine-xt-java-runtime-compiler/src/main/java/org/finos/legend/engine/external/language/java/runtime/compiler/shared/PureCompileAndExecuteJava.java
  legend-engine-xt-java-runtime-compiler/src/main/java/org/finos/legend/engine/external/language/java/runtime/compiler/shared/PureResultBuilder.java
  legend-engine-xt-java-runtime-compiler/src/main/resources/core_external_language_java_compiler/compiler.pure
  legend-engine-xt-java-runtime-compiler/src/test/java/org/finos/legend/engine/external/language/java/runtime/compiler/AbstractTestCompileAndExecuteJava.java
  legend-engine-xt-java-runtime-compiler/src/test/java/org/finos/legend/engine/external/language/java/runtime/compiler/compiled/TestCompileAndExecuteJavaCompiled.java
  legend-engine-xt-java-runtime-compiler/src/test/java/org/finos/legend/engine/external/language/java/runtime/compiler/shared/TestCompileAndExecuteJava.java
  legend-engine-xt-java-runtime-compiler/src/test/java/org/finos/legend/engine/external/language/java/runtime/compiler/shared/TestPureResultBuilder.java
  legend-engine-xt-java-runtime-compiler/src/test/resources/org/finos/legend/engine/external/language/java/runtime/compiler/shared/InvalidJavaClass.java
  legend-engine-xt-java-runtime-compiler/src/test/resources/org/finos/legend/engine/external/language/java/runtime/compiler/shared/ValidJavaClass.java
Labels: enhancement, cla-present

#1384 Delete .attach_pidXYZ files
  legend-engine-executionPlan-dependencies/.attach_pid173350
  legend-engine-executionPlan-generation/.attach_pid88735
  legend-engine-testable/.attach_pid176908
  legend-engine-xt-authentication-implementation-gcp-federation/.attach_pid172868
  legend-engine-xt-daml-grammar/.attach_pid115173
  legend-engine-xt-data-space-protocol/.attach_pid134054
  legend-engine-xt-diagram-protocol/.attach_pid22990
  legend-engine-xt-flatdata-shared/.attach_pid99711
  legend-engine-xt-javaGeneration-pure/.attach_pid88380
  legend-engine-xt-relationalStore-protocol/.attach_pid89344
Labels: bug, cla-present

#1361 Fix lineage calculation for semi structured queries
  legend-engine-xt-relationalStore-executionPlan/pom.xml
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/AbstractTestSemiStructured.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredFlattening.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredInheritanceMapping.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredJoinChainMapping.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSemiStructuredParseJsonMapping.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestSimpleSemiStructuredMapping.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/lineage/scanColumns/scanColumns.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
Labels: bug, cla-present

#1382 add typeName and typePath support
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/metaExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/metaExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/simpleObject.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/simple.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/metaLibrary.pure
Labels: cla-present

#1358 Prepare for preeval opensourcing
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/extension/router_extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/routing/router_routing.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/contract/storeContract.pure
Labels: cla-present

#1368 scalar Date, DateTime, BigDecimal in GraphQL schema generation
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/sdl/fromPure_sdl.pure
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/sdl/tests/simpleTest.pure
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/deprecated/generation.pure
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/deprecated/tests/generationTests.pure
  legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLFileGeneration.java
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/ClassWithCustomScalars.graphql
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/scalarFileGeneration.json
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/scalars.graphql
Labels: cla-present

#1386 External Format Contract Refactor
  legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/external/shared/format/model/ExternalFormatExtension.java
  legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/external/shared/format/model/transformation/fromModel/ExternalFormatSchemaGenerationExtension.java
  legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/external/shared/format/model/transformation/toModel/ExternalFormatModelGenerationExtension.java
  legend-engine-external-shared-format-model/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/SchemaSetCompiler.java
  legend-engine-external-shared-format-model/src/test/java/org/finos/legend/engine/external/shared/format/model/transformation/toModel/TestExampleSchemaToModelGeneration.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/executionPlan/executionPlan_generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/externalFormat/externalFormatContract.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/schemaSet/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/schemaSet/metamodel_diagram.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/transformation/tests/externalFormatContract.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/extensions/extension.pure
  legend-engine-xt-flatdata-pure/src/main/resources/core_external_format_flatdata/externalFormatContract.pure
  legend-engine-xt-flatdata-pure/src/main/resources/core_external_format_flatdata/metamodel/metamodel.pure
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/sdl/fromPure_sdl.pure
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/toPure/introspection/toPure_introspection.pure
  legend-engine-xt-haskell-pure/src/main/resources/core_external_language_haskell/transformation.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/binding/shared.pure
  legend-engine-xt-json-pure/src/main/resources/core_external_format_json/externalFormatContract.pure
  legend-engine-xt-json-pure/src/main/resources/core_external_format_json/metamodel/metamodel.pure
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/metamodel/metamodel.pure
  legend-engine-xt-xml-pure/src/main/resources/core_external_format_xml/externalFormatContract.pure
  legend-engine-xt-xml-pure/src/main/resources/core_external_format_xml/metamodel/metamodel.pure
Labels: cla-present

#1387 Add support for int, float, list in graphql arguments
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/transformation/tests/testQueryToGraphFetch.pure
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/transformation/transformation_graphFetch.pure
Labels: cla-present

#1390 Fix AggregationAware composer
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperMappingGrammarComposer.java
  legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/to/TestMappingGrammarTo.java
  legend-engine-language-pure-grammar/src/test/resources/SimpleAggregationAwareMapping.json
Labels: bug, cla-present

#1394 Databricks serverless endpoint (enabling integration testing)
  .github/workflows/database-databricks-integration-test.yml
  legend-engine-xt-relationalStore-executionPlan-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProvider_Databricks.java
  legend-engine-xt-relationalStore-executionPlan-connection/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/connection/authentication/strategy/ApiTokenAuthenticationStrategy.java
  pom.xml
Labels: cla-present

#1388 fix bug while executing multi-execution services
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestRunner.java
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/TestValueSpecificationBuilder.java
  legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java
  legend-engine-test-runner-service/src/test/resources/testable/service/serviceGrammarWithTestKeys3.pure
Labels: bug, cla-present

#1383 json schema feature updates to enable polymorphism
  legend-engine-external-format-jsonSchema/src/main/java/org/finos/legend/engine/external/format/jsonSchema/schema/generations/JSONSchemaConfig.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/external/format/json/fromJSONSchema.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/external/format/json/jsonSchema.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/external/format/json/tests/sharedSchema.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/external/format/json/tests/testToJsonSchema.pure
Labels: cla-present

#1401 Update GraphQL API endpoints with user/group workspace parameters.
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/debug/GraphQLDebug.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecute.java
Labels: cla-present

#1400 Update Snowflake/Postgres workflows to upload test results as Github artifacts
  .github/workflows/database-postgresql-integration-test.yml
  .github/workflows/database-postgresql-sql-generation-integration-test.yml
  .github/workflows/database-snowflake-integration-test.yml
  .github/workflows/database-snowflake-sql-generation-integration-test.yml
Labels: cla-present

#1389 support Function Expression in ExtractEnumValue
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/meta/testExtractEnumValue.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/metaLibrary.pure
Labels: cla-present

#1379 Persistence validation fix
  legend-engine-xt-persistence-cloud-grammar/pom.xml
  legend-engine-xt-persistence-grammar/pom.xml
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/toPureGraph/PersistenceCompilerExtension.java
  legend-engine-xt-persistence-pure/src/main/resources/core_persistence/persistence/validations_rules.pure
  legend-engine-xt-persistence-pure/src/main/resources/core_persistence/test/validation_rules_test.pure
Labels: cla-present

#1403 Improve error message when multiple properties found with same name
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/platformBinding/typeInfo/typeInfo.pure
Labels: cla-present

#1402 Add new plans to deserialize and execute plan tests
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/ExecutionNode.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/graphFetch/crossStore/TestDeserializeAndExecuteRelationalCrossStoreGraphFetchExecutionPlan.java
  legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/full/graphFetch/crossStore/withByteCode/plan2.json
  legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/full/graphFetch/crossStore/withSourceCode/plan2.json
Labels: cla-present

#1404 fix bug while running multiple tests of same keys
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestRunner.java
  legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java
  legend-engine-test-runner-service/src/test/resources/testable/service/serviceGrammarWithTestKeys3.pure
Labels: cla-present

#1406 add SubTypeGraphFetch tree
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/platformBinding/typeInfo/typeInfo.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/sourceTreeCalc/subType/testOnSourceRoot.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/sourceTreeCalc/testSourceTreeCalc.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/lineage/scanProperties.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/tools/testProfiles.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/simpleObject.pure
  legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestM2MGrammarCompileAndExecute.java
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchStoreStreamReading.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/platform/executionPlanNodes/platform/serialize.pure
  pom.xml
Labels: bug, cla-present, requires PURE

#1399 Prepend Query With SQL Comments
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/PlanExecutor.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/state/ExecutionState.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/json/JsonStreamingResult.java
  legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestQueryExecutionWithParameters.java
  legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestRelationalManagerOnExecution.java
  legend-engine-service-post-validation-runner/src/test/java/org/finos/legend/engine/service/post/validation/runner/TestLegendServicePostValidationRunner.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/RelationalExecutor.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/activity/RelationalExecutionActivity.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalExecutionNodeExecutor.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/RelationalResult.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/SQLExecutionResult.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/serialization/RelationalResultToJsonDefaultSerializer.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/TestRelationStoreExecutableManager.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/execution/TestExecutionPlan.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/functions/in/TestPlanExecutionForIn.java
  legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/RelationalExecutionNode.java
  legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/SQLExecutionNode.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/executionPlan.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/relationalGraphFetch.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/defaultPostProcessor.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/extension/extension_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/invocations/execution_relational_execute.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/models/executionPlan_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/models/results_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/relationalMappingExecution.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbTestRunner/testRunner.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/relationalSetUp.pure
Labels: cla-present, requires PURE

#1396 Delete Legacy Xsd Serialize/Deserialize nodes
  legend-engine-extensions-collection-execution/src/test/java/org/finos/legend/engine/extensions/collection/execution/TestExtensions.java
  legend-engine-extensions-collection-generation/pom.xml
  legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
  legend-engine-xt-xml-protocol/pom.xml
  legend-engine-xt-xml-protocol/src/main/java/org/finos/legend/engine/external/format/xml/XmlProtocolExtension.java
  legend-engine-xt-xml-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/external/format/xml/XmlDeserializeExecutionNode.java
  legend-engine-xt-xml-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/external/format/xml/XmlSerializeExecutionNode.java
  legend-engine-xt-xml-protocol/src/main/resources/META-INF/services/org.finos.legend.engine.protocol.pure.v1.extension.PureProtocolExtension
  legend-engine-xt-xml-runtime/pom.xml
  legend-engine-xt-xml-runtime/src/main/java/org/finos/legend/engine/external/format/xml/XmlExecutionExtension.java
  legend-engine-xt-xml-runtime/src/main/resources/META-INF/services/org.finos.legend.engine.plan.execution.extension.ExecutionExtension
  pom.xml
Labels: cla-present

#1391 Opensource preeval
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/valueSpecification.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/preeval.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/preeval/tests.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/contract/storeContract.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/router/tests/testPreeval.pure
Labels: cla-present

#1414 Handle LongNode in AnyDeserializer
  legend-engine-protocol/src/main/java/org/finos/legend/engine/protocol/AnyDeserializer.java
  legend-engine-protocol/src/test/java/org/finos/legend/engine/protocol/TestAnyDeserializer.java
Labels: cla-present

#1415 fix relational extension archetype
  legend-engine-xt-relationalStore-dbExtension-archetype/src/main/resources/archetype-resources/legend-engine-xt-relationalStore-__dbtype__-execution-tests/pom.xml
  legend-engine-xt-relationalStore-dbExtension-archetype/src/main/resources/archetype-resources/legend-engine-xt-relationalStore-__dbtype__-pure/pom.xml
  legend-engine-xt-relationalStore-dbExtension-archetype/src/main/resources/archetype-resources/legend-engine-xt-relationalStore-__dbtype__-pure/src/main/resources/core_relational___dbtype__.definition.json
  legend-engine-xt-relationalStore-dbExtension-archetype/src/main/resources/archetype-resources/legend-engine-xt-relationalStore-__dbtype__-pure/src/test/java/org/finos/legend/pure/code/core/Test_Pure_Relational_DbSpecific___DbType__.java
Labels: cla-present

#1419 Update sql test worflows to publish test results
  .github/workflows/database-athena-sql-generation-integration-test.yml
  .github/workflows/database-bigquery-sql-generation-integration-test.yml
  .github/workflows/database-databricks-sql-generation-integration-test.yml
  .github/workflows/database-mssqlserver-sql-generation-integration-test.yml
  .github/workflows/database-redshift-sql-generation-integration-test.yml
  .github/workflows/database-spanner-sql-generation-integration-test.yml
Labels: cla-present

#1420 add service validation duplicate assertion ID check
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/ServiceCompilerExtensionImpl.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceCompilationFromGrammar.java
Labels: cla-present

#1418 Ensure we call end on Deflater and Inflater instances
  legend-engine-shared-javaCompiler/src/main/java/org/finos/legend/engine/shared/javaCompiler/StringJavaSource.java
Labels: bug, cla-present

#1429 Update Maven Central badge
  README.md
Labels: cla-present

#1424 Adding Warnings To Communicate Incorrect Or Unsupported Model Chain/M…
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ConnectionFirstPassBuilder.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRuntimeBuilder.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestRuntimeCompilationFromGrammar.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceCompilationFromGrammar.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
Labels: cla-present

#1425 Adding Fix To Avoid Conflict between Variable Names in Alloy Lambdas …
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/functionInMapping.pure
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/metamodel_factories.pure
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/metamodel_factories_tests.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/langLibraryTests.pure
Labels: cla-present

#1430 bump to Pure 4.1.2
  pom.xml
Labels: cla-present

#1431 Upgrade to the new Pure version
  legend-engine-pure-platform-functions-java/pom.xml
  legend-engine-xt-json-javaPlatformBinding-pure/pom.xml
  legend-engine-xt-relationalStore-sqlserver-pure/pom.xml
  legend-engine-xt-sql-pure/pom.xml
  pom.xml
Labels: cla-present

#1411 dyna function for querying ssp
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestExtractFromSemiStructuredJoin.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/TestExtractFromSemiStructuredSimple.java
  legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/extractFromSemiStructuredJoin.pure
  legend-engine-xt-relationalStore-executionPlan/src/test/resources/org/finos/legend/engine/plan/execution/stores/relational/test/semiStructured/extractFromSemiStructuredMappingSimple.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/h2/h2Extension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/snowflake/snowflakeExtension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/testSuiteCompletenessTests.pure
Labels: cla-present

#1433 Add Java SQL test summary generator
  legend-engine-test-reports/pom.xml
  legend-engine-test-reports/src/main/java/org/finos/legend/engine/test/LegendDatabaseSQLTestingReport.java
  legend-engine-test-reports/src/main/java/org/finos/legend/engine/test/LegendDatabaseTestingReportGenerator.java
  legend-engine-test-reports/src/main/java/org/finos/legend/engine/test/TestStatus.java
  legend-engine-test-reports/src/main/script/download_github_workflow_artifacts.sh
  legend-engine-test-reports/src/test/resources/example-reports/postgresql/TEST-org.finos.legend.engine.server.test.pureClient.stores.dbSpecific.Test_Relational_DbSpecific_Postgres_UsingPureClientTestSuite.xml
  legend-engine-test-reports/src/test/resources/example-reports/postgresql/result.zip
  legend-engine-test-reports/src/test/resources/example-reports/snowflake/TEST-org.finos.legend.engine.server.test.pureClient.stores.dbSpecific.Test_Relational_DbSpecific_Snowflake_UsingPureClientTestSuite.xml
  legend-engine-test-reports/src/test/resources/example-reports/snowflake/result.zip
Labels: cla-present

#1435 Update sql testing report generator
  legend-engine-test-reports/src/main/java/org/finos/legend/engine/test/LegendDatabaseSQLTestingReport.java
  legend-engine-test-reports/src/main/java/org/finos/legend/engine/test/LegendDatabaseTestingReportGenerator.java
  legend-engine-test-reports/src/main/java/org/finos/legend/engine/test/TestStatus.java
Labels: cla-present

#1434 Fix for association properties in GraphQL
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/transformation/tests/testQueryToGraphFetch.pure
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/transformation/transformation_graphFetch.pure
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Project1_Workspace1.pure
Labels: cla-present

#1436 Update SQL testing report generator
  legend-engine-test-reports/src/main/java/org/finos/legend/engine/test/LegendDatabaseSQLTestingReport.java
  legend-engine-test-reports/src/main/java/org/finos/legend/engine/test/LegendDatabaseTestingReportGenerator.java
  legend-engine-test-reports/src/main/java/org/finos/legend/engine/test/TestStatus.java
  legend-engine-xt-relationalStore-test-server/src/test/java/org/finos/legend/engine/server/test/pureClient/stores/dbSpecific/Test_Relational_DbSpecific_Snowflake_UsingPureClientTestSuite.java
Labels: cla-present

#1392 Handle multiple statements in GraphQL
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/domain/domainManagement.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/domain/tests/testDomainManagement.pure
  legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLAPI.java
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Project1_Workspace1.pure
Labels: cla-present

#1439 Cleanup ServiceStore Diagram
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/ServiceStoreProtocolExtension.java
  legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/AuthenticationSchemeRequirement.java
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan_print.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/metamodel/metamodelDiagram.pure
Labels: cla-present

#1417 Clean up authentication modules
  legend-engine-xt-authentication-experimental/pom.xml
  legend-engine-xt-authentication-experimental/src/main/java/org/finos/legend/engine/connection/jdbc/JdbcConnectionProvider.java
  legend-engine-xt-authentication-experimental/src/main/java/org/finos/legend/engine/connection/jdbc/JdbcConnectionSpecification.java
  legend-engine-xt-authentication-experimental/src/test/java/org/finos/legend/engine/connection/TestJdbcConnectionProvider.java
  legend-engine-xt-authentication-implementation-core/pom.xml
  legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/connection/ConnectionProvider.java
  legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/connection/ConnectionSpecification.java
  pom.xml
Labels: cla-present

#1437 Delete empty legacy service tests at composer
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/HelperServiceGrammarComposer.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/ServiceGrammarComposerExtension.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarRoundtrip.java
  legend-engine-xt-mastery-grammar/src/test/java/org/finos/legend/engine/language/pure/dsl/mastery/compiler/test/TestMasteryCompilationFromGrammar.java
Labels: cla-present

#1428 Legend SQL - Further translations for SQL functions
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/tds/tdsSchema.pure
  legend-engine-xt-sql-grammar-integration/src/test/java/org/finos/legend/engine/language/sql/grammar/integration/test/TestSQLEmbedded.java
  legend-engine-xt-sql-grammar/src/main/antlr4/org/finos/legend/engine/language/sql/grammar/from/antlr4/SqlBaseLexer.g4
  legend-engine-xt-sql-grammar/src/main/antlr4/org/finos/legend/engine/language/sql/grammar/from/antlr4/SqlBaseParser.g4
  legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/from/AbstractSqlBaseLexer.java
  legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/from/SQLGrammarParser.java
  legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/from/SqlVisitor.java
  legend-engine-xt-sql-grammar/src/main/java/org/finos/legend/engine/language/sql/grammar/to/SQLGrammarComposer.java
  legend-engine-xt-sql-grammar/src/test/java/org/finos/legend/engine/language/sql/grammar/test/roundtrip/TestSQLRoundTrip.java
  legend-engine-xt-sql-pure-metamodel/src/main/resources/core_external_query_sql_metamodel/metamodel.pure
  legend-engine-xt-sql-pure/pom.xml
  legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql.definition.json
  legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/fromPure.pure
  legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/shared.pure
  legend-engine-xt-sql-pure/src/main/resources/core_external_query_sql/binding/fromPure/tests/testTranspile.pure
Labels: cla-present

#1432 Add Trino DatabaseType
  legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/DatabaseType.java
Labels: cla-present

#1443 bump Pure to 4.2.1
  pom.xml
Labels: cla-present

#1446 change hardcoded path to databricks finos instance
  legend-engine-xt-relationalStore-test-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig_withDatabricksTestConnection.json
Labels: cla-present

#1444 add support for plan caching on graphql
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/domain/domainManagement.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/domain/tests/testDomainManagement.pure
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/deprecated/tests/generationTests.pure
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/transformation/tests/testQueryToGraphFetch.pure
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/transformation/transformation_graphFetch.pure
  legend-engine-xt-graphQL-query/pom.xml
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/GraphQL.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/cache/GraphQLCacheKey.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/cache/GraphQLDevCacheKey.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/cache/GraphQLPlanCache.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/cache/GraphQLProdCacheKey.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/debug/GraphQLDebug.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecute.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/GraphQLExecutionHelper.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/SerializedNamedPlans.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/execute/model/GraphQLCachableVisitorHelper.java
  legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLAPI.java
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/Project1_Workspace1.pure
Labels: cla-present

#1409 Legend Authentication Refactoring - Integrate credential provider
  legend-engine-server/pom.xml
  legend-engine-server/src/main/java/org/finos/legend/engine/server/Server.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/pom.xml
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/main/java/org/finos/legend/engine/authentication/LegendDefaultDatabaseAuthenticationFlowProvider.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication-default/src/test/java/org/finos/legend/engine/authentication/flows/TestSnowflakeWithKeyPairFlow.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/pom.xml
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/src/main/java/org/finos/legend/engine/authentication/flows/SnowflakeWithKeyPairFlow.java
  legend-engine-xt-relationalStore-executionPlan-connection-authentication/src/main/java/org/finos/legend/engine/authentication/provider/DatabaseAuthenticationFlowProviderConfiguration.java
  legend-engine-xt-relationalStore-executionPlan/pom.xml
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/config/RelationalExecutionConfiguration.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalStoreExecutorBuilder.java
Labels: cla-present
