Repository finos/legend-engine, pull requests merged in 2023-01, with the labels that each got.

#1279 download athena jar for running db integration tests
  .github/workflows/database-athena-integration-test.yml
  .github/workflows/database-athena-sql-generation-integration-test.yml
  legend-engine-xt-relationalStore-athena-execution-tests/pom.xml
Labels: cla-present

#1284 relational tutorial improvement
  docs/store/extensions/Relational/new-connector-tutorial.md
  legend-engine-xt-relationalStore-athena-execution-tests/pom.xml
Labels: cla-present

#1282 Adding WeekofYear DynaFunction For MEMSQL
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/customMemSQLTests.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/memSqlExtension.pure
Labels: cla-present

#1283 Adding Fix For Java Reserved Words When Used As Pure Class Properties
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/conventions.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/test/stringLibraryTests.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/testSimpleRelationalGraphFetch.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/relationalSetUp.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/testModel/simpleTestModel.pure
Labels: cla-present

#1286 Enhance java generation to support generics and ways to extend protocol generation
  legend-engine-protocol-generation/src/main/java/org/finos/legend/engine/protocol/generation/GenerateMetaClasses.java
  legend-engine-protocol-generation/src/main/java/org/finos/legend/engine/protocol/generation/GenerateTranslator.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/PackageableElement.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/connection/Connection.java
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/generation/conventions.pure
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/protocol/generation/generation.pure
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/protocol/generation/generation_conventions_helper.pure
  legend-engine-xt-javaGeneration-pure/src/main/resources/core_external_language_java/protocol/generation/generation_test.pure
Labels: cla-present

#1288 Revert "support for execution environments in multi execution services"
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ValueSpecificationBuilderForFuncExpr.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
  legend-engine-language-pure-dsl-service-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/service/generation/ServicePlanGenerator.java
  legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceLexerGrammar.g4
  legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceParserGrammar.g4
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/HelperServiceBuilder.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/ServiceCompilerExtensionImpl.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/from/ServiceParseTreeWalker.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/HelperExecutionEnvironmentGrammarComposer.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/HelperServiceGrammarComposer.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/ServiceGrammarComposerExtension.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/ServiceProtocolExtension.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/ExecutionEnvironmentInstance.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/ExecutionParameters.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/MultiExecutionParameters.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/SingleExecutionParameters.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceCompilationFromGrammar.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarParser.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarRoundtrip.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/legend/service/helperFunctions.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/legend/service/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/mappingExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/routing/router_routing.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/store/routing.pure
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestRunner.java
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/TestValueSpecificationBuilder.java
  legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java
  legend-engine-test-runner-service/src/test/resources/testable/m2m/legend-testable-m2m-inline-multiExec-embeddedParam.pure
  legend-engine-test-runner-service/src/test/resources/testable/m2m/legend-testable-m2m-service-model.pure
Labels: cla-present

#1234 cleanup model to model test suite parser and compiler
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/data/core/EmbeddedDataCompilerHelper.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/data/embedded/ModelStoreDataParseTreeWalker.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/MappingParseTreeWalker.java
  legend-engine-language-pure-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/data/ModelStoreDataGrammarComposer.java
  legend-engine-language-pure-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/roundtrip/TestMappingGrammarRoundtrip.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/connection/ModelStoreTestConnectionFactory.java
Labels: bug, cla-present

#1295 Update database-spanner-integration-test.yml
  .github/workflows/database-spanner-integration-test.yml
Labels: cla-present

#1296 Use custom batch size for relational graphfetch
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/result/graphFetch/GraphObjectsBatch.java
  legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
  legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/simpleRelationalService.pure
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalExecutionNodeExecutor.java
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/result/graphFetch/RelationalGraphObjectsBatch.java
Labels: cla-present

#1299 GraphQL - Fix empty schema
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/sdl/fromPure_sdl.pure
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/deprecated/tests/generationTests.pure
  legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLFileGeneration.java
  legend-engine-xt-graphQL-query/src/test/resources/org/finos/legend/engine/query/graphQL/api/test/schema.graphql
Labels: cla-present

#1300 create compilation warning for duplicate columns in a table
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
Labels: cla-present

#1305 Changetoken Cast Generation
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/changetoken/changetoken_test.pure
  legend-engine-pure-ide-light/pom.xml
  legend-engine-pure-ide-light/src/main/java/org/finos/legend/engine/ide/PureIDELight.java
  legend-engine-xt-changetoken-compiler/pom.xml
  legend-engine-xt-changetoken-compiler/src/main/java/org/finos/legend/engine/changetoken/generation/GenerateCast.java
  legend-engine-xt-changetoken-compiler/src/main/java/org/finos/legend/engine/changetoken/generation/GenerateCastUtil.java
  legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCast2Test.java
  legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastTest.java
  legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastTestBase.java
  legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastUtilTest.java
  legend-engine-xt-changetoken-compiler/src/test/resources/log4j.properties
  legend-engine-xt-changetoken-pure/pom.xml
  legend-engine-xt-changetoken-pure/src/main/java/org/finos/legend/engine/changetoken/code/CorePureChangeTokenCodeRepositoryProvider.java
  legend-engine-xt-changetoken-pure/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.filesystem.repository.CodeRepositoryProvider
  legend-engine-xt-changetoken-pure/src/main/resources/core_pure_changetoken.definition.json
  legend-engine-xt-changetoken-pure/src/main/resources/core_pure_changetoken/cast_generation.pure
  legend-engine-xt-changetoken-pure/src/main/resources/core_pure_changetoken/changetoken.pure
  legend-engine-xt-changetoken-pure/src/main/resources/core_pure_changetoken/changetoken_diagram.pure
  legend-engine-xt-changetoken-pure/src/main/resources/core_pure_changetoken/changetoken_test.pure
  pom.xml
Labels: enhancement, cla-present

#1306 Detailed test summary for db integration workflows
  .github/workflows/database-athena-sql-generation-integration-test.yml
  .github/workflows/database-bigquery-sql-generation-integration-test.yml
  .github/workflows/database-databricks-sql-generation-integration-test.yml
  .github/workflows/database-mssqlserver-sql-generation-integration-test.yml
  .github/workflows/database-postgresql-sql-generation-integration-test.yml
  .github/workflows/database-redshift-sql-generation-integration-test.yml
  .github/workflows/database-snowflake-sql-generation-integration-test.yml
  .github/workflows/database-spanner-sql-generation-integration-test.yml
  legend-engine-xt-relationalStore-test-server/src/main/java/org/finos/legend/engine/server/test/shared/Relational_DbSpecific_UsingPureClientTestSuite.java
Labels: cla-present

#1302 Dependency management in XStore graph fetch execution
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/compilation/GeneratePureConfig.java
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/store/platform/graphFetch/IPlatformPrimitiveQualifierLocalGraphFetchExecutionNodeSpecifics.java
  legend-engine-executionPlan-execution-store-inMemory/src/main/java/org/finos/legend/engine/plan/execution/stores/inMemory/plugin/InMemoryExecutionNodeExecutor.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/cache/graphFetch/GraphFetchCrossAssociationKeys.java
  legend-engine-executionPlan-execution/src/main/java/org/finos/legend/engine/plan/execution/nodes/ExecutionNodeExecutor.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/ExecutionNode.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/ExecutionNodeVisitor.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/GlobalGraphFetchExecutionNode.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/PlatformGlobalGraphFetchExecutionNode.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/PlatformPrimitiveQualifierLocalGraphFetchExecutionNode.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/StoreMappingGlobalGraphFetchExecutionNode.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_print.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/extensions.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/test/executionPlan_execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetchExecutionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetch_routing.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/testCrossStoreGraphFetch.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/testRouting.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/testUnion.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/modelToModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_18_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_19_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_20_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_22_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_23_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_24_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_25_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_26_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_27_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_28_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/models/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/metamodel/clustering.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/platform/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/store/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/storeContract.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/simpleObject.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/tests/legend/testUnitMeasure.pure
  legend-engine-server/src/test/java/org/finos/legend/engine/server/test/pureClient/stores/Test_M2M_UsingPureClientTestSuite.java
  legend-engine-server/src/test/java/org/finos/legend/engine/server/test/pureClient/stores/Test_Relational_UsingPureClientTestSuite.java
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/bindPlanToLegendJavaPlatform.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/graphFetchCommon.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/inMemory/graphFetchInMemory.pure
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/planConventions/enginePlatformDependencies.pure
  legend-engine-xt-relationalStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/relational/plugin/RelationalExecutionNodeExecutor.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/test/full/graphFetch/cache/TestPlanExecutionWithGraphFetchCrossKeyCache.java
  legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/executionPlanNodes/graphFetch/graphFetchRelational.pure
  legend-engine-xt-relationalStore-javaPlatformBinding-pure/src/main/resources/core_relational_java_platform_binding/legendJavaPlatformBinding/executionPlanTest.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/contract/storeContract.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/domain/domainManagementTests.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/relationalGraphFetch.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/testOrderedCrossStoreGraphFetch.pure
  legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/plugin/ServiceExecutionNodeExecutor.java
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/contract/storeContract.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan_generation.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/tests/testRouting.pure
Labels: enhancement, cla-present

#1303 support execution environment for multi-execution services
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ValueSpecificationBuilderForFuncExpr.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
  legend-engine-language-pure-dsl-service-generation/src/main/java/org/finos/legend/engine/language/pure/dsl/service/generation/ServicePlanGenerator.java
  legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceLexerGrammar.g4
  legend-engine-language-pure-dsl-service/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/ServiceParserGrammar.g4
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/HelperServiceBuilder.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/ServiceCompilerExtensionImpl.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/from/ServiceParseTreeWalker.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/HelperExecutionEnvironmentGrammarComposer.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/HelperServiceGrammarComposer.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/grammar/to/ServiceGrammarComposerExtension.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/ServiceProtocolExtension.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/ExecutionEnvironmentInstance.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/ExecutionParameters.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/MultiExecutionParameters.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/service/SingleExecutionParameters.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceCompilationFromGrammar.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarParser.java
  legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarRoundtrip.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/legend/service/helperFunctions.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/legend/service/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/mappingExtension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/routing/router_routing.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/router/store/routing.pure
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestRunner.java
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/TestValueSpecificationBuilder.java
  legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java
  legend-engine-test-runner-service/src/test/resources/testable/m2m/legend-testable-m2m-inline-multiExec-embeddedParam.pure
  legend-engine-test-runner-service/src/test/resources/testable/m2m/legend-testable-m2m-service-model.pure
  legend-engine-test-runner-service/src/test/resources/testable/service/serviceGrammarWithTestKeysAndParameters.pure
Labels: enhancement, cla-present

#1249 adding precedence for post processors
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/RelationalCompilerExtension.java
  legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/RelationalDatabaseConnection.java
  legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/postprocessor/PostProcessor.java
Labels: cla-present

#1313 update legend pure to 3.8.3
  pom.xml
Labels: cla-present

#1289 fix root union support on relational graph fetch as router union
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/contract/storeContract.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/graphFetch/tests/union/testUnionRootLevel_relational.pure
Labels: cla-present

#1317 Revert memsql boolean literal processor
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/customMemSQLTests.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/sqlQueryToString/dbSpecific/memSql/memSqlExtension.pure
Labels: cla-present

#1318 revert adding precedence for Post processor
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/RelationalCompilerExtension.java
  legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/RelationalDatabaseConnection.java
  legend-engine-xt-relationalStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/postprocessor/PostProcessor.java
Labels: cla-present

#1314 Support derived properties in Model Chain
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/chain.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/modelToModelToRelational/m2m2rShowcase.pure
Labels: cla-present

#1321 Refactor Legend authentication - Dependency cleanup
  legend-engine-xt-authentication-implementation-core/pom.xml
  legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/authentication/intermediationrule/impl/EncryptedPrivateKeyFromVaultRule.java
  legend-engine-xt-authentication-implementation-core/src/test/java/org/finos/legend/authentication/TestCredentialCreation_EncryptedApiKey.java
Labels: cla-present

#1312 add graphQL SDL xt extension
  legend-engine-extensions-collection-generation/src/test/java/org/finos/legend/engine/extensions/collection/generation/TestExtensions.java
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/binding/fromPure/sdl/fromPure_sdl.pure
  legend-engine-xt-graphQL-pure/src/main/resources/core_external_query_graphql/contract.pure
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/format/GraphQLSDLFormatExtension.java
  legend-engine-xt-graphQL-query/src/main/java/org/finos/legend/engine/query/graphQL/api/format/ModelToGraphQLSchemaConfiguration.java
  legend-engine-xt-graphQL-query/src/main/resources/META-INF/services/org.finos.legend.engine.external.shared.format.model.ExternalFormatExtension
Labels: cla-present

#1323 Refactor Legend Authentication : Add xt grammar extensions
  legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/compiler/toPureGraph/AuthenticationCompilerExtension.java
  legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/compiler/toPureGraph/HelperAuthenticationBuilder.java
  legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/compiler/toPureGraph/IAuthenticationCompilerExtension.java
  legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/from/AWSCredentialsParser.java
  legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/from/AuthenticationGrammarParserExtension.java
  legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/from/AuthenticationParseTreeWalker.java
  legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/from/CredentialVaultSecretParseTreeWalker.java
  legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/from/IAuthenticationGrammarParserExtension.java
  legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/from/SpecificationSourceCode.java
  legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/from/demo/AuthenticationDemoParseTreeWalker.java
  legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/to/AuthenticationGrammarComposerExtension.java
  legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/to/AuthenticationSpecificationComposer.java
  legend-engine-xt-authentication-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/authentication/grammar/to/IAuthenticationGrammarComposerExtension.java
  legend-engine-xt-authentication-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.dsl.authentication.compiler.toPureGraph.IAuthenticationCompilerExtension
  legend-engine-xt-authentication-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.dsl.authentication.grammar.from.IAuthenticationGrammarParserExtension
  legend-engine-xt-authentication-grammar/src/main/resources/META-INF/services/org.finos.legend.engine.language.pure.dsl.authentication.grammar.to.IAuthenticationGrammarComposerExtension
  legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/authentication/intermediationrule/impl/UserPasswordFromVaultRule.java
  legend-engine-xt-authentication-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/authentication/specification/UserPasswordAuthenticationSpecification.java
  legend-engine-xt-authentication-pure/src/main/resources/core_authentication/metamodel/metamodel_apikey.pure
  legend-engine-xt-authentication-pure/src/main/resources/core_authentication/pure/vX_X_X/transfers/authentication.pure
Labels: cla-present

#1325 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-present

#1327 Restrict Variable Reprocessing
  legend-engine-pure-code-compiled-core/src/main/resources/core/store/m2m/chain.pure
Labels: cla-present

#1335 Add all valid assertion IDs to assertion not found exception
  legend-engine-service-post-validation-runner/src/main/java/org/finos/legend/engine/service/post/validation/runner/ServicePostValidationRunner.java
Labels: cla-present

#1336 Support for ChangeFieldType changetoken
  legend-engine-xt-changetoken-compiler/src/main/java/org/finos/legend/engine/changetoken/generation/GenerateCastUtil.java
  legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCast3Test.java
  legend-engine-xt-changetoken-compiler/src/test/java/org/finos/legend/engine/changetoken/generation/GenerateCastUtilTest.java
  legend-engine-xt-changetoken-pure/src/main/resources/core_pure_changetoken/cast_generation.pure
  legend-engine-xt-changetoken-pure/src/main/resources/core_pure_changetoken/changetoken_test.pure
Labels: cla-present

#1320 Improve property alias logic for subtype unions
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/functions/tests/testConcatenate.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/union/testUnion.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/mapping/union/testUnionPartial.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/validation/tests/testValidationWithMilestoning.pure
Labels: bug, cla-present

#1338 Legend Authentication Refactoring - Update APIs
  docs/authentication/code-examples.md
  legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/authentication/credentialprovider/CredentialProviderProvider.java
  legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/authentication/credentialprovider/impl/ApikeyCredentialProvider.java
  legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/authentication/credentialprovider/impl/PrivateKeyCredentialProvider.java
  legend-engine-xt-authentication-implementation-core/src/main/java/org/finos/legend/authentication/credentialprovider/impl/UserPasswordCredentialProvider.java
  legend-engine-xt-authentication-implementation-core/src/test/java/org/finos/legend/authentication/TestCredentialProviderProvider.java
  legend-engine-xt-authentication-implementation-gcp-federation/src/main/java/org/finos/legend/authentication/credentialprovider/impl/GCPWIFWithAWSIdPOAuthCredentialProvider.java
Labels: cla-present

#1339 Upgrade legend-pure to 3.8.4
  pom.xml
Labels: cla-present, dependencies

#1343 update serverVersion on tests
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/functions/tests/testIn.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/advanced/testRelationalResultSourcing.pure
Labels: cla-present

#1328 Fix first join JSON to grammar bug
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperRelationalGrammarComposer.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestRelationalGrammarRoundtrip.java
Labels: bug, cla-present

#1342 Include debug details when plan generation fails
  legend-engine-executionPlan-generation/src/main/java/org/finos/legend/engine/plan/generation/PlanGenerator.java
Labels: cla-present

#1344 new protocol v1_29_0
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/PureClientVersions.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_29_0/extension/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_29_0/models/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_29_0/models/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_29_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_29_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/extension/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/invocations/execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/invocations/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/invocations/testLoadModels.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/models/diagram.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/models/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/models/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/models/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/models/results.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/scan/buildBasePureModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/scan/buildPureModelAsText.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/scan/testBuildPureModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/transfers/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/transfers/mapping.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/transfers/store.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/transfers/valueSpecification.pure
  legend-engine-xt-avro-pure/src/main/resources/core_external_format_avro/protocol/protocol_v1_29_0.pure
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/protocol/protocol_v1_29_0.pure
  legend-engine-xt-relationalStore-bigquery-pure/src/main/resources/core_relational_bigquery/relational/protocols/pure/v1_29_0/extension/extension_bigQuery.pure
  legend-engine-xt-relationalStore-bigquery-pure/src/main/resources/core_relational_bigquery/relational/protocols/pure/v1_29_0/models/metamodel_bigQuery.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/extension/extension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/extension/extension_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/invocations/execution_relation_executeInRelationalDb.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/invocations/execution_relational_execute.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/invocations/execution_relational_testConnection.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/invocations/execution_relational_testData.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/models/executionPlan_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/models/metamodel_connection.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/models/metamodel_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/models/results_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/models/testData_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/transfers/connection_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/transfers/metamodel_relational.pure
  legend-engine-xt-relationalStore-spanner-pure/src/main/resources/core_relational_spanner/relational/protocols/pure/v1_29_0/extension/extension_Spanner.pure
  legend-engine-xt-relationalStore-spanner-pure/src/main/resources/core_relational_spanner/relational/protocols/pure/v1_29_0/models/metamodel_Spanner.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_29_0/extension/extension.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_29_0/extension/extension_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_29_0/models/executionPlan_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_29_0/models/metamodel_connection.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_29_0/models/metamodel_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_29_0/transfers/connection_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_29_0/transfers/metamodel_serviceStore.pure
Labels: cla-present

#1309 Improvements for compilation warning for duplicate columns
  legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
  legend-engine-xt-relationalStore-grammar/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRelationalCompilationFromGrammar.java
Labels: cla-present

#1345 update service version to latest protocol version
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/functions/tests/testIn.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/advanced/testRelationalResultSourcing.pure
Labels: cla-present

#1315 Persistence API to take actions using the given platform
  legend-engine-xt-persistence-api/pom.xml
  legend-engine-xt-persistence-api/src/main/java/org/finos/legend/engine/persistence/api/PersistencePlatformActionPayload.java
  legend-engine-xt-persistence-api/src/main/java/org/finos/legend/engine/persistence/api/PersistencePlatformActions.java
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/platform/PersistencePlatformActionRequest.java
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/platform/PersistencePlatformActionsExtension.java
  pom.xml
Labels: cla-present

#1346 Fix persistence api module version
  legend-engine-xt-persistence-api/pom.xml
Labels: cla-present

#1349 revert protocol change and change server version
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/PureClientVersions.java
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/functions/tests/testIn.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tests/advanced/testRelationalResultSourcing.pure
Labels: cla-present

#1348 added milestoning validation check on parameters of GetAll, GetAllVersions and GetAllVersionsInRange
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
  legend-engine-language-pure-dsl-service-execution/src/test/java/org/finos/legend/engine/language/pure/dsl/service/execution/TestServiceRunner.java
  legend-engine-language-pure-dsl-service-execution/src/test/resources/org/finos/legend/engine/pure/dsl/service/execution/test/simpleRelationalService.pure
Labels: cla-present

#1352 Revert protocol changes
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/PureClientVersions.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_29_0/extension/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_29_0/models/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_29_0/models/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_29_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/binding/protocols/pure/v1_29_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/extension/extension.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/invocations/execution.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/invocations/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/invocations/testLoadModels.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/models/diagram.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/models/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/models/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/models/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/models/results.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/scan/buildBasePureModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/scan/buildPureModelAsText.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/scan/testBuildPureModel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/transfers/executionPlan.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/transfers/generation.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/transfers/mapping.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/transfers/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/transfers/store.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_29_0/transfers/valueSpecification.pure
  legend-engine-xt-avro-pure/src/main/resources/core_external_format_avro/protocol/protocol_v1_29_0.pure
  legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/protocol/protocol_v1_29_0.pure
  legend-engine-xt-relationalStore-bigquery-pure/src/main/resources/core_relational_bigquery/relational/protocols/pure/v1_29_0/extension/extension_bigQuery.pure
  legend-engine-xt-relationalStore-bigquery-pure/src/main/resources/core_relational_bigquery/relational/protocols/pure/v1_29_0/models/metamodel_bigQuery.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/extension/extension.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/extension/extension_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/invocations/execution_relation_executeInRelationalDb.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/invocations/execution_relational_execute.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/invocations/execution_relational_testConnection.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/invocations/execution_relational_testData.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/models/executionPlan_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/models/metamodel_connection.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/models/metamodel_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/models/results_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/models/testData_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/transfers/connection_relational.pure
  legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/protocols/pure/v1_29_0/transfers/metamodel_relational.pure
  legend-engine-xt-relationalStore-spanner-pure/src/main/resources/core_relational_spanner/relational/protocols/pure/v1_29_0/extension/extension_Spanner.pure
  legend-engine-xt-relationalStore-spanner-pure/src/main/resources/core_relational_spanner/relational/protocols/pure/v1_29_0/models/metamodel_Spanner.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_29_0/extension/extension.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_29_0/extension/extension_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_29_0/models/executionPlan_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_29_0/models/metamodel_connection.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_29_0/models/metamodel_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_29_0/transfers/connection_serviceStore.pure
  legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/v1_29_0/transfers/metamodel_serviceStore.pure
Labels: cla-present

#1330 Implement native pure function to create and execute plans in engine
  legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/store/shared/IResult.java
  legend-engine-pure-ide-light/pom.xml
  legend-engine-pure-ide-light/src/main/java/org/finos/legend/engine/ide/PureIDELight.java
  legend-engine-pure-runtime-execution/pom.xml
  legend-engine-pure-runtime-execution/src/main/java/org/finos/legend/engine/pure/runtime/execution/CoreExternalExecutionCodeRepositoryProvider.java
  legend-engine-pure-runtime-execution/src/main/java/org/finos/legend/engine/pure/runtime/execution/compiled/ExecutionExtensionCompiled.java
  legend-engine-pure-runtime-execution/src/main/java/org/finos/legend/engine/pure/runtime/execution/compiled/natives/LegendExecute.java
  legend-engine-pure-runtime-execution/src/main/java/org/finos/legend/engine/pure/runtime/execution/interpreted/ExecutionExtensionInterpreted.java
  legend-engine-pure-runtime-execution/src/main/java/org/finos/legend/engine/pure/runtime/execution/interpreted/natives/LegendExecute.java
  legend-engine-pure-runtime-execution/src/main/java/org/finos/legend/engine/pure/runtime/execution/shared/LegendExecute.java
  legend-engine-pure-runtime-execution/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.filesystem.repository.CodeRepositoryProvider
  legend-engine-pure-runtime-execution/src/main/resources/META-INF/services/org.finos.legend.pure.runtime.java.compiled.extension.CompiledExtension
  legend-engine-pure-runtime-execution/src/main/resources/META-INF/services/org.finos.legend.pure.runtime.java.interpreted.extension.InterpretedExtension
  legend-engine-pure-runtime-execution/src/main/resources/core_external_execution.definition.json
  legend-engine-pure-runtime-execution/src/main/resources/core_external_execution/execution.pure
  legend-engine-pure-runtime-execution/src/test/java/org/finos/legend/engine/pure/runtime/execution/LegendExecuteTest.java
  legend-engine-pure-runtime-execution/src/test/resources/testModels.txt
  legend-engine-xt-javaPlatformBinding-pure/src/main/resources/core_java_platform_binding/legendJavaPlatformBinding/platform/executionPlanNodes/platform/serialize.pure
  pom.xml
Labels: cla-present

#1238 Cleanup testable framework
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperMappingBuilder.java
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PackageableElementFourthPassBuilder.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/HelperServiceBuilder.java
  legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/ServiceCompilerExtensionImpl.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/CorePureProtocolExtension.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/AtomicTestId.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/TestBatch.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/result/TestExecuted.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/result/TestExecutionStatus.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/result/TestPassed.java
  legend-engine-protocol-pure/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/result/TestResult.java
  legend-engine-pure-code-compiled-core/src/main/resources/core/legend/service/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/data/diagram.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/mapping/metamodel.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/test/diagram.pure
  legend-engine-pure-code-compiled-core/src/main/resources/core/pure/test/testable.pure
  legend-engine-test-runner-mapping/src/main/java/org/finos/legend/engine/testable/mapping/extension/MappingTestRunner.java
  legend-engine-test-runner-mapping/src/main/java/org/finos/legend/engine/testable/mapping/extension/MappingTestableRunnerExtension.java
  legend-engine-test-runner-mapping/src/test/java/org/finos/legend/engine/test/runner/mapping/TestMappingTestRunner.java
  legend-engine-test-runner-mapping/src/test/java/org/finos/legend/engine/testable/mapping/extension/TestMappingTestRunner.java
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestRunner.java
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/testable/service/extension/ServiceTestableRunnerExtension.java
  legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/TestableRunner.java
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/extension/TestRunner.java
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/model/RunTestsTestableInput.java
  legend-engine-testable/src/main/java/org/finos/legend/engine/testable/model/UniqueTestId.java
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/toPureGraph/HelperPersistenceBuilder.java
  legend-engine-xt-persistence-grammar/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/toPureGraph/PersistenceCompilerExtension.java
  legend-engine-xt-persistence-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/persistence/test/PersistenceTestBatch.java
  legend-engine-xt-persistence-pure/src/main/resources/core_persistence/persistence/metamodel.pure
  legend-engine-xt-persistence-pure/src/main/resources/core_persistence/test/validation_rules_test.pure
  legend-engine-xt-persistence-test-runner/src/main/java/org/finos/legend/engine/testable/persistence/extension/PersistenceTestRunner.java
  legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/appendonly/TestAppendOnlyWithAllowDuplicates.java
  legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/appendonly/TestAppendOnlyWithFilterDuplicates.java
  legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/delta/bitemporal/TestPersistenceBitemporalDelta.java
  legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/delta/nontemporal/TestPersistenceNonTemporalDelta.java
  legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/delta/unitemporal/TestPersistenceUnitemporalDelta.java
  legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/snapshot/nontemporal/TestNonTemporalSnapshot.java
  legend-engine-xt-persistence-test-runner/src/test/java/org/finos/legend/engine/testable/persistence/ingestmode/snapshot/unitemporal/TestPersistenceUnitemporalSnapshot.java
  legend-engine-xt-relationalStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/testable/mapping/TestMappingTestRunner.java
  legend-engine-xt-serviceStore-executionPlan/src/test/java/org/finos/legend/engine/plan/execution/stores/service/testable/mapping/TestMappingTestRunner.java
  pom.xml
Labels: cla-present

#1359 Revert "added milestoning validation check on parameters of GetAll, GetAllVersions and GetAllVersionsInRange #1348"
  legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java
  legend-engine-language-pure-compiler/src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java
Labels: cla-present

#1360 If tests is null, log and return
  legend-engine-test-runner-service/src/main/java/org/finos/legend/engine/test/runner/service/ServiceTestRunner.java
Labels: cla-present
